### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.MyIndexedListItem
  commentId: T:Innova.Data.AppSettings.MyIndexedListItem
  id: MyIndexedListItem
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.MyIndexedListItem.Index
  - Innova.Data.AppSettings.MyIndexedListItem.IsPinned
  - Innova.Data.AppSettings.MyIndexedListItem.Key
  langs:
  - csharp
  - vb
  name: MyIndexedListItem
  nameWithType: MyIndexedListItem
  fullName: Innova.Data.AppSettings.MyIndexedListItem
  type: Class
  source:
    id: MyIndexedListItem
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyIndexedListItem.cs
    startLine: 5
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents an indexed list item.
  example: []
  syntax:
    content: public class MyIndexedListItem
    content.vb: Public Class MyIndexedListItem
  inheritance:
  - System.Object
- uid: Innova.Data.AppSettings.MyIndexedListItem.Index
  commentId: P:Innova.Data.AppSettings.MyIndexedListItem.Index
  id: Index
  parent: Innova.Data.AppSettings.MyIndexedListItem
  langs:
  - csharp
  - vb
  name: Index
  nameWithType: MyIndexedListItem.Index
  fullName: Innova.Data.AppSettings.MyIndexedListItem.Index
  type: Property
  source:
    id: Index
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyIndexedListItem.cs
    startLine: 10
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the index of the item.
  example: []
  syntax:
    content: public int Index { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Index As Integer
  overload: Innova.Data.AppSettings.MyIndexedListItem.Index*
- uid: Innova.Data.AppSettings.MyIndexedListItem.Key
  commentId: P:Innova.Data.AppSettings.MyIndexedListItem.Key
  id: Key
  parent: Innova.Data.AppSettings.MyIndexedListItem
  langs:
  - csharp
  - vb
  name: Key
  nameWithType: MyIndexedListItem.Key
  fullName: Innova.Data.AppSettings.MyIndexedListItem.Key
  type: Property
  source:
    id: Key
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyIndexedListItem.cs
    startLine: 15
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the key of the item.
  example: []
  syntax:
    content: public object Key { get; set; }
    parameters: []
    return:
      type: System.Object
    content.vb: Public Property Key As Object
  overload: Innova.Data.AppSettings.MyIndexedListItem.Key*
- uid: Innova.Data.AppSettings.MyIndexedListItem.IsPinned
  commentId: P:Innova.Data.AppSettings.MyIndexedListItem.IsPinned
  id: IsPinned
  parent: Innova.Data.AppSettings.MyIndexedListItem
  langs:
  - csharp
  - vb
  name: IsPinned
  nameWithType: MyIndexedListItem.IsPinned
  fullName: Innova.Data.AppSettings.MyIndexedListItem.IsPinned
  type: Property
  source:
    id: IsPinned
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyIndexedListItem.cs
    startLine: 20
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets a value indicating whether the item is pinned.
  example: []
  syntax:
    content: public bool IsPinned { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsPinned As Boolean
  overload: Innova.Data.AppSettings.MyIndexedListItem.IsPinned*
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.MyIndexedListItem.Index*
  commentId: Overload:Innova.Data.AppSettings.MyIndexedListItem.Index
  href: Innova.Data.AppSettings.MyIndexedListItem.Index.html#Innova_Data_AppSettings_MyIndexedListItem_Index
  name: Index
  nameWithType: MyIndexedListItem.Index
  fullName: Innova.Data.AppSettings.MyIndexedListItem.Index
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Innova.Data.AppSettings.MyIndexedListItem.Key*
  commentId: Overload:Innova.Data.AppSettings.MyIndexedListItem.Key
  href: Innova.Data.AppSettings.MyIndexedListItem.Key.html#Innova_Data_AppSettings_MyIndexedListItem_Key
  name: Key
  nameWithType: MyIndexedListItem.Key
  fullName: Innova.Data.AppSettings.MyIndexedListItem.Key
- uid: Innova.Data.AppSettings.MyIndexedListItem.IsPinned*
  commentId: Overload:Innova.Data.AppSettings.MyIndexedListItem.IsPinned
  href: Innova.Data.AppSettings.MyIndexedListItem.IsPinned.html#Innova_Data_AppSettings_MyIndexedListItem_IsPinned
  name: IsPinned
  nameWithType: MyIndexedListItem.IsPinned
  fullName: Innova.Data.AppSettings.MyIndexedListItem.IsPinned
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
memberLayout: SeparatePages
