### YamlMime:ManagedReference
items:
- uid: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  commentId: T:Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  id: IServerSettingsEntityServiceFactory
  parent: Innova.Rest.Server.Settings
  children:
  - Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService``1
  - Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService
  - Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService``1
  langs:
  - csharp
  - vb
  name: IServerSettingsEntityServiceFactory
  nameWithType: IServerSettingsEntityServiceFactory
  fullName: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  type: Interface
  source:
    id: IServerSettingsEntityServiceFactory
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Settings\IServerSettingsEntityServiceFactory.cs
    startLine: 5
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Settings
  syntax:
    content: public interface IServerSettingsEntityServiceFactory
    content.vb: Public Interface IServerSettingsEntityServiceFactory
- uid: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService
  commentId: M:Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService
  id: CreateDefaultSettingsEntityService
  parent: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  langs:
  - csharp
  - vb
  name: CreateDefaultSettingsEntityService()
  nameWithType: IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService()
  fullName: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService()
  type: Method
  source:
    id: CreateDefaultSettingsEntityService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Settings\IServerSettingsEntityServiceFactory.cs
    startLine: 7
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Settings
  syntax:
    content: ISettingEntityService CreateDefaultSettingsEntityService()
    return:
      type: Innova.Data.AppSettings.Services.ISettingEntityService
    content.vb: Function CreateDefaultSettingsEntityService() As ISettingEntityService
  overload: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService*
- uid: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService``1
  commentId: M:Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService``1
  id: CreateDefaultApplicationSettingService``1
  parent: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  langs:
  - csharp
  - vb
  name: CreateDefaultApplicationSettingService<T>()
  nameWithType: IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService<T>()
  fullName: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService<T>()
  type: Method
  source:
    id: CreateDefaultApplicationSettingService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Settings\IServerSettingsEntityServiceFactory.cs
    startLine: 9
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Settings
  syntax:
    content: 'IApplicationSettingService<T> CreateDefaultApplicationSettingService<T>() where T : class'
    typeParameters:
    - id: T
    return:
      type: Innova.Data.AppSettings.IApplicationSettingService{{T}}
    content.vb: Function CreateDefaultApplicationSettingService(Of T As Class)() As IApplicationSettingService(Of T)
  overload: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService*
  nameWithType.vb: IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService(Of T)()
  fullName.vb: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService(Of T)()
  name.vb: CreateDefaultApplicationSettingService(Of T)()
- uid: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService``1
  commentId: M:Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService``1
  id: CreateDefaultUserSettingService``1
  parent: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  langs:
  - csharp
  - vb
  name: CreateDefaultUserSettingService<T>()
  nameWithType: IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService<T>()
  fullName: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService<T>()
  type: Method
  source:
    id: CreateDefaultUserSettingService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Settings\IServerSettingsEntityServiceFactory.cs
    startLine: 11
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Settings
  syntax:
    content: 'IUserSettingService<T> CreateDefaultUserSettingService<T>() where T : class'
    typeParameters:
    - id: T
    return:
      type: Innova.Data.AppSettings.IUserSettingService{{T}}
    content.vb: Function CreateDefaultUserSettingService(Of T As Class)() As IUserSettingService(Of T)
  overload: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService*
  nameWithType.vb: IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService(Of T)()
  fullName.vb: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService(Of T)()
  name.vb: CreateDefaultUserSettingService(Of T)()
references:
- uid: Innova.Rest.Server.Settings
  commentId: N:Innova.Rest.Server.Settings
  href: Innova.html
  name: Innova.Rest.Server.Settings
  nameWithType: Innova.Rest.Server.Settings
  fullName: Innova.Rest.Server.Settings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Settings
    name: Settings
    href: Innova.Rest.Server.Settings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Settings
    name: Settings
    href: Innova.Rest.Server.Settings.html
- uid: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService*
  commentId: Overload:Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService
  href: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService.html#Innova_Rest_Server_Settings_IServerSettingsEntityServiceFactory_CreateDefaultSettingsEntityService
  name: CreateDefaultSettingsEntityService
  nameWithType: IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService
  fullName: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultSettingsEntityService
- uid: Innova.Data.AppSettings.Services.ISettingEntityService
  commentId: T:Innova.Data.AppSettings.Services.ISettingEntityService
  parent: Innova.Data.AppSettings.Services
  href: Innova.Data.AppSettings.Services.ISettingEntityService.html
  name: ISettingEntityService
  nameWithType: ISettingEntityService
  fullName: Innova.Data.AppSettings.Services.ISettingEntityService
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  href: Innova.html
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
- uid: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService*
  commentId: Overload:Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService
  href: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService.html#Innova_Rest_Server_Settings_IServerSettingsEntityServiceFactory_CreateDefaultApplicationSettingService__1
  name: CreateDefaultApplicationSettingService
  nameWithType: IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService
  fullName: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultApplicationSettingService
- uid: Innova.Data.AppSettings.IApplicationSettingService{{T}}
  commentId: T:Innova.Data.AppSettings.IApplicationSettingService{`0}
  parent: Innova.Data.AppSettings
  definition: Innova.Data.AppSettings.IApplicationSettingService`1
  href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  name: IApplicationSettingService<T>
  nameWithType: IApplicationSettingService<T>
  fullName: Innova.Data.AppSettings.IApplicationSettingService<T>
  nameWithType.vb: IApplicationSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.IApplicationSettingService(Of T)
  name.vb: IApplicationSettingService(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.IApplicationSettingService`1
    name: IApplicationSettingService
    href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.IApplicationSettingService`1
    name: IApplicationSettingService
    href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.IApplicationSettingService`1
  commentId: T:Innova.Data.AppSettings.IApplicationSettingService`1
  href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  name: IApplicationSettingService<T>
  nameWithType: IApplicationSettingService<T>
  fullName: Innova.Data.AppSettings.IApplicationSettingService<T>
  nameWithType.vb: IApplicationSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.IApplicationSettingService(Of T)
  name.vb: IApplicationSettingService(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.IApplicationSettingService`1
    name: IApplicationSettingService
    href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.IApplicationSettingService`1
    name: IApplicationSettingService
    href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService*
  commentId: Overload:Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService
  href: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService.html#Innova_Rest_Server_Settings_IServerSettingsEntityServiceFactory_CreateDefaultUserSettingService__1
  name: CreateDefaultUserSettingService
  nameWithType: IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService
  fullName: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.CreateDefaultUserSettingService
- uid: Innova.Data.AppSettings.IUserSettingService{{T}}
  commentId: T:Innova.Data.AppSettings.IUserSettingService{`0}
  parent: Innova.Data.AppSettings
  definition: Innova.Data.AppSettings.IUserSettingService`1
  href: Innova.Data.AppSettings.IUserSettingService-1.html
  name: IUserSettingService<T>
  nameWithType: IUserSettingService<T>
  fullName: Innova.Data.AppSettings.IUserSettingService<T>
  nameWithType.vb: IUserSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.IUserSettingService(Of T)
  name.vb: IUserSettingService(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.IUserSettingService`1
    name: IUserSettingService
    href: Innova.Data.AppSettings.IUserSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.IUserSettingService`1
    name: IUserSettingService
    href: Innova.Data.AppSettings.IUserSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.IUserSettingService`1
  commentId: T:Innova.Data.AppSettings.IUserSettingService`1
  href: Innova.Data.AppSettings.IUserSettingService-1.html
  name: IUserSettingService<T>
  nameWithType: IUserSettingService<T>
  fullName: Innova.Data.AppSettings.IUserSettingService<T>
  nameWithType.vb: IUserSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.IUserSettingService(Of T)
  name.vb: IUserSettingService(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.IUserSettingService`1
    name: IUserSettingService
    href: Innova.Data.AppSettings.IUserSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.IUserSettingService`1
    name: IUserSettingService
    href: Innova.Data.AppSettings.IUserSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
memberLayout: SeparatePages
