### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  id: AppSettings
  parent: Innova.Data
  children:
  - Innova.Data.AppSettings.ApplicationSettings
  - Innova.Data.AppSettings.ApplicationSettingsTypeConfiguration
  - Innova.Data.AppSettings.EmailTemplate
  - Innova.Data.AppSettings.EntitySavedQuerySetting
  - Innova.Data.AppSettings.EntitySavedQuerySettingConverter
  - Innova.Data.AppSettings.EntitySavedQueryType
  - Innova.Data.AppSettings.IApplicationSettingService
  - Innova.Data.AppSettings.IApplicationSettingService`1
  - Innova.Data.AppSettings.ILayoutService
  - Innova.Data.AppSettings.ISavedQueryService
  - Innova.Data.AppSettings.IServiceCollectionSettings
  - Innova.Data.AppSettings.IUserSettingService
  - Innova.Data.AppSettings.IUserSettingServiceSave
  - Innova.Data.AppSettings.IUserSettingService`1
  - Innova.Data.AppSettings.Interfaces
  - Innova.Data.AppSettings.Layout
  - Innova.Data.AppSettings.MruList
  - Innova.Data.AppSettings.MyIndexedListItem
  - Innova.Data.AppSettings.MyLatestList`1
  - Innova.Data.AppSettings.MyList`1
  - Innova.Data.AppSettings.MyQueue`1
  - Innova.Data.AppSettings.Services
  - Innova.Data.AppSettings.UserSettings
  - Innova.Data.AppSettings.UserSettingsTypeConfiguration
  - Innova.Data.AppSettings.ViewLayout
  - Innova.Data.AppSettings.ViewLayoutSetting
  - Innova.Data.AppSettings.ViewLayoutSettingNew
  - Innova.Data.AppSettings.ViewLayoutypeConverter
  - Innova.Data.AppSettings.XMLTypeConverter
  langs:
  - csharp
  - vb
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  type: Namespace
  assemblies:
  - Innova.Data
references:
- uid: Innova.Data.AppSettings.Interfaces
  commentId: N:Innova.Data.AppSettings.Interfaces
  href: Innova.html
  name: Innova.Data.AppSettings.Interfaces
  nameWithType: Innova.Data.AppSettings.Interfaces
  fullName: Innova.Data.AppSettings.Interfaces
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Interfaces
    name: Interfaces
    href: Innova.Data.AppSettings.Interfaces.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Interfaces
    name: Interfaces
    href: Innova.Data.AppSettings.Interfaces.html
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  href: Innova.html
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
- uid: Innova.Data.AppSettings.ApplicationSettings
  commentId: T:Innova.Data.AppSettings.ApplicationSettings
  href: Innova.Data.AppSettings.ApplicationSettings.html
  name: ApplicationSettings
  nameWithType: ApplicationSettings
  fullName: Innova.Data.AppSettings.ApplicationSettings
- uid: Innova.Data.AppSettings.ApplicationSettingsTypeConfiguration
  commentId: T:Innova.Data.AppSettings.ApplicationSettingsTypeConfiguration
  href: Innova.Data.AppSettings.ApplicationSettingsTypeConfiguration.html
  name: ApplicationSettingsTypeConfiguration
  nameWithType: ApplicationSettingsTypeConfiguration
  fullName: Innova.Data.AppSettings.ApplicationSettingsTypeConfiguration
- uid: Innova.Data.AppSettings.EmailTemplate
  commentId: T:Innova.Data.AppSettings.EmailTemplate
  href: Innova.Data.AppSettings.EmailTemplate.html
  name: EmailTemplate
  nameWithType: EmailTemplate
  fullName: Innova.Data.AppSettings.EmailTemplate
- uid: Innova.Data.AppSettings.EntitySavedQuerySetting
  commentId: T:Innova.Data.AppSettings.EntitySavedQuerySetting
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.EntitySavedQuerySetting.html
  name: EntitySavedQuerySetting
  nameWithType: EntitySavedQuerySetting
  fullName: Innova.Data.AppSettings.EntitySavedQuerySetting
- uid: Innova.Data.AppSettings.EntitySavedQuerySettingConverter
  commentId: T:Innova.Data.AppSettings.EntitySavedQuerySettingConverter
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.EntitySavedQuerySettingConverter.html
  name: EntitySavedQuerySettingConverter
  nameWithType: EntitySavedQuerySettingConverter
  fullName: Innova.Data.AppSettings.EntitySavedQuerySettingConverter
- uid: Innova.Data.AppSettings.EntitySavedQueryType
  commentId: T:Innova.Data.AppSettings.EntitySavedQueryType
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.EntitySavedQueryType.html
  name: EntitySavedQueryType
  nameWithType: EntitySavedQueryType
  fullName: Innova.Data.AppSettings.EntitySavedQueryType
- uid: Innova.Data.AppSettings.IApplicationSettingService
  commentId: T:Innova.Data.AppSettings.IApplicationSettingService
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.IApplicationSettingService.html
  name: IApplicationSettingService
  nameWithType: IApplicationSettingService
  fullName: Innova.Data.AppSettings.IApplicationSettingService
- uid: Innova.Data.AppSettings.IApplicationSettingService`1
  commentId: T:Innova.Data.AppSettings.IApplicationSettingService`1
  href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  name: IApplicationSettingService<T>
  nameWithType: IApplicationSettingService<T>
  fullName: Innova.Data.AppSettings.IApplicationSettingService<T>
  nameWithType.vb: IApplicationSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.IApplicationSettingService(Of T)
  name.vb: IApplicationSettingService(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.IApplicationSettingService`1
    name: IApplicationSettingService
    href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.IApplicationSettingService`1
    name: IApplicationSettingService
    href: Innova.Data.AppSettings.IApplicationSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.ILayoutService
  commentId: T:Innova.Data.AppSettings.ILayoutService
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ILayoutService.html
  name: ILayoutService
  nameWithType: ILayoutService
  fullName: Innova.Data.AppSettings.ILayoutService
- uid: Innova.Data.AppSettings.ISavedQueryService
  commentId: T:Innova.Data.AppSettings.ISavedQueryService
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ISavedQueryService.html
  name: ISavedQueryService
  nameWithType: ISavedQueryService
  fullName: Innova.Data.AppSettings.ISavedQueryService
- uid: Innova.Data.AppSettings.IServiceCollectionSettings
  commentId: T:Innova.Data.AppSettings.IServiceCollectionSettings
  href: Innova.Data.AppSettings.IServiceCollectionSettings.html
  name: IServiceCollectionSettings
  nameWithType: IServiceCollectionSettings
  fullName: Innova.Data.AppSettings.IServiceCollectionSettings
- uid: Innova.Data.AppSettings.IUserSettingService
  commentId: T:Innova.Data.AppSettings.IUserSettingService
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.IUserSettingService.html
  name: IUserSettingService
  nameWithType: IUserSettingService
  fullName: Innova.Data.AppSettings.IUserSettingService
- uid: Innova.Data.AppSettings.IUserSettingServiceSave
  commentId: T:Innova.Data.AppSettings.IUserSettingServiceSave
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.IUserSettingServiceSave.html
  name: IUserSettingServiceSave
  nameWithType: IUserSettingServiceSave
  fullName: Innova.Data.AppSettings.IUserSettingServiceSave
- uid: Innova.Data.AppSettings.IUserSettingService`1
  commentId: T:Innova.Data.AppSettings.IUserSettingService`1
  href: Innova.Data.AppSettings.IUserSettingService-1.html
  name: IUserSettingService<T>
  nameWithType: IUserSettingService<T>
  fullName: Innova.Data.AppSettings.IUserSettingService<T>
  nameWithType.vb: IUserSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.IUserSettingService(Of T)
  name.vb: IUserSettingService(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.IUserSettingService`1
    name: IUserSettingService
    href: Innova.Data.AppSettings.IUserSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.IUserSettingService`1
    name: IUserSettingService
    href: Innova.Data.AppSettings.IUserSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.Layout
  commentId: T:Innova.Data.AppSettings.Layout
  href: Innova.Data.AppSettings.Layout.html
  name: Layout
  nameWithType: Layout
  fullName: Innova.Data.AppSettings.Layout
- uid: Innova.Data.AppSettings.MruList
  commentId: T:Innova.Data.AppSettings.MruList
  href: Innova.Data.AppSettings.MruList.html
  name: MruList
  nameWithType: MruList
  fullName: Innova.Data.AppSettings.MruList
- uid: Innova.Data.AppSettings.MyIndexedListItem
  commentId: T:Innova.Data.AppSettings.MyIndexedListItem
  href: Innova.Data.AppSettings.MyIndexedListItem.html
  name: MyIndexedListItem
  nameWithType: MyIndexedListItem
  fullName: Innova.Data.AppSettings.MyIndexedListItem
- uid: Innova.Data.AppSettings.MyLatestList`1
  commentId: T:Innova.Data.AppSettings.MyLatestList`1
  href: Innova.Data.AppSettings.MyLatestList-1.html
  name: MyLatestList<KeyType>
  nameWithType: MyLatestList<KeyType>
  fullName: Innova.Data.AppSettings.MyLatestList<KeyType>
  nameWithType.vb: MyLatestList(Of KeyType)
  fullName.vb: Innova.Data.AppSettings.MyLatestList(Of KeyType)
  name.vb: MyLatestList(Of KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyLatestList`1
    name: MyLatestList
    href: Innova.Data.AppSettings.MyLatestList-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.MyLatestList`1
    name: MyLatestList
    href: Innova.Data.AppSettings.MyLatestList-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Data.AppSettings.MyList`1
  commentId: T:Innova.Data.AppSettings.MyList`1
  href: Innova.Data.AppSettings.MyList-1.html
  name: MyList<KeyType>
  nameWithType: MyList<KeyType>
  fullName: Innova.Data.AppSettings.MyList<KeyType>
  nameWithType.vb: MyList(Of KeyType)
  fullName.vb: Innova.Data.AppSettings.MyList(Of KeyType)
  name.vb: MyList(Of KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyList`1
    name: MyList
    href: Innova.Data.AppSettings.MyList-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.MyList`1
    name: MyList
    href: Innova.Data.AppSettings.MyList-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Data.AppSettings.MyQueue`1
  commentId: T:Innova.Data.AppSettings.MyQueue`1
  href: Innova.Data.AppSettings.MyQueue-1.html
  name: MyQueue<KeyType>
  nameWithType: MyQueue<KeyType>
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>
  nameWithType.vb: MyQueue(Of KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType)
  name.vb: MyQueue(Of KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyQueue`1
    name: MyQueue
    href: Innova.Data.AppSettings.MyQueue-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.MyQueue`1
    name: MyQueue
    href: Innova.Data.AppSettings.MyQueue-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Data.AppSettings.UserSettings
  commentId: T:Innova.Data.AppSettings.UserSettings
  href: Innova.Data.AppSettings.UserSettings.html
  name: UserSettings
  nameWithType: UserSettings
  fullName: Innova.Data.AppSettings.UserSettings
- uid: Innova.Data.AppSettings.UserSettingsTypeConfiguration
  commentId: T:Innova.Data.AppSettings.UserSettingsTypeConfiguration
  href: Innova.Data.AppSettings.UserSettingsTypeConfiguration.html
  name: UserSettingsTypeConfiguration
  nameWithType: UserSettingsTypeConfiguration
  fullName: Innova.Data.AppSettings.UserSettingsTypeConfiguration
- uid: Innova.Data.AppSettings.ViewLayout
  commentId: T:Innova.Data.AppSettings.ViewLayout
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ViewLayout.html
  name: ViewLayout
  nameWithType: ViewLayout
  fullName: Innova.Data.AppSettings.ViewLayout
- uid: Innova.Data.AppSettings.ViewLayoutSetting
  commentId: T:Innova.Data.AppSettings.ViewLayoutSetting
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ViewLayoutSetting.html
  name: ViewLayoutSetting
  nameWithType: ViewLayoutSetting
  fullName: Innova.Data.AppSettings.ViewLayoutSetting
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew
  commentId: T:Innova.Data.AppSettings.ViewLayoutSettingNew
  href: Innova.Data.AppSettings.ViewLayoutSettingNew.html
  name: ViewLayoutSettingNew
  nameWithType: ViewLayoutSettingNew
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew
- uid: Innova.Data.AppSettings.ViewLayoutypeConverter
  commentId: T:Innova.Data.AppSettings.ViewLayoutypeConverter
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ViewLayoutypeConverter.html
  name: ViewLayoutypeConverter
  nameWithType: ViewLayoutypeConverter
  fullName: Innova.Data.AppSettings.ViewLayoutypeConverter
- uid: Innova.Data.AppSettings.XMLTypeConverter
  commentId: T:Innova.Data.AppSettings.XMLTypeConverter
  href: Innova.Data.AppSettings.XMLTypeConverter.html
  name: XMLTypeConverter
  nameWithType: XMLTypeConverter
  fullName: Innova.Data.AppSettings.XMLTypeConverter
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
memberLayout: SeparatePages
