### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  commentId: T:Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  id: ILayoutDataServiceBase
  parent: Innova.Data.AppSettings.Services
  children:
  - Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout(System.String,System.String)
  - Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts
  - Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout(System.String,System.String,System.String)
  - Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout(System.String)
  - Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId
  langs:
  - csharp
  - vb
  name: ILayoutDataServiceBase
  nameWithType: ILayoutDataServiceBase
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  type: Interface
  source:
    id: ILayoutDataServiceBase
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutDataServiceBase.cs
    startLine: 5
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Represents the interface for layout data service.
  example: []
  syntax:
    content: public interface ILayoutDataServiceBase
    content.vb: Public Interface ILayoutDataServiceBase
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId
  commentId: P:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId
  id: UserId
  parent: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  langs:
  - csharp
  - vb
  name: UserId
  nameWithType: ILayoutDataServiceBase.UserId
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId
  type: Property
  source:
    id: UserId
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutDataServiceBase.cs
    startLine: 10
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Gets the user ID.
  example: []
  syntax:
    content: string UserId { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property UserId As String
  overload: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId*
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout(System.String,System.String)
  commentId: M:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout(System.String,System.String)
  id: DeleteLayout(System.String,System.String)
  parent: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  langs:
  - csharp
  - vb
  name: DeleteLayout(string, string)
  nameWithType: ILayoutDataServiceBase.DeleteLayout(string, string)
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout(string, string)
  type: Method
  source:
    id: DeleteLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutDataServiceBase.cs
    startLine: 17
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Deletes a layout.
  example: []
  syntax:
    content: void DeleteLayout(string viewname, string layoutname)
    parameters:
    - id: viewname
      type: System.String
      description: The name of the view.
    - id: layoutname
      type: System.String
      description: The name of the layout.
    content.vb: Sub DeleteLayout(viewname As String, layoutname As String)
  overload: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout*
  nameWithType.vb: ILayoutDataServiceBase.DeleteLayout(String, String)
  fullName.vb: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout(String, String)
  name.vb: DeleteLayout(String, String)
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts
  commentId: M:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts
  id: GetLayouts
  parent: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  langs:
  - csharp
  - vb
  name: GetLayouts()
  nameWithType: ILayoutDataServiceBase.GetLayouts()
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts()
  type: Method
  source:
    id: GetLayouts
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutDataServiceBase.cs
    startLine: 22
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Gets all layouts.
  example: []
  syntax:
    content: void GetLayouts()
    content.vb: Sub GetLayouts()
  overload: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts*
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout(System.String,System.String,System.String)
  commentId: M:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout(System.String,System.String,System.String)
  id: GetOrCreateLayout(System.String,System.String,System.String)
  parent: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  langs:
  - csharp
  - vb
  name: GetOrCreateLayout(string, string, string)
  nameWithType: ILayoutDataServiceBase.GetOrCreateLayout(string, string, string)
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout(string, string, string)
  type: Method
  source:
    id: GetOrCreateLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutDataServiceBase.cs
    startLine: 30
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Gets or creates a layout.
  example: []
  syntax:
    content: void GetOrCreateLayout(string viewname, string layoutname, string layout)
    parameters:
    - id: viewname
      type: System.String
      description: The name of the view.
    - id: layoutname
      type: System.String
      description: The name of the layout.
    - id: layout
      type: System.String
      description: The layout content.
    content.vb: Sub GetOrCreateLayout(viewname As String, layoutname As String, layout As String)
  overload: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout*
  nameWithType.vb: ILayoutDataServiceBase.GetOrCreateLayout(String, String, String)
  fullName.vb: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout(String, String, String)
  name.vb: GetOrCreateLayout(String, String, String)
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout(System.String)
  commentId: M:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout(System.String)
  id: GetViewLayout(System.String)
  parent: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  langs:
  - csharp
  - vb
  name: GetViewLayout(string)
  nameWithType: ILayoutDataServiceBase.GetViewLayout(string)
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout(string)
  type: Method
  source:
    id: GetViewLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutDataServiceBase.cs
    startLine: 37
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Gets the view layout.
  example: []
  syntax:
    content: ViewLayout GetViewLayout(string viewname)
    parameters:
    - id: viewname
      type: System.String
      description: The name of the view.
    return:
      type: Innova.Data.AppSettings.ViewLayout
      description: The view layout.
    content.vb: Function GetViewLayout(viewname As String) As ViewLayout
  overload: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout*
  nameWithType.vb: ILayoutDataServiceBase.GetViewLayout(String)
  fullName.vb: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout(String)
  name.vb: GetViewLayout(String)
references:
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  href: Innova.html
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId*
  commentId: Overload:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId
  href: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId.html#Innova_Data_AppSettings_Services_ILayoutDataServiceBase_UserId
  name: UserId
  nameWithType: ILayoutDataServiceBase.UserId
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.UserId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout*
  commentId: Overload:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout
  href: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout.html#Innova_Data_AppSettings_Services_ILayoutDataServiceBase_DeleteLayout_System_String_System_String_
  name: DeleteLayout
  nameWithType: ILayoutDataServiceBase.DeleteLayout
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.DeleteLayout
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts*
  commentId: Overload:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts
  href: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts.html#Innova_Data_AppSettings_Services_ILayoutDataServiceBase_GetLayouts
  name: GetLayouts
  nameWithType: ILayoutDataServiceBase.GetLayouts
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetLayouts
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout*
  commentId: Overload:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout
  href: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout.html#Innova_Data_AppSettings_Services_ILayoutDataServiceBase_GetOrCreateLayout_System_String_System_String_System_String_
  name: GetOrCreateLayout
  nameWithType: ILayoutDataServiceBase.GetOrCreateLayout
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetOrCreateLayout
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout*
  commentId: Overload:Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout
  href: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout.html#Innova_Data_AppSettings_Services_ILayoutDataServiceBase_GetViewLayout_System_String_
  name: GetViewLayout
  nameWithType: ILayoutDataServiceBase.GetViewLayout
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.GetViewLayout
- uid: Innova.Data.AppSettings.ViewLayout
  commentId: T:Innova.Data.AppSettings.ViewLayout
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ViewLayout.html
  name: ViewLayout
  nameWithType: ViewLayout
  fullName: Innova.Data.AppSettings.ViewLayout
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
memberLayout: SeparatePages
