### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.IUserSettingServiceSave
  commentId: T:Innova.Data.AppSettings.IUserSettingServiceSave
  id: IUserSettingServiceSave
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.IUserSettingServiceSave.Save
  langs:
  - csharp
  - vb
  name: IUserSettingServiceSave
  nameWithType: IUserSettingServiceSave
  fullName: Innova.Data.AppSettings.IUserSettingServiceSave
  type: Interface
  source:
    id: IUserSettingServiceSave
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IUserSettingService.cs
    startLine: 55
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents a user setting service that provides operations for saving user settings.
  example: []
  syntax:
    content: public interface IUserSettingServiceSave
    content.vb: Public Interface IUserSettingServiceSave
- uid: Innova.Data.AppSettings.IUserSettingServiceSave.Save
  commentId: M:Innova.Data.AppSettings.IUserSettingServiceSave.Save
  id: Save
  parent: Innova.Data.AppSettings.IUserSettingServiceSave
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: IUserSettingServiceSave.Save()
  fullName: Innova.Data.AppSettings.IUserSettingServiceSave.Save()
  type: Method
  source:
    id: Save
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IUserSettingService.cs
    startLine: 61
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Saves the user settings.
  example: []
  syntax:
    content: Task Save()
    return:
      type: System.Threading.Tasks.Task
      description: A task representing the asynchronous operation.
    content.vb: Function Save() As Task
  overload: Innova.Data.AppSettings.IUserSettingServiceSave.Save*
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Data.AppSettings.IUserSettingServiceSave.Save*
  commentId: Overload:Innova.Data.AppSettings.IUserSettingServiceSave.Save
  href: Innova.Data.AppSettings.IUserSettingServiceSave.Save.html#Innova_Data_AppSettings_IUserSettingServiceSave_Save
  name: Save
  nameWithType: IUserSettingServiceSave.Save
  fullName: Innova.Data.AppSettings.IUserSettingServiceSave.Save
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
memberLayout: SeparatePages
