### YamlMime:ManagedReference
items:
- uid: Innova.Data.Entity.Configuration
  commentId: N:Innova.Data.Entity.Configuration
  id: Configuration
  parent: Innova.Data.Entity
  children:
  - Innova.Data.Entity.Configuration.SqlApplicationRolesInterceptor
  - Innova.Data.Entity.Configuration.SqlConnectionExtensions
  - Innova.Data.Entity.Configuration.UserNameInterceptor
  langs:
  - csharp
  - vb
  name: Innova.Data.Entity.Configuration
  nameWithType: Innova.Data.Entity.Configuration
  fullName: Innova.Data.Entity.Configuration
  type: Namespace
  assemblies:
  - Innova.Data
references:
- uid: Innova.Data.Entity.Configuration.SqlApplicationRolesInterceptor
  commentId: T:Innova.Data.Entity.Configuration.SqlApplicationRolesInterceptor
  href: Innova.Data.Entity.Configuration.SqlApplicationRolesInterceptor.html
  name: SqlApplicationRolesInterceptor
  nameWithType: SqlApplicationRolesInterceptor
  fullName: Innova.Data.Entity.Configuration.SqlApplicationRolesInterceptor
- uid: Innova.Data.Entity.Configuration.SqlConnectionExtensions
  commentId: T:Innova.Data.Entity.Configuration.SqlConnectionExtensions
  href: Innova.Data.Entity.Configuration.SqlConnectionExtensions.html
  name: SqlConnectionExtensions
  nameWithType: SqlConnectionExtensions
  fullName: Innova.Data.Entity.Configuration.SqlConnectionExtensions
- uid: Innova.Data.Entity.Configuration.UserNameInterceptor
  commentId: T:Innova.Data.Entity.Configuration.UserNameInterceptor
  href: Innova.Data.Entity.Configuration.UserNameInterceptor.html
  name: UserNameInterceptor
  nameWithType: UserNameInterceptor
  fullName: Innova.Data.Entity.Configuration.UserNameInterceptor
memberLayout: SeparatePages
