### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.ViewLayout
  commentId: T:Innova.Data.AppSettings.ViewLayout
  id: ViewLayout
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.ViewLayout.#ctor
  - Innova.Data.AppSettings.ViewLayout.Layouts
  - Innova.Data.AppSettings.ViewLayout.ViewName
  langs:
  - csharp
  - vb
  name: ViewLayout
  nameWithType: ViewLayout
  fullName: Innova.Data.AppSettings.ViewLayout
  type: Class
  source:
    id: ViewLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayout.cs
    startLine: 13
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents a view layout.
  example: []
  syntax:
    content: >-
      [Serializable]

      [TypeConverter(typeof(ViewLayoutypeConverter))]

      public class ViewLayout
    content.vb: >-
      <Serializable>

      <TypeConverter(GetType(ViewLayoutypeConverter))>

      Public Class ViewLayout
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  - type: System.ComponentModel.TypeConverterAttribute
    ctor: System.ComponentModel.TypeConverterAttribute.#ctor(System.Type)
    arguments:
    - type: System.Type
      value: Innova.Data.AppSettings.ViewLayoutypeConverter
- uid: Innova.Data.AppSettings.ViewLayout.ViewName
  commentId: P:Innova.Data.AppSettings.ViewLayout.ViewName
  id: ViewName
  parent: Innova.Data.AppSettings.ViewLayout
  langs:
  - csharp
  - vb
  name: ViewName
  nameWithType: ViewLayout.ViewName
  fullName: Innova.Data.AppSettings.ViewLayout.ViewName
  type: Property
  source:
    id: ViewName
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayout.cs
    startLine: 20
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the name of the view.
  example: []
  syntax:
    content: public string ViewName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ViewName As String
  overload: Innova.Data.AppSettings.ViewLayout.ViewName*
- uid: Innova.Data.AppSettings.ViewLayout.Layouts
  commentId: P:Innova.Data.AppSettings.ViewLayout.Layouts
  id: Layouts
  parent: Innova.Data.AppSettings.ViewLayout
  langs:
  - csharp
  - vb
  name: Layouts
  nameWithType: ViewLayout.Layouts
  fullName: Innova.Data.AppSettings.ViewLayout.Layouts
  type: Property
  source:
    id: Layouts
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayout.cs
    startLine: 25
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the list of layouts.
  example: []
  syntax:
    content: public List<Layout> Layouts { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Innova.Data.AppSettings.Layout}
    content.vb: Public Property Layouts As List(Of Layout)
  overload: Innova.Data.AppSettings.ViewLayout.Layouts*
- uid: Innova.Data.AppSettings.ViewLayout.#ctor
  commentId: M:Innova.Data.AppSettings.ViewLayout.#ctor
  id: '#ctor'
  parent: Innova.Data.AppSettings.ViewLayout
  langs:
  - csharp
  - vb
  name: ViewLayout()
  nameWithType: ViewLayout.ViewLayout()
  fullName: Innova.Data.AppSettings.ViewLayout.ViewLayout()
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayout.cs
    startLine: 30
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Initializes a new instance of the <xref href="Innova.Data.AppSettings.ViewLayout" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public ViewLayout()
    content.vb: Public Sub New()
  overload: Innova.Data.AppSettings.ViewLayout.#ctor*
  nameWithType.vb: ViewLayout.New()
  fullName.vb: Innova.Data.AppSettings.ViewLayout.New()
  name.vb: New()
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.ViewLayout.ViewName*
  commentId: Overload:Innova.Data.AppSettings.ViewLayout.ViewName
  href: Innova.Data.AppSettings.ViewLayout.ViewName.html#Innova_Data_AppSettings_ViewLayout_ViewName
  name: ViewName
  nameWithType: ViewLayout.ViewName
  fullName: Innova.Data.AppSettings.ViewLayout.ViewName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Data.AppSettings.ViewLayout.Layouts*
  commentId: Overload:Innova.Data.AppSettings.ViewLayout.Layouts
  href: Innova.Data.AppSettings.ViewLayout.Layouts.html#Innova_Data_AppSettings_ViewLayout_Layouts
  name: Layouts
  nameWithType: ViewLayout.Layouts
  fullName: Innova.Data.AppSettings.ViewLayout.Layouts
- uid: System.Collections.Generic.List{Innova.Data.AppSettings.Layout}
  commentId: T:System.Collections.Generic.List{Innova.Data.AppSettings.Layout}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<Layout>
  nameWithType: List<Layout>
  fullName: System.Collections.Generic.List<Innova.Data.AppSettings.Layout>
  nameWithType.vb: List(Of Layout)
  fullName.vb: System.Collections.Generic.List(Of Innova.Data.AppSettings.Layout)
  name.vb: List(Of Layout)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Innova.Data.AppSettings.Layout
    name: Layout
    href: Innova.Data.AppSettings.Layout.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.AppSettings.Layout
    name: Layout
    href: Innova.Data.AppSettings.Layout.html
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Innova.Data.AppSettings.ViewLayout
  commentId: T:Innova.Data.AppSettings.ViewLayout
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ViewLayout.html
  name: ViewLayout
  nameWithType: ViewLayout
  fullName: Innova.Data.AppSettings.ViewLayout
- uid: Innova.Data.AppSettings.ViewLayout.#ctor*
  commentId: Overload:Innova.Data.AppSettings.ViewLayout.#ctor
  href: Innova.Data.AppSettings.ViewLayout.-ctor.html#Innova_Data_AppSettings_ViewLayout__ctor
  name: ViewLayout
  nameWithType: ViewLayout.ViewLayout
  fullName: Innova.Data.AppSettings.ViewLayout.ViewLayout
  nameWithType.vb: ViewLayout.New
  fullName.vb: Innova.Data.AppSettings.ViewLayout.New
  name.vb: New
memberLayout: SeparatePages
