### YamlMime:ManagedReference
items:
- uid: Innova.Data.Revision.EntityRevisionServiceConfiguration`1
  commentId: T:Innova.Data.Revision.EntityRevisionServiceConfiguration`1
  id: EntityRevisionServiceConfiguration`1
  parent: Innova.Data.Revision
  children:
  - Innova.Data.Revision.EntityRevisionServiceConfiguration`1.ImplementRead
  langs:
  - csharp
  - vb
  name: EntityRevisionServiceConfiguration<T>
  nameWithType: EntityRevisionServiceConfiguration<T>
  fullName: Innova.Data.Revision.EntityRevisionServiceConfiguration<T>
  type: Class
  source:
    id: EntityRevisionServiceConfiguration
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Revision\EntityRevisionServiceConfiguration.cs
    startLine: 6
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Revision
  summary: Represents the configuration for the entity revision service.
  example: []
  syntax:
    content: 'public class EntityRevisionServiceConfiguration<T> : IEntityRevisionServiceConfiguration<T> where T : class'
    typeParameters:
    - id: T
      description: The type of the entity.
    content.vb: Public Class EntityRevisionServiceConfiguration(Of T As Class) Implements IEntityRevisionServiceConfiguration(Of T)
  inheritance:
  - System.Object
  implements:
  - Innova.Data.Revision.IEntityRevisionServiceConfiguration{{T}}
  nameWithType.vb: EntityRevisionServiceConfiguration(Of T)
  fullName.vb: Innova.Data.Revision.EntityRevisionServiceConfiguration(Of T)
  name.vb: EntityRevisionServiceConfiguration(Of T)
- uid: Innova.Data.Revision.EntityRevisionServiceConfiguration`1.ImplementRead
  commentId: P:Innova.Data.Revision.EntityRevisionServiceConfiguration`1.ImplementRead
  id: ImplementRead
  parent: Innova.Data.Revision.EntityRevisionServiceConfiguration`1
  langs:
  - csharp
  - vb
  name: ImplementRead
  nameWithType: EntityRevisionServiceConfiguration<T>.ImplementRead
  fullName: Innova.Data.Revision.EntityRevisionServiceConfiguration<T>.ImplementRead
  type: Property
  source:
    id: ImplementRead
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Revision\EntityRevisionServiceConfiguration.cs
    startLine: 11
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Revision
  summary: Gets or sets a value indicating whether to implement the read operation.
  example: []
  syntax:
    content: public bool ImplementRead { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ImplementRead As Boolean
  overload: Innova.Data.Revision.EntityRevisionServiceConfiguration`1.ImplementRead*
  implements:
  - Innova.Data.Revision.IEntityRevisionServiceConfiguration{{T}}.ImplementRead
  nameWithType.vb: EntityRevisionServiceConfiguration(Of T).ImplementRead
  fullName.vb: Innova.Data.Revision.EntityRevisionServiceConfiguration(Of T).ImplementRead
references:
- uid: Innova.Data.Revision
  commentId: N:Innova.Data.Revision
  href: Innova.html
  name: Innova.Data.Revision
  nameWithType: Innova.Data.Revision
  fullName: Innova.Data.Revision
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Revision
    name: Revision
    href: Innova.Data.Revision.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Revision
    name: Revision
    href: Innova.Data.Revision.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration{{T}}
  commentId: T:Innova.Data.Revision.IEntityRevisionServiceConfiguration{`0}
  parent: Innova.Data.Revision
  definition: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
  href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.html
  name: IEntityRevisionServiceConfiguration<T>
  nameWithType: IEntityRevisionServiceConfiguration<T>
  fullName: Innova.Data.Revision.IEntityRevisionServiceConfiguration<T>
  nameWithType.vb: IEntityRevisionServiceConfiguration(Of T)
  fullName.vb: Innova.Data.Revision.IEntityRevisionServiceConfiguration(Of T)
  name.vb: IEntityRevisionServiceConfiguration(Of T)
  spec.csharp:
  - uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
    name: IEntityRevisionServiceConfiguration
    href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
    name: IEntityRevisionServiceConfiguration
    href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
  commentId: T:Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
  href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.html
  name: IEntityRevisionServiceConfiguration<T>
  nameWithType: IEntityRevisionServiceConfiguration<T>
  fullName: Innova.Data.Revision.IEntityRevisionServiceConfiguration<T>
  nameWithType.vb: IEntityRevisionServiceConfiguration(Of T)
  fullName.vb: Innova.Data.Revision.IEntityRevisionServiceConfiguration(Of T)
  name.vb: IEntityRevisionServiceConfiguration(Of T)
  spec.csharp:
  - uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
    name: IEntityRevisionServiceConfiguration
    href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
    name: IEntityRevisionServiceConfiguration
    href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.Revision.EntityRevisionServiceConfiguration`1.ImplementRead*
  commentId: Overload:Innova.Data.Revision.EntityRevisionServiceConfiguration`1.ImplementRead
  href: Innova.Data.Revision.EntityRevisionServiceConfiguration-1.ImplementRead.html#Innova_Data_Revision_EntityRevisionServiceConfiguration_1_ImplementRead
  name: ImplementRead
  nameWithType: EntityRevisionServiceConfiguration<T>.ImplementRead
  fullName: Innova.Data.Revision.EntityRevisionServiceConfiguration<T>.ImplementRead
  nameWithType.vb: EntityRevisionServiceConfiguration(Of T).ImplementRead
  fullName.vb: Innova.Data.Revision.EntityRevisionServiceConfiguration(Of T).ImplementRead
- uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration{{T}}.ImplementRead
  commentId: P:Innova.Data.Revision.IEntityRevisionServiceConfiguration{`0}.ImplementRead
  parent: Innova.Data.Revision.IEntityRevisionServiceConfiguration{{T}}
  definition: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead
  href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.ImplementRead.html#Innova_Data_Revision_IEntityRevisionServiceConfiguration_1_ImplementRead
  name: ImplementRead
  nameWithType: IEntityRevisionServiceConfiguration<T>.ImplementRead
  fullName: Innova.Data.Revision.IEntityRevisionServiceConfiguration<T>.ImplementRead
  nameWithType.vb: IEntityRevisionServiceConfiguration(Of T).ImplementRead
  fullName.vb: Innova.Data.Revision.IEntityRevisionServiceConfiguration(Of T).ImplementRead
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead
  commentId: P:Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead
  href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.ImplementRead.html#Innova_Data_Revision_IEntityRevisionServiceConfiguration_1_ImplementRead
  name: ImplementRead
  nameWithType: IEntityRevisionServiceConfiguration<T>.ImplementRead
  fullName: Innova.Data.Revision.IEntityRevisionServiceConfiguration<T>.ImplementRead
  nameWithType.vb: IEntityRevisionServiceConfiguration(Of T).ImplementRead
  fullName.vb: Innova.Data.Revision.IEntityRevisionServiceConfiguration(Of T).ImplementRead
memberLayout: SeparatePages
