### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.ILayoutService
  commentId: T:Innova.Data.AppSettings.ILayoutService
  id: ILayoutService
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.ILayoutService.DefaultLayout
  - Innova.Data.AppSettings.ILayoutService.UserLayout
  langs:
  - csharp
  - vb
  name: ILayoutService
  nameWithType: ILayoutService
  fullName: Innova.Data.AppSettings.ILayoutService
  type: Interface
  source:
    id: ILayoutService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutService.cs
    startLine: 8
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents a service for managing layout data.
  example: []
  syntax:
    content: public interface ILayoutService
    content.vb: Public Interface ILayoutService
- uid: Innova.Data.AppSettings.ILayoutService.UserLayout
  commentId: P:Innova.Data.AppSettings.ILayoutService.UserLayout
  id: UserLayout
  parent: Innova.Data.AppSettings.ILayoutService
  langs:
  - csharp
  - vb
  name: UserLayout
  nameWithType: ILayoutService.UserLayout
  fullName: Innova.Data.AppSettings.ILayoutService.UserLayout
  type: Property
  source:
    id: UserLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutService.cs
    startLine: 13
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the user layout data service.
  example: []
  syntax:
    content: ILayoutDataServiceBase UserLayout { get; }
    parameters: []
    return:
      type: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
    content.vb: ReadOnly Property UserLayout As ILayoutDataServiceBase
  overload: Innova.Data.AppSettings.ILayoutService.UserLayout*
- uid: Innova.Data.AppSettings.ILayoutService.DefaultLayout
  commentId: P:Innova.Data.AppSettings.ILayoutService.DefaultLayout
  id: DefaultLayout
  parent: Innova.Data.AppSettings.ILayoutService
  langs:
  - csharp
  - vb
  name: DefaultLayout
  nameWithType: ILayoutService.DefaultLayout
  fullName: Innova.Data.AppSettings.ILayoutService.DefaultLayout
  type: Property
  source:
    id: DefaultLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ILayoutService.cs
    startLine: 18
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the default layout data service.
  example: []
  syntax:
    content: ILayoutDataServiceBase DefaultLayout { get; }
    parameters: []
    return:
      type: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
    content.vb: ReadOnly Property DefaultLayout As ILayoutDataServiceBase
  overload: Innova.Data.AppSettings.ILayoutService.DefaultLayout*
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Data.AppSettings.ILayoutService.UserLayout*
  commentId: Overload:Innova.Data.AppSettings.ILayoutService.UserLayout
  href: Innova.Data.AppSettings.ILayoutService.UserLayout.html#Innova_Data_AppSettings_ILayoutService_UserLayout
  name: UserLayout
  nameWithType: ILayoutService.UserLayout
  fullName: Innova.Data.AppSettings.ILayoutService.UserLayout
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  commentId: T:Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  parent: Innova.Data.AppSettings.Services
  href: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.html
  name: ILayoutDataServiceBase
  nameWithType: ILayoutDataServiceBase
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  href: Innova.html
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
- uid: Innova.Data.AppSettings.ILayoutService.DefaultLayout*
  commentId: Overload:Innova.Data.AppSettings.ILayoutService.DefaultLayout
  href: Innova.Data.AppSettings.ILayoutService.DefaultLayout.html#Innova_Data_AppSettings_ILayoutService_DefaultLayout
  name: DefaultLayout
  nameWithType: ILayoutService.DefaultLayout
  fullName: Innova.Data.AppSettings.ILayoutService.DefaultLayout
memberLayout: SeparatePages
