### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  id: Services
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.Services.AppSettingsServiceLifecycle
  - Innova.Data.AppSettings.Services.ApplicationSettingService`1
  - Innova.Data.AppSettings.Services.BaseUserSetting`1
  - Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
  - Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  - Innova.Data.AppSettings.Services.ISettingEntityService
  - Innova.Data.AppSettings.Services.LayoutDataServiceBase`1
  - Innova.Data.AppSettings.Services.LayoutService`1
  - Innova.Data.AppSettings.Services.SavedQueryService`1
  - Innova.Data.AppSettings.Services.ServiceConstants
  - Innova.Data.AppSettings.Services.SettingEntityService`1
  - Innova.Data.AppSettings.Services.UserLayoutDataService`1
  - Innova.Data.AppSettings.Services.UserSettingService`1
  - Innova.Data.AppSettings.Services.UserSettingsServiceLifecycle
  langs:
  - csharp
  - vb
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  type: Namespace
  assemblies:
  - Innova.Data
references:
- uid: Innova.Data.AppSettings.Services.AppSettingsServiceLifecycle
  commentId: T:Innova.Data.AppSettings.Services.AppSettingsServiceLifecycle
  href: Innova.Data.AppSettings.Services.AppSettingsServiceLifecycle.html
  name: AppSettingsServiceLifecycle
  nameWithType: AppSettingsServiceLifecycle
  fullName: Innova.Data.AppSettings.Services.AppSettingsServiceLifecycle
- uid: Innova.Data.AppSettings.Services.ApplicationSettingService`1
  commentId: T:Innova.Data.AppSettings.Services.ApplicationSettingService`1
  href: Innova.Data.AppSettings.Services.ApplicationSettingService-1.html
  name: ApplicationSettingService<T>
  nameWithType: ApplicationSettingService<T>
  fullName: Innova.Data.AppSettings.Services.ApplicationSettingService<T>
  nameWithType.vb: ApplicationSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.Services.ApplicationSettingService(Of T)
  name.vb: ApplicationSettingService(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.ApplicationSettingService`1
    name: ApplicationSettingService
    href: Innova.Data.AppSettings.Services.ApplicationSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.ApplicationSettingService`1
    name: ApplicationSettingService
    href: Innova.Data.AppSettings.Services.ApplicationSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1
  commentId: T:Innova.Data.AppSettings.Services.BaseUserSetting`1
  href: Innova.Data.AppSettings.Services.BaseUserSetting-1.html
  name: BaseUserSetting<T>
  nameWithType: BaseUserSetting<T>
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>
  nameWithType.vb: BaseUserSetting(Of T)
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T)
  name.vb: BaseUserSetting(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.BaseUserSetting`1
    name: BaseUserSetting
    href: Innova.Data.AppSettings.Services.BaseUserSetting-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.BaseUserSetting`1
    name: BaseUserSetting
    href: Innova.Data.AppSettings.Services.BaseUserSetting-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
  commentId: T:Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
  href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  name: DefaultLayoutDataService<TContext>
  nameWithType: DefaultLayoutDataService<TContext>
  fullName: Innova.Data.AppSettings.Services.DefaultLayoutDataService<TContext>
  nameWithType.vb: DefaultLayoutDataService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.DefaultLayoutDataService(Of TContext)
  name.vb: DefaultLayoutDataService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
    name: DefaultLayoutDataService
    href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
    name: DefaultLayoutDataService
    href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  commentId: T:Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  parent: Innova.Data.AppSettings.Services
  href: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.html
  name: ILayoutDataServiceBase
  nameWithType: ILayoutDataServiceBase
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
- uid: Innova.Data.AppSettings.Services.ISettingEntityService
  commentId: T:Innova.Data.AppSettings.Services.ISettingEntityService
  parent: Innova.Data.AppSettings.Services
  href: Innova.Data.AppSettings.Services.ISettingEntityService.html
  name: ISettingEntityService
  nameWithType: ISettingEntityService
  fullName: Innova.Data.AppSettings.Services.ISettingEntityService
- uid: Innova.Data.AppSettings.Services.LayoutDataServiceBase`1
  commentId: T:Innova.Data.AppSettings.Services.LayoutDataServiceBase`1
  href: Innova.Data.AppSettings.Services.LayoutDataServiceBase-1.html
  name: LayoutDataServiceBase<TContext>
  nameWithType: LayoutDataServiceBase<TContext>
  fullName: Innova.Data.AppSettings.Services.LayoutDataServiceBase<TContext>
  nameWithType.vb: LayoutDataServiceBase(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.LayoutDataServiceBase(Of TContext)
  name.vb: LayoutDataServiceBase(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.LayoutDataServiceBase`1
    name: LayoutDataServiceBase
    href: Innova.Data.AppSettings.Services.LayoutDataServiceBase-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.LayoutDataServiceBase`1
    name: LayoutDataServiceBase
    href: Innova.Data.AppSettings.Services.LayoutDataServiceBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.LayoutService`1
  commentId: T:Innova.Data.AppSettings.Services.LayoutService`1
  href: Innova.Data.AppSettings.Services.LayoutService-1.html
  name: LayoutService<TContext>
  nameWithType: LayoutService<TContext>
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>
  nameWithType.vb: LayoutService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext)
  name.vb: LayoutService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.LayoutService`1
    name: LayoutService
    href: Innova.Data.AppSettings.Services.LayoutService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.LayoutService`1
    name: LayoutService
    href: Innova.Data.AppSettings.Services.LayoutService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.SavedQueryService`1
  commentId: T:Innova.Data.AppSettings.Services.SavedQueryService`1
  href: Innova.Data.AppSettings.Services.SavedQueryService-1.html
  name: SavedQueryService<TContext>
  nameWithType: SavedQueryService<TContext>
  fullName: Innova.Data.AppSettings.Services.SavedQueryService<TContext>
  nameWithType.vb: SavedQueryService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.SavedQueryService(Of TContext)
  name.vb: SavedQueryService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.SavedQueryService`1
    name: SavedQueryService
    href: Innova.Data.AppSettings.Services.SavedQueryService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.SavedQueryService`1
    name: SavedQueryService
    href: Innova.Data.AppSettings.Services.SavedQueryService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.ServiceConstants
  commentId: T:Innova.Data.AppSettings.Services.ServiceConstants
  href: Innova.Data.AppSettings.Services.ServiceConstants.html
  name: ServiceConstants
  nameWithType: ServiceConstants
  fullName: Innova.Data.AppSettings.Services.ServiceConstants
- uid: Innova.Data.AppSettings.Services.SettingEntityService`1
  commentId: T:Innova.Data.AppSettings.Services.SettingEntityService`1
  href: Innova.Data.AppSettings.Services.SettingEntityService-1.html
  name: SettingEntityService<TContext>
  nameWithType: SettingEntityService<TContext>
  fullName: Innova.Data.AppSettings.Services.SettingEntityService<TContext>
  nameWithType.vb: SettingEntityService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.SettingEntityService(Of TContext)
  name.vb: SettingEntityService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.SettingEntityService`1
    name: SettingEntityService
    href: Innova.Data.AppSettings.Services.SettingEntityService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.SettingEntityService`1
    name: SettingEntityService
    href: Innova.Data.AppSettings.Services.SettingEntityService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.UserLayoutDataService`1
  commentId: T:Innova.Data.AppSettings.Services.UserLayoutDataService`1
  href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  name: UserLayoutDataService<TContext>
  nameWithType: UserLayoutDataService<TContext>
  fullName: Innova.Data.AppSettings.Services.UserLayoutDataService<TContext>
  nameWithType.vb: UserLayoutDataService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.UserLayoutDataService(Of TContext)
  name.vb: UserLayoutDataService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.UserLayoutDataService`1
    name: UserLayoutDataService
    href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.UserLayoutDataService`1
    name: UserLayoutDataService
    href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.UserSettingService`1
  commentId: T:Innova.Data.AppSettings.Services.UserSettingService`1
  href: Innova.Data.AppSettings.Services.UserSettingService-1.html
  name: UserSettingService<T>
  nameWithType: UserSettingService<T>
  fullName: Innova.Data.AppSettings.Services.UserSettingService<T>
  nameWithType.vb: UserSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.Services.UserSettingService(Of T)
  name.vb: UserSettingService(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.UserSettingService`1
    name: UserSettingService
    href: Innova.Data.AppSettings.Services.UserSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.UserSettingService`1
    name: UserSettingService
    href: Innova.Data.AppSettings.Services.UserSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.Services.UserSettingsServiceLifecycle
  commentId: T:Innova.Data.AppSettings.Services.UserSettingsServiceLifecycle
  href: Innova.Data.AppSettings.Services.UserSettingsServiceLifecycle.html
  name: UserSettingsServiceLifecycle
  nameWithType: UserSettingsServiceLifecycle
  fullName: Innova.Data.AppSettings.Services.UserSettingsServiceLifecycle
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  href: Innova.html
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
memberLayout: SeparatePages
