### YamlMime:ManagedReference
items:
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1
  commentId: T:Innova.Data.Entity.IEntityServiceConfiguration`1
  id: IEntityServiceConfiguration`1
  parent: Innova.Data.Entity
  children:
  - Innova.Data.Entity.IEntityServiceConfiguration`1.DefaultOrderBy
  - Innova.Data.Entity.IEntityServiceConfiguration`1.HasRevision
  - Innova.Data.Entity.IEntityServiceConfiguration`1.PrimaryKeyPropertyNames
  - Innova.Data.Entity.IEntityServiceConfiguration`1.UseCachingWithLookup
  langs:
  - csharp
  - vb
  name: IEntityServiceConfiguration<T>
  nameWithType: IEntityServiceConfiguration<T>
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>
  type: Interface
  source:
    id: IEntityServiceConfiguration
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Entity\IEntityServiceConfiguration.cs
    startLine: 11
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Entity
  summary: Represents the configuration for an entity service.
  example: []
  syntax:
    content: 'public interface IEntityServiceConfiguration<T> where T : class'
    typeParameters:
    - id: T
      description: The type of the entity.
    content.vb: Public Interface IEntityServiceConfiguration(Of T As Class)
  nameWithType.vb: IEntityServiceConfiguration(Of T)
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T)
  name.vb: IEntityServiceConfiguration(Of T)
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1.DefaultOrderBy
  commentId: P:Innova.Data.Entity.IEntityServiceConfiguration`1.DefaultOrderBy
  id: DefaultOrderBy
  parent: Innova.Data.Entity.IEntityServiceConfiguration`1
  langs:
  - csharp
  - vb
  name: DefaultOrderBy
  nameWithType: IEntityServiceConfiguration<T>.DefaultOrderBy
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>.DefaultOrderBy
  type: Property
  source:
    id: DefaultOrderBy
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Entity\IEntityServiceConfiguration.cs
    startLine: 16
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Entity
  summary: Gets the default order by expression for querying entities.
  example: []
  syntax:
    content: Expression<Func<IQueryable<T>, IOrderedQueryable<T>>> DefaultOrderBy { get; }
    parameters: []
    return:
      type: System.Linq.Expressions.Expression{System.Func{System.Linq.IQueryable{{T}},System.Linq.IOrderedQueryable{{T}}}}
    content.vb: ReadOnly Property DefaultOrderBy As Expression(Of Func(Of IQueryable(Of T), IOrderedQueryable(Of T)))
  overload: Innova.Data.Entity.IEntityServiceConfiguration`1.DefaultOrderBy*
  nameWithType.vb: IEntityServiceConfiguration(Of T).DefaultOrderBy
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T).DefaultOrderBy
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1.UseCachingWithLookup
  commentId: P:Innova.Data.Entity.IEntityServiceConfiguration`1.UseCachingWithLookup
  id: UseCachingWithLookup
  parent: Innova.Data.Entity.IEntityServiceConfiguration`1
  langs:
  - csharp
  - vb
  name: UseCachingWithLookup
  nameWithType: IEntityServiceConfiguration<T>.UseCachingWithLookup
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>.UseCachingWithLookup
  type: Property
  source:
    id: UseCachingWithLookup
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Entity\IEntityServiceConfiguration.cs
    startLine: 21
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Entity
  summary: Gets a value indicating whether caching is enabled for lookup operations.
  example: []
  syntax:
    content: bool UseCachingWithLookup { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property UseCachingWithLookup As Boolean
  overload: Innova.Data.Entity.IEntityServiceConfiguration`1.UseCachingWithLookup*
  nameWithType.vb: IEntityServiceConfiguration(Of T).UseCachingWithLookup
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T).UseCachingWithLookup
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1.HasRevision
  commentId: P:Innova.Data.Entity.IEntityServiceConfiguration`1.HasRevision
  id: HasRevision
  parent: Innova.Data.Entity.IEntityServiceConfiguration`1
  langs:
  - csharp
  - vb
  name: HasRevision
  nameWithType: IEntityServiceConfiguration<T>.HasRevision
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>.HasRevision
  type: Property
  source:
    id: HasRevision
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Entity\IEntityServiceConfiguration.cs
    startLine: 26
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Entity
  summary: Gets a value indicating whether the entity has revision history.
  example: []
  syntax:
    content: bool HasRevision { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property HasRevision As Boolean
  overload: Innova.Data.Entity.IEntityServiceConfiguration`1.HasRevision*
  nameWithType.vb: IEntityServiceConfiguration(Of T).HasRevision
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T).HasRevision
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1.PrimaryKeyPropertyNames
  commentId: P:Innova.Data.Entity.IEntityServiceConfiguration`1.PrimaryKeyPropertyNames
  id: PrimaryKeyPropertyNames
  parent: Innova.Data.Entity.IEntityServiceConfiguration`1
  langs:
  - csharp
  - vb
  name: PrimaryKeyPropertyNames
  nameWithType: IEntityServiceConfiguration<T>.PrimaryKeyPropertyNames
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>.PrimaryKeyPropertyNames
  type: Property
  source:
    id: PrimaryKeyPropertyNames
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Entity\IEntityServiceConfiguration.cs
    startLine: 31
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Entity
  summary: Gets the names of the primary key properties of the entity.
  example: []
  syntax:
    content: List<string> PrimaryKeyPropertyNames { get; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: ReadOnly Property PrimaryKeyPropertyNames As List(Of String)
  overload: Innova.Data.Entity.IEntityServiceConfiguration`1.PrimaryKeyPropertyNames*
  nameWithType.vb: IEntityServiceConfiguration(Of T).PrimaryKeyPropertyNames
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T).PrimaryKeyPropertyNames
references:
- uid: Innova.Data.Entity
  commentId: N:Innova.Data.Entity
  href: Innova.html
  name: Innova.Data.Entity
  nameWithType: Innova.Data.Entity
  fullName: Innova.Data.Entity
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Entity
    name: Entity
    href: Innova.Data.Entity.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Entity
    name: Entity
    href: Innova.Data.Entity.html
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1.DefaultOrderBy*
  commentId: Overload:Innova.Data.Entity.IEntityServiceConfiguration`1.DefaultOrderBy
  href: Innova.Data.Entity.IEntityServiceConfiguration-1.DefaultOrderBy.html#Innova_Data_Entity_IEntityServiceConfiguration_1_DefaultOrderBy
  name: DefaultOrderBy
  nameWithType: IEntityServiceConfiguration<T>.DefaultOrderBy
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>.DefaultOrderBy
  nameWithType.vb: IEntityServiceConfiguration(Of T).DefaultOrderBy
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T).DefaultOrderBy
- uid: System.Linq.Expressions.Expression{System.Func{System.Linq.IQueryable{{T}},System.Linq.IOrderedQueryable{{T}}}}
  commentId: T:System.Linq.Expressions.Expression{System.Func{System.Linq.IQueryable{`0},System.Linq.IOrderedQueryable{`0}}}
  parent: System.Linq.Expressions
  definition: System.Linq.Expressions.Expression`1
  href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  name: Expression<Func<IQueryable<T>, IOrderedQueryable<T>>>
  nameWithType: Expression<Func<IQueryable<T>, IOrderedQueryable<T>>>
  fullName: System.Linq.Expressions.Expression<System.Func<System.Linq.IQueryable<T>, System.Linq.IOrderedQueryable<T>>>
  nameWithType.vb: Expression(Of Func(Of IQueryable(Of T), IOrderedQueryable(Of T)))
  fullName.vb: System.Linq.Expressions.Expression(Of System.Func(Of System.Linq.IQueryable(Of T), System.Linq.IOrderedQueryable(Of T)))
  name.vb: Expression(Of Func(Of IQueryable(Of T), IOrderedQueryable(Of T)))
  spec.csharp:
  - uid: System.Linq.Expressions.Expression`1
    name: Expression
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  - name: <
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: <
  - uid: System.Linq.IQueryable`1
    name: IQueryable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.iqueryable-1
  - name: <
  - name: T
  - name: '>'
  - name: ','
  - name: " "
  - uid: System.Linq.IOrderedQueryable`1
    name: IOrderedQueryable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.iorderedqueryable-1
  - name: <
  - name: T
  - name: '>'
  - name: '>'
  - name: '>'
  spec.vb:
  - uid: System.Linq.Expressions.Expression`1
    name: Expression
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Func`2
    name: Func
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.func-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.Linq.IQueryable`1
    name: IQueryable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.iqueryable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: ','
  - name: " "
  - uid: System.Linq.IOrderedQueryable`1
    name: IOrderedQueryable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.iorderedqueryable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: )
  - name: )
- uid: System.Linq.Expressions.Expression`1
  commentId: T:System.Linq.Expressions.Expression`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  name: Expression<TDelegate>
  nameWithType: Expression<TDelegate>
  fullName: System.Linq.Expressions.Expression<TDelegate>
  nameWithType.vb: Expression(Of TDelegate)
  fullName.vb: System.Linq.Expressions.Expression(Of TDelegate)
  name.vb: Expression(Of TDelegate)
  spec.csharp:
  - uid: System.Linq.Expressions.Expression`1
    name: Expression
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  - name: <
  - name: TDelegate
  - name: '>'
  spec.vb:
  - uid: System.Linq.Expressions.Expression`1
    name: Expression
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions.expression-1
  - name: (
  - name: Of
  - name: " "
  - name: TDelegate
  - name: )
- uid: System.Linq.Expressions
  commentId: N:System.Linq.Expressions
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Linq.Expressions
  nameWithType: System.Linq.Expressions
  fullName: System.Linq.Expressions
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Linq
    name: Linq
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq
  - name: .
  - uid: System.Linq.Expressions
    name: Expressions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Linq
    name: Linq
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq
  - name: .
  - uid: System.Linq.Expressions
    name: Expressions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.linq.expressions
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1.UseCachingWithLookup*
  commentId: Overload:Innova.Data.Entity.IEntityServiceConfiguration`1.UseCachingWithLookup
  href: Innova.Data.Entity.IEntityServiceConfiguration-1.UseCachingWithLookup.html#Innova_Data_Entity_IEntityServiceConfiguration_1_UseCachingWithLookup
  name: UseCachingWithLookup
  nameWithType: IEntityServiceConfiguration<T>.UseCachingWithLookup
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>.UseCachingWithLookup
  nameWithType.vb: IEntityServiceConfiguration(Of T).UseCachingWithLookup
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T).UseCachingWithLookup
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1.HasRevision*
  commentId: Overload:Innova.Data.Entity.IEntityServiceConfiguration`1.HasRevision
  href: Innova.Data.Entity.IEntityServiceConfiguration-1.HasRevision.html#Innova_Data_Entity_IEntityServiceConfiguration_1_HasRevision
  name: HasRevision
  nameWithType: IEntityServiceConfiguration<T>.HasRevision
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>.HasRevision
  nameWithType.vb: IEntityServiceConfiguration(Of T).HasRevision
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T).HasRevision
- uid: Innova.Data.Entity.IEntityServiceConfiguration`1.PrimaryKeyPropertyNames*
  commentId: Overload:Innova.Data.Entity.IEntityServiceConfiguration`1.PrimaryKeyPropertyNames
  href: Innova.Data.Entity.IEntityServiceConfiguration-1.PrimaryKeyPropertyNames.html#Innova_Data_Entity_IEntityServiceConfiguration_1_PrimaryKeyPropertyNames
  name: PrimaryKeyPropertyNames
  nameWithType: IEntityServiceConfiguration<T>.PrimaryKeyPropertyNames
  fullName: Innova.Data.Entity.IEntityServiceConfiguration<T>.PrimaryKeyPropertyNames
  nameWithType.vb: IEntityServiceConfiguration(Of T).PrimaryKeyPropertyNames
  fullName.vb: Innova.Data.Entity.IEntityServiceConfiguration(Of T).PrimaryKeyPropertyNames
- uid: System.Collections.Generic.List{System.String}
  commentId: T:System.Collections.Generic.List{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<string>
  nameWithType: List<string>
  fullName: System.Collections.Generic.List<string>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
memberLayout: SeparatePages
