### YamlMime:ManagedReference
items:
- uid: Innova.Data.Security.Builder.ISettingSecurityBuilder`1
  commentId: T:Innova.Data.Security.Builder.ISettingSecurityBuilder`1
  id: ISettingSecurityBuilder`1
  parent: Innova.Data.Security.Builder
  children:
  - Innova.Data.Security.Builder.ISettingSecurityBuilder`1.Settings
  langs:
  - csharp
  - vb
  name: ISettingSecurityBuilder<TSetting>
  nameWithType: ISettingSecurityBuilder<TSetting>
  fullName: Innova.Data.Security.Builder.ISettingSecurityBuilder<TSetting>
  type: Interface
  source:
    id: ISettingSecurityBuilder
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Security\Builder\ISecurityBuilder.cs
    startLine: 28
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Security.Builder
  summary: Represents a security builder interface with settings.
  example: []
  syntax:
    content: 'public interface ISettingSecurityBuilder<TSetting> : ISecurityBuilder where TSetting : class'
    typeParameters:
    - id: TSetting
      description: The type of the settings.
    content.vb: Public Interface ISettingSecurityBuilder(Of TSetting As Class) Inherits ISecurityBuilder
  inheritedMembers:
  - Innova.Data.Security.Builder.ISecurityBuilder.Build
  nameWithType.vb: ISettingSecurityBuilder(Of TSetting)
  fullName.vb: Innova.Data.Security.Builder.ISettingSecurityBuilder(Of TSetting)
  name.vb: ISettingSecurityBuilder(Of TSetting)
- uid: Innova.Data.Security.Builder.ISettingSecurityBuilder`1.Settings
  commentId: P:Innova.Data.Security.Builder.ISettingSecurityBuilder`1.Settings
  id: Settings
  parent: Innova.Data.Security.Builder.ISettingSecurityBuilder`1
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: ISettingSecurityBuilder<TSetting>.Settings
  fullName: Innova.Data.Security.Builder.ISettingSecurityBuilder<TSetting>.Settings
  type: Property
  source:
    id: Settings
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Security\Builder\ISecurityBuilder.cs
    startLine: 33
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Security.Builder
  summary: Gets the settings.
  example: []
  syntax:
    content: TSetting Settings { get; }
    parameters: []
    return:
      type: '{TSetting}'
    content.vb: ReadOnly Property Settings As TSetting
  overload: Innova.Data.Security.Builder.ISettingSecurityBuilder`1.Settings*
  nameWithType.vb: ISettingSecurityBuilder(Of TSetting).Settings
  fullName.vb: Innova.Data.Security.Builder.ISettingSecurityBuilder(Of TSetting).Settings
references:
- uid: Innova.Data.Security.Builder
  commentId: N:Innova.Data.Security.Builder
  href: Innova.html
  name: Innova.Data.Security.Builder
  nameWithType: Innova.Data.Security.Builder
  fullName: Innova.Data.Security.Builder
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Security
    name: Security
    href: Innova.Data.Security.html
  - name: .
  - uid: Innova.Data.Security.Builder
    name: Builder
    href: Innova.Data.Security.Builder.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Security
    name: Security
    href: Innova.Data.Security.html
  - name: .
  - uid: Innova.Data.Security.Builder
    name: Builder
    href: Innova.Data.Security.Builder.html
- uid: Innova.Data.Security.Builder.ISecurityBuilder.Build
  commentId: M:Innova.Data.Security.Builder.ISecurityBuilder.Build
  parent: Innova.Data.Security.Builder.ISecurityBuilder
  href: Innova.Data.Security.Builder.ISecurityBuilder.Build.html#Innova_Data_Security_Builder_ISecurityBuilder_Build
  name: Build()
  nameWithType: ISecurityBuilder.Build()
  fullName: Innova.Data.Security.Builder.ISecurityBuilder.Build()
  spec.csharp:
  - uid: Innova.Data.Security.Builder.ISecurityBuilder.Build
    name: Build
    href: Innova.Data.Security.Builder.ISecurityBuilder.Build.html#Innova_Data_Security_Builder_ISecurityBuilder_Build
  - name: (
  - name: )
  spec.vb:
  - uid: Innova.Data.Security.Builder.ISecurityBuilder.Build
    name: Build
    href: Innova.Data.Security.Builder.ISecurityBuilder.Build.html#Innova_Data_Security_Builder_ISecurityBuilder_Build
  - name: (
  - name: )
- uid: Innova.Data.Security.Builder.ISecurityBuilder
  commentId: T:Innova.Data.Security.Builder.ISecurityBuilder
  parent: Innova.Data.Security.Builder
  href: Innova.Data.Security.Builder.ISecurityBuilder.html
  name: ISecurityBuilder
  nameWithType: ISecurityBuilder
  fullName: Innova.Data.Security.Builder.ISecurityBuilder
- uid: Innova.Data.Security.Builder.ISettingSecurityBuilder`1.Settings*
  commentId: Overload:Innova.Data.Security.Builder.ISettingSecurityBuilder`1.Settings
  href: Innova.Data.Security.Builder.ISettingSecurityBuilder-1.Settings.html#Innova_Data_Security_Builder_ISettingSecurityBuilder_1_Settings
  name: Settings
  nameWithType: ISettingSecurityBuilder<TSetting>.Settings
  fullName: Innova.Data.Security.Builder.ISettingSecurityBuilder<TSetting>.Settings
  nameWithType.vb: ISettingSecurityBuilder(Of TSetting).Settings
  fullName.vb: Innova.Data.Security.Builder.ISettingSecurityBuilder(Of TSetting).Settings
- uid: '{TSetting}'
  commentId: '!:TSetting'
  definition: TSetting
  name: TSetting
  nameWithType: TSetting
  fullName: TSetting
- uid: TSetting
  name: TSetting
  nameWithType: TSetting
  fullName: TSetting
memberLayout: SeparatePages
