### YamlMime:ManagedReference
items:
- uid: Innova.Rest.Client.IInnovaApplicationBuilderExt
  commentId: T:Innova.Rest.Client.IInnovaApplicationBuilderExt
  id: IInnovaApplicationBuilderExt
  parent: Innova.Rest.Client
  children:
  - Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  langs:
  - csharp
  - vb
  name: IInnovaApplicationBuilderExt
  nameWithType: IInnovaApplicationBuilderExt
  fullName: Innova.Rest.Client.IInnovaApplicationBuilderExt
  type: Class
  source:
    id: IInnovaApplicationBuilderExt
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Client\IInnovaApplicationBuilderExt.cs
    startLine: 9
  assemblies:
  - Innova.Rest.Client
  namespace: Innova.Rest.Client
  syntax:
    content: public static class IInnovaApplicationBuilderExt
    content.vb: Public Module IInnovaApplicationBuilderExt
  inheritance:
  - System.Object
- uid: Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  commentId: M:Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  id: UseHttpClient(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  isExtensionMethod: true
  parent: Innova.Rest.Client.IInnovaApplicationBuilderExt
  langs:
  - csharp
  - vb
  name: UseHttpClient(IInnovaApplicationBuilderBase, string)
  nameWithType: IInnovaApplicationBuilderExt.UseHttpClient(IInnovaApplicationBuilderBase, string)
  fullName: Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase, string)
  type: Method
  source:
    id: UseHttpClient
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Client\IInnovaApplicationBuilderExt.cs
    startLine: 11
  assemblies:
  - Innova.Rest.Client
  namespace: Innova.Rest.Client
  syntax:
    content: public static IInnovaApplicationBuilderBase UseHttpClient(this IInnovaApplicationBuilderBase applicationBuilder, string httpPath)
    parameters:
    - id: applicationBuilder
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
    - id: httpPath
      type: System.String
    return:
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
    content.vb: Public Shared Function UseHttpClient(applicationBuilder As IInnovaApplicationBuilderBase, httpPath As String) As IInnovaApplicationBuilderBase
  overload: Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient*
  nameWithType.vb: IInnovaApplicationBuilderExt.UseHttpClient(IInnovaApplicationBuilderBase, String)
  fullName.vb: Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase, String)
  name.vb: UseHttpClient(IInnovaApplicationBuilderBase, String)
references:
- uid: Innova.Rest.Client
  commentId: N:Innova.Rest.Client
  href: Innova.html
  name: Innova.Rest.Client
  nameWithType: Innova.Rest.Client
  fullName: Innova.Rest.Client
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Client
    name: Client
    href: Innova.Rest.Client.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Client
    name: Client
    href: Innova.Rest.Client.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient*
  commentId: Overload:Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient
  href: Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient.html#Innova_Rest_Client_IInnovaApplicationBuilderExt_UseHttpClient_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_System_String_
  name: UseHttpClient
  nameWithType: IInnovaApplicationBuilderExt.UseHttpClient
  fullName: Innova.Rest.Client.IInnovaApplicationBuilderExt.UseHttpClient
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  commentId: T:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  parent: Innova.Abstractions.Builder
  href: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.html
  name: IInnovaApplicationBuilderBase
  nameWithType: IInnovaApplicationBuilderBase
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Abstractions.Builder
  commentId: N:Innova.Abstractions.Builder
  href: Innova.html
  name: Innova.Abstractions.Builder
  nameWithType: Innova.Abstractions.Builder
  fullName: Innova.Abstractions.Builder
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
memberLayout: SeparatePages
