### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.Interfaces.IBaseSettings
  commentId: T:Innova.Data.AppSettings.Interfaces.IBaseSettings
  id: IBaseSettings
  parent: Innova.Data.AppSettings.Interfaces
  children:
  - Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey
  - Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue
  langs:
  - csharp
  - vb
  name: IBaseSettings
  nameWithType: IBaseSettings
  fullName: Innova.Data.AppSettings.Interfaces.IBaseSettings
  type: Interface
  source:
    id: IBaseSettings
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseSettings.cs
    startLine: 5
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Interfaces
  summary: Represents the base settings interface.
  example: []
  syntax:
    content: public interface IBaseSettings
    content.vb: Public Interface IBaseSettings
- uid: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey
  commentId: P:Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey
  id: SettingsKey
  parent: Innova.Data.AppSettings.Interfaces.IBaseSettings
  langs:
  - csharp
  - vb
  name: SettingsKey
  nameWithType: IBaseSettings.SettingsKey
  fullName: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey
  type: Property
  source:
    id: SettingsKey
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseSettings.cs
    startLine: 10
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Interfaces
  summary: Gets or sets the settings key.
  example: []
  syntax:
    content: string SettingsKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property SettingsKey As String
  overload: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey*
- uid: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue
  commentId: P:Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue
  id: SettingsValue
  parent: Innova.Data.AppSettings.Interfaces.IBaseSettings
  langs:
  - csharp
  - vb
  name: SettingsValue
  nameWithType: IBaseSettings.SettingsValue
  fullName: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue
  type: Property
  source:
    id: SettingsValue
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseSettings.cs
    startLine: 15
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Interfaces
  summary: Gets or sets the settings value.
  example: []
  syntax:
    content: string SettingsValue { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property SettingsValue As String
  overload: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue*
references:
- uid: Innova.Data.AppSettings.Interfaces
  commentId: N:Innova.Data.AppSettings.Interfaces
  href: Innova.html
  name: Innova.Data.AppSettings.Interfaces
  nameWithType: Innova.Data.AppSettings.Interfaces
  fullName: Innova.Data.AppSettings.Interfaces
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Interfaces
    name: Interfaces
    href: Innova.Data.AppSettings.Interfaces.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Interfaces
    name: Interfaces
    href: Innova.Data.AppSettings.Interfaces.html
- uid: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey*
  commentId: Overload:Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey
  href: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey.html#Innova_Data_AppSettings_Interfaces_IBaseSettings_SettingsKey
  name: SettingsKey
  nameWithType: IBaseSettings.SettingsKey
  fullName: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue*
  commentId: Overload:Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue
  href: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue.html#Innova_Data_AppSettings_Interfaces_IBaseSettings_SettingsValue
  name: SettingsValue
  nameWithType: IBaseSettings.SettingsValue
  fullName: Innova.Data.AppSettings.Interfaces.IBaseSettings.SettingsValue
memberLayout: SeparatePages
