### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Library.Configuration.UI.IVisibilityService
  commentId: T:Innova.Prism.Library.Configuration.UI.IVisibilityService
  id: IVisibilityService
  parent: Innova.Prism.Library.Configuration.UI
  children:
  - Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility(System.String,System.String)
  - Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility(System.String,System.String)
  langs:
  - csharp
  - vb
  name: IVisibilityService
  nameWithType: IVisibilityService
  fullName: Innova.Prism.Library.Configuration.UI.IVisibilityService
  type: Interface
  source:
    id: IVisibilityService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\IVisibilityService.cs
    startLine: 7
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Represents a service for managing visibility of UI elements.
  example: []
  syntax:
    content: public interface IVisibilityService
    content.vb: Public Interface IVisibilityService
- uid: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility(System.String,System.String)
  commentId: M:Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility(System.String,System.String)
  id: GetGroupVisibility(System.String,System.String)
  parent: Innova.Prism.Library.Configuration.UI.IVisibilityService
  langs:
  - csharp
  - vb
  name: GetGroupVisibility(string, string)
  nameWithType: IVisibilityService.GetGroupVisibility(string, string)
  fullName: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility(string, string)
  type: Method
  source:
    id: GetGroupVisibility
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\IVisibilityService.cs
    startLine: 15
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Gets the visibility of a group of UI elements.
  example: []
  syntax:
    content: Visibility GetGroupVisibility(string entityName, string groupName)
    parameters:
    - id: entityName
      type: System.String
      description: The name of the entity.
    - id: groupName
      type: System.String
      description: The name of the group.
    return:
      type: System.Windows.Visibility
      description: The visibility of the group.
    content.vb: Function GetGroupVisibility(entityName As String, groupName As String) As Visibility
  overload: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility*
  nameWithType.vb: IVisibilityService.GetGroupVisibility(String, String)
  fullName.vb: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility(String, String)
  name.vb: GetGroupVisibility(String, String)
- uid: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility(System.String,System.String)
  commentId: M:Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility(System.String,System.String)
  id: GetVisibility(System.String,System.String)
  parent: Innova.Prism.Library.Configuration.UI.IVisibilityService
  langs:
  - csharp
  - vb
  name: GetVisibility(string, string)
  nameWithType: IVisibilityService.GetVisibility(string, string)
  fullName: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility(string, string)
  type: Method
  source:
    id: GetVisibility
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\IVisibilityService.cs
    startLine: 23
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Gets the visibility of a UI element.
  example: []
  syntax:
    content: Visibility GetVisibility(string entityName, string propertyName)
    parameters:
    - id: entityName
      type: System.String
      description: The name of the entity.
    - id: propertyName
      type: System.String
      description: The name of the property.
    return:
      type: System.Windows.Visibility
      description: The visibility of the UI element.
    content.vb: Function GetVisibility(entityName As String, propertyName As String) As Visibility
  overload: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility*
  nameWithType.vb: IVisibilityService.GetVisibility(String, String)
  fullName.vb: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility(String, String)
  name.vb: GetVisibility(String, String)
references:
- uid: Innova.Prism.Library.Configuration.UI
  commentId: N:Innova.Prism.Library.Configuration.UI
  href: Innova.html
  name: Innova.Prism.Library.Configuration.UI
  nameWithType: Innova.Prism.Library.Configuration.UI
  fullName: Innova.Prism.Library.Configuration.UI
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
- uid: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility*
  commentId: Overload:Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility
  href: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility.html#Innova_Prism_Library_Configuration_UI_IVisibilityService_GetGroupVisibility_System_String_System_String_
  name: GetGroupVisibility
  nameWithType: IVisibilityService.GetGroupVisibility
  fullName: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetGroupVisibility
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Windows.Visibility
  commentId: T:System.Windows.Visibility
  parent: System.Windows
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.windows.visibility
  name: Visibility
  nameWithType: Visibility
  fullName: System.Windows.Visibility
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Windows
  commentId: N:System.Windows
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Windows
  nameWithType: System.Windows
  fullName: System.Windows
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
- uid: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility*
  commentId: Overload:Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility
  href: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility.html#Innova_Prism_Library_Configuration_UI_IVisibilityService_GetVisibility_System_String_System_String_
  name: GetVisibility
  nameWithType: IVisibilityService.GetVisibility
  fullName: Innova.Prism.Library.Configuration.UI.IVisibilityService.GetVisibility
memberLayout: SeparatePages
