### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.Services.LayoutService`1
  commentId: T:Innova.Data.AppSettings.Services.LayoutService`1
  id: LayoutService`1
  parent: Innova.Data.AppSettings.Services
  children:
  - Innova.Data.AppSettings.Services.LayoutService`1.#ctor(Innova.Data.AppSettings.Services.UserLayoutDataService{`0},Innova.Data.AppSettings.Services.DefaultLayoutDataService{`0})
  - Innova.Data.AppSettings.Services.LayoutService`1.DefaultLayout
  - Innova.Data.AppSettings.Services.LayoutService`1.UserLayout
  langs:
  - csharp
  - vb
  name: LayoutService<TContext>
  nameWithType: LayoutService<TContext>
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>
  type: Class
  source:
    id: LayoutService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\LayoutService.cs
    startLine: 12
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Represents a service for managing layout data.
  example: []
  syntax:
    content: 'public class LayoutService<TContext> : ILayoutService where TContext : DbContext'
    typeParameters:
    - id: TContext
      description: The type of the database context.
    content.vb: Public Class LayoutService(Of TContext As DbContext) Implements ILayoutService
  inheritance:
  - System.Object
  implements:
  - Innova.Data.AppSettings.ILayoutService
  nameWithType.vb: LayoutService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext)
  name.vb: LayoutService(Of TContext)
- uid: Innova.Data.AppSettings.Services.LayoutService`1.UserLayout
  commentId: P:Innova.Data.AppSettings.Services.LayoutService`1.UserLayout
  id: UserLayout
  parent: Innova.Data.AppSettings.Services.LayoutService`1
  langs:
  - csharp
  - vb
  name: UserLayout
  nameWithType: LayoutService<TContext>.UserLayout
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>.UserLayout
  type: Property
  source:
    id: UserLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\LayoutService.cs
    startLine: 17
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Gets the user layout data service.
  example: []
  syntax:
    content: public ILayoutDataServiceBase UserLayout { get; }
    parameters: []
    return:
      type: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
    content.vb: Public ReadOnly Property UserLayout As ILayoutDataServiceBase
  overload: Innova.Data.AppSettings.Services.LayoutService`1.UserLayout*
  implements:
  - Innova.Data.AppSettings.ILayoutService.UserLayout
  nameWithType.vb: LayoutService(Of TContext).UserLayout
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext).UserLayout
- uid: Innova.Data.AppSettings.Services.LayoutService`1.DefaultLayout
  commentId: P:Innova.Data.AppSettings.Services.LayoutService`1.DefaultLayout
  id: DefaultLayout
  parent: Innova.Data.AppSettings.Services.LayoutService`1
  langs:
  - csharp
  - vb
  name: DefaultLayout
  nameWithType: LayoutService<TContext>.DefaultLayout
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>.DefaultLayout
  type: Property
  source:
    id: DefaultLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\LayoutService.cs
    startLine: 22
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Gets the default layout data service.
  example: []
  syntax:
    content: public ILayoutDataServiceBase DefaultLayout { get; }
    parameters: []
    return:
      type: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
    content.vb: Public ReadOnly Property DefaultLayout As ILayoutDataServiceBase
  overload: Innova.Data.AppSettings.Services.LayoutService`1.DefaultLayout*
  implements:
  - Innova.Data.AppSettings.ILayoutService.DefaultLayout
  nameWithType.vb: LayoutService(Of TContext).DefaultLayout
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext).DefaultLayout
- uid: Innova.Data.AppSettings.Services.LayoutService`1.#ctor(Innova.Data.AppSettings.Services.UserLayoutDataService{`0},Innova.Data.AppSettings.Services.DefaultLayoutDataService{`0})
  commentId: M:Innova.Data.AppSettings.Services.LayoutService`1.#ctor(Innova.Data.AppSettings.Services.UserLayoutDataService{`0},Innova.Data.AppSettings.Services.DefaultLayoutDataService{`0})
  id: '#ctor(Innova.Data.AppSettings.Services.UserLayoutDataService{`0},Innova.Data.AppSettings.Services.DefaultLayoutDataService{`0})'
  parent: Innova.Data.AppSettings.Services.LayoutService`1
  langs:
  - csharp
  - vb
  name: LayoutService(UserLayoutDataService<TContext>, DefaultLayoutDataService<TContext>)
  nameWithType: LayoutService<TContext>.LayoutService(UserLayoutDataService<TContext>, DefaultLayoutDataService<TContext>)
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>.LayoutService(Innova.Data.AppSettings.Services.UserLayoutDataService<TContext>, Innova.Data.AppSettings.Services.DefaultLayoutDataService<TContext>)
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\LayoutService.cs
    startLine: 29
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Initializes a new instance of the <xref href="Innova.Data.AppSettings.Services.LayoutService%601" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public LayoutService(UserLayoutDataService<TContext> userLayout, DefaultLayoutDataService<TContext> defaultLayout)
    parameters:
    - id: userLayout
      type: Innova.Data.AppSettings.Services.UserLayoutDataService{{TContext}}
      description: The user layout data service.
    - id: defaultLayout
      type: Innova.Data.AppSettings.Services.DefaultLayoutDataService{{TContext}}
      description: The default layout data service.
    content.vb: Public Sub New(userLayout As UserLayoutDataService(Of TContext), defaultLayout As DefaultLayoutDataService(Of TContext))
  overload: Innova.Data.AppSettings.Services.LayoutService`1.#ctor*
  nameWithType.vb: LayoutService(Of TContext).New(UserLayoutDataService(Of TContext), DefaultLayoutDataService(Of TContext))
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext).New(Innova.Data.AppSettings.Services.UserLayoutDataService(Of TContext), Innova.Data.AppSettings.Services.DefaultLayoutDataService(Of TContext))
  name.vb: New(UserLayoutDataService(Of TContext), DefaultLayoutDataService(Of TContext))
references:
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  href: Innova.html
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Innova.Data.AppSettings.ILayoutService
  commentId: T:Innova.Data.AppSettings.ILayoutService
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ILayoutService.html
  name: ILayoutService
  nameWithType: ILayoutService
  fullName: Innova.Data.AppSettings.ILayoutService
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Data.AppSettings.Services.LayoutService`1.UserLayout*
  commentId: Overload:Innova.Data.AppSettings.Services.LayoutService`1.UserLayout
  href: Innova.Data.AppSettings.Services.LayoutService-1.UserLayout.html#Innova_Data_AppSettings_Services_LayoutService_1_UserLayout
  name: UserLayout
  nameWithType: LayoutService<TContext>.UserLayout
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>.UserLayout
  nameWithType.vb: LayoutService(Of TContext).UserLayout
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext).UserLayout
- uid: Innova.Data.AppSettings.ILayoutService.UserLayout
  commentId: P:Innova.Data.AppSettings.ILayoutService.UserLayout
  parent: Innova.Data.AppSettings.ILayoutService
  href: Innova.Data.AppSettings.ILayoutService.UserLayout.html#Innova_Data_AppSettings_ILayoutService_UserLayout
  name: UserLayout
  nameWithType: ILayoutService.UserLayout
  fullName: Innova.Data.AppSettings.ILayoutService.UserLayout
- uid: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  commentId: T:Innova.Data.AppSettings.Services.ILayoutDataServiceBase
  parent: Innova.Data.AppSettings.Services
  href: Innova.Data.AppSettings.Services.ILayoutDataServiceBase.html
  name: ILayoutDataServiceBase
  nameWithType: ILayoutDataServiceBase
  fullName: Innova.Data.AppSettings.Services.ILayoutDataServiceBase
- uid: Innova.Data.AppSettings.Services.LayoutService`1.DefaultLayout*
  commentId: Overload:Innova.Data.AppSettings.Services.LayoutService`1.DefaultLayout
  href: Innova.Data.AppSettings.Services.LayoutService-1.DefaultLayout.html#Innova_Data_AppSettings_Services_LayoutService_1_DefaultLayout
  name: DefaultLayout
  nameWithType: LayoutService<TContext>.DefaultLayout
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>.DefaultLayout
  nameWithType.vb: LayoutService(Of TContext).DefaultLayout
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext).DefaultLayout
- uid: Innova.Data.AppSettings.ILayoutService.DefaultLayout
  commentId: P:Innova.Data.AppSettings.ILayoutService.DefaultLayout
  parent: Innova.Data.AppSettings.ILayoutService
  href: Innova.Data.AppSettings.ILayoutService.DefaultLayout.html#Innova_Data_AppSettings_ILayoutService_DefaultLayout
  name: DefaultLayout
  nameWithType: ILayoutService.DefaultLayout
  fullName: Innova.Data.AppSettings.ILayoutService.DefaultLayout
- uid: Innova.Data.AppSettings.Services.LayoutService`1
  commentId: T:Innova.Data.AppSettings.Services.LayoutService`1
  href: Innova.Data.AppSettings.Services.LayoutService-1.html
  name: LayoutService<TContext>
  nameWithType: LayoutService<TContext>
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>
  nameWithType.vb: LayoutService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext)
  name.vb: LayoutService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.LayoutService`1
    name: LayoutService
    href: Innova.Data.AppSettings.Services.LayoutService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.LayoutService`1
    name: LayoutService
    href: Innova.Data.AppSettings.Services.LayoutService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.LayoutService`1.#ctor*
  commentId: Overload:Innova.Data.AppSettings.Services.LayoutService`1.#ctor
  href: Innova.Data.AppSettings.Services.LayoutService-1.-ctor.html#Innova_Data_AppSettings_Services_LayoutService_1__ctor_Innova_Data_AppSettings_Services_UserLayoutDataService__0__Innova_Data_AppSettings_Services_DefaultLayoutDataService__0__
  name: LayoutService
  nameWithType: LayoutService<TContext>.LayoutService
  fullName: Innova.Data.AppSettings.Services.LayoutService<TContext>.LayoutService
  nameWithType.vb: LayoutService(Of TContext).New
  fullName.vb: Innova.Data.AppSettings.Services.LayoutService(Of TContext).New
  name.vb: New
- uid: Innova.Data.AppSettings.Services.UserLayoutDataService{{TContext}}
  commentId: T:Innova.Data.AppSettings.Services.UserLayoutDataService{`0}
  parent: Innova.Data.AppSettings.Services
  definition: Innova.Data.AppSettings.Services.UserLayoutDataService`1
  href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  name: UserLayoutDataService<TContext>
  nameWithType: UserLayoutDataService<TContext>
  fullName: Innova.Data.AppSettings.Services.UserLayoutDataService<TContext>
  nameWithType.vb: UserLayoutDataService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.UserLayoutDataService(Of TContext)
  name.vb: UserLayoutDataService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.UserLayoutDataService`1
    name: UserLayoutDataService
    href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.UserLayoutDataService`1
    name: UserLayoutDataService
    href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService{{TContext}}
  commentId: T:Innova.Data.AppSettings.Services.DefaultLayoutDataService{`0}
  parent: Innova.Data.AppSettings.Services
  definition: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
  href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  name: DefaultLayoutDataService<TContext>
  nameWithType: DefaultLayoutDataService<TContext>
  fullName: Innova.Data.AppSettings.Services.DefaultLayoutDataService<TContext>
  nameWithType.vb: DefaultLayoutDataService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.DefaultLayoutDataService(Of TContext)
  name.vb: DefaultLayoutDataService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
    name: DefaultLayoutDataService
    href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
    name: DefaultLayoutDataService
    href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.UserLayoutDataService`1
  commentId: T:Innova.Data.AppSettings.Services.UserLayoutDataService`1
  href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  name: UserLayoutDataService<TContext>
  nameWithType: UserLayoutDataService<TContext>
  fullName: Innova.Data.AppSettings.Services.UserLayoutDataService<TContext>
  nameWithType.vb: UserLayoutDataService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.UserLayoutDataService(Of TContext)
  name.vb: UserLayoutDataService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.UserLayoutDataService`1
    name: UserLayoutDataService
    href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.UserLayoutDataService`1
    name: UserLayoutDataService
    href: Innova.Data.AppSettings.Services.UserLayoutDataService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
- uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
  commentId: T:Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
  href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  name: DefaultLayoutDataService<TContext>
  nameWithType: DefaultLayoutDataService<TContext>
  fullName: Innova.Data.AppSettings.Services.DefaultLayoutDataService<TContext>
  nameWithType.vb: DefaultLayoutDataService(Of TContext)
  fullName.vb: Innova.Data.AppSettings.Services.DefaultLayoutDataService(Of TContext)
  name.vb: DefaultLayoutDataService(Of TContext)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
    name: DefaultLayoutDataService
    href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  - name: <
  - name: TContext
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.DefaultLayoutDataService`1
    name: DefaultLayoutDataService
    href: Innova.Data.AppSettings.Services.DefaultLayoutDataService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TContext
  - name: )
memberLayout: SeparatePages
