### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Library.Security
  commentId: N:Innova.Prism.Library.Security
  id: Security
  parent: Innova.Prism.Library
  children:
  - Innova.Prism.Library.Security.COMInvokeAttribute
  - Innova.Prism.Library.Security.COMUtils
  - Innova.Prism.Library.Security.DirectoryObjectDialog
  - Innova.Prism.Library.Security.DirectoryObjectDialogInitEventArgs
  - Innova.Prism.Library.Security.DirectoryObjectDialogOptions
  - Innova.Prism.Library.Security.DirectoryObjectDialogResult
  - Innova.Prism.Library.Security.DirectoryObjectSelection
  - Innova.Prism.Library.Security.DirectoryScope
  - Innova.Prism.Library.Security.DirectoryScopeOptions
  - Innova.Prism.Library.Security.InvokeUtils
  - Innova.Prism.Library.Security.LowLevel
  - Innova.Prism.Library.Security.MarshalUtils
  - Innova.Prism.Library.Security.MiscUtils
  - Innova.Prism.Library.Security.ReflectionUtils
  langs:
  - csharp
  - vb
  name: Innova.Prism.Library.Security
  nameWithType: Innova.Prism.Library.Security
  fullName: Innova.Prism.Library.Security
  type: Namespace
  assemblies:
  - Innova.Prism.Library
references:
- uid: Innova.Prism.Library.Security.LowLevel
  commentId: N:Innova.Prism.Library.Security.LowLevel
  href: Innova.html
  name: Innova.Prism.Library.Security.LowLevel
  nameWithType: Innova.Prism.Library.Security.LowLevel
  fullName: Innova.Prism.Library.Security.LowLevel
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Security
    name: Security
    href: Innova.Prism.Library.Security.html
  - name: .
  - uid: Innova.Prism.Library.Security.LowLevel
    name: LowLevel
    href: Innova.Prism.Library.Security.LowLevel.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Security
    name: Security
    href: Innova.Prism.Library.Security.html
  - name: .
  - uid: Innova.Prism.Library.Security.LowLevel
    name: LowLevel
    href: Innova.Prism.Library.Security.LowLevel.html
- uid: Innova.Prism.Library.Security.COMInvokeAttribute
  commentId: T:Innova.Prism.Library.Security.COMInvokeAttribute
  parent: Innova.Prism.Library.Security
  href: Innova.Prism.Library.Security.COMInvokeAttribute.html
  name: COMInvokeAttribute
  nameWithType: COMInvokeAttribute
  fullName: Innova.Prism.Library.Security.COMInvokeAttribute
- uid: Innova.Prism.Library.Security.COMUtils
  commentId: T:Innova.Prism.Library.Security.COMUtils
  href: Innova.Prism.Library.Security.COMUtils.html
  name: COMUtils
  nameWithType: COMUtils
  fullName: Innova.Prism.Library.Security.COMUtils
- uid: Innova.Prism.Library.Security.DirectoryObjectDialog
  commentId: T:Innova.Prism.Library.Security.DirectoryObjectDialog
  href: Innova.Prism.Library.Security.DirectoryObjectDialog.html
  name: DirectoryObjectDialog
  nameWithType: DirectoryObjectDialog
  fullName: Innova.Prism.Library.Security.DirectoryObjectDialog
- uid: Innova.Prism.Library.Security.DirectoryObjectDialogInitEventArgs
  commentId: T:Innova.Prism.Library.Security.DirectoryObjectDialogInitEventArgs
  href: Innova.Prism.Library.Security.DirectoryObjectDialogInitEventArgs.html
  name: DirectoryObjectDialogInitEventArgs
  nameWithType: DirectoryObjectDialogInitEventArgs
  fullName: Innova.Prism.Library.Security.DirectoryObjectDialogInitEventArgs
- uid: Innova.Prism.Library.Security.DirectoryObjectDialogOptions
  commentId: T:Innova.Prism.Library.Security.DirectoryObjectDialogOptions
  parent: Innova.Prism.Library.Security
  href: Innova.Prism.Library.Security.DirectoryObjectDialogOptions.html
  name: DirectoryObjectDialogOptions
  nameWithType: DirectoryObjectDialogOptions
  fullName: Innova.Prism.Library.Security.DirectoryObjectDialogOptions
- uid: Innova.Prism.Library.Security.DirectoryObjectDialogResult
  commentId: T:Innova.Prism.Library.Security.DirectoryObjectDialogResult
  href: Innova.Prism.Library.Security.DirectoryObjectDialogResult.html
  name: DirectoryObjectDialogResult
  nameWithType: DirectoryObjectDialogResult
  fullName: Innova.Prism.Library.Security.DirectoryObjectDialogResult
- uid: Innova.Prism.Library.Security.DirectoryObjectSelection
  commentId: T:Innova.Prism.Library.Security.DirectoryObjectSelection
  href: Innova.Prism.Library.Security.DirectoryObjectSelection.html
  name: DirectoryObjectSelection
  nameWithType: DirectoryObjectSelection
  fullName: Innova.Prism.Library.Security.DirectoryObjectSelection
- uid: Innova.Prism.Library.Security.DirectoryScope
  commentId: T:Innova.Prism.Library.Security.DirectoryScope
  parent: Innova.Prism.Library.Security
  href: Innova.Prism.Library.Security.DirectoryScope.html
  name: DirectoryScope
  nameWithType: DirectoryScope
  fullName: Innova.Prism.Library.Security.DirectoryScope
- uid: Innova.Prism.Library.Security.DirectoryScopeOptions
  commentId: T:Innova.Prism.Library.Security.DirectoryScopeOptions
  href: Innova.Prism.Library.Security.DirectoryScopeOptions.html
  name: DirectoryScopeOptions
  nameWithType: DirectoryScopeOptions
  fullName: Innova.Prism.Library.Security.DirectoryScopeOptions
- uid: Innova.Prism.Library.Security.InvokeUtils
  commentId: T:Innova.Prism.Library.Security.InvokeUtils
  href: Innova.Prism.Library.Security.InvokeUtils.html
  name: InvokeUtils
  nameWithType: InvokeUtils
  fullName: Innova.Prism.Library.Security.InvokeUtils
- uid: Innova.Prism.Library.Security.MarshalUtils
  commentId: T:Innova.Prism.Library.Security.MarshalUtils
  href: Innova.Prism.Library.Security.MarshalUtils.html
  name: MarshalUtils
  nameWithType: MarshalUtils
  fullName: Innova.Prism.Library.Security.MarshalUtils
- uid: Innova.Prism.Library.Security.MiscUtils
  commentId: T:Innova.Prism.Library.Security.MiscUtils
  href: Innova.Prism.Library.Security.MiscUtils.html
  name: MiscUtils
  nameWithType: MiscUtils
  fullName: Innova.Prism.Library.Security.MiscUtils
- uid: Innova.Prism.Library.Security.ReflectionUtils
  commentId: T:Innova.Prism.Library.Security.ReflectionUtils
  href: Innova.Prism.Library.Security.ReflectionUtils.html
  name: ReflectionUtils
  nameWithType: ReflectionUtils
  fullName: Innova.Prism.Library.Security.ReflectionUtils
- uid: Innova.Prism.Library.Security
  commentId: N:Innova.Prism.Library.Security
  href: Innova.html
  name: Innova.Prism.Library.Security
  nameWithType: Innova.Prism.Library.Security
  fullName: Innova.Prism.Library.Security
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Security
    name: Security
    href: Innova.Prism.Library.Security.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Security
    name: Security
    href: Innova.Prism.Library.Security.html
memberLayout: SeparatePages
