### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Library.Configuration.UI
  commentId: N:Innova.Prism.Library.Configuration.UI
  id: Configuration.UI
  parent: Innova.Prism.Library
  children:
  - Innova.Prism.Library.Configuration.UI.IUiConfiguration
  - Innova.Prism.Library.Configuration.UI.IVisibilityService
  - Innova.Prism.Library.Configuration.UI.UiBase
  - Innova.Prism.Library.Configuration.UI.UiConfiguration
  - Innova.Prism.Library.Configuration.UI.UiEntity
  - Innova.Prism.Library.Configuration.UI.UiField
  - Innova.Prism.Library.Configuration.UI.UiGroup
  - Innova.Prism.Library.Configuration.UI.VisibilityService
  - Innova.Prism.Library.Configuration.UI.VisibilityServiceLifecycle
  langs:
  - csharp
  - vb
  name: Innova.Prism.Library.Configuration.UI
  nameWithType: Innova.Prism.Library.Configuration.UI
  fullName: Innova.Prism.Library.Configuration.UI
  type: Namespace
  assemblies:
  - Innova.Prism.Library
references:
- uid: Innova.Prism.Library.Configuration.UI.IUiConfiguration
  commentId: T:Innova.Prism.Library.Configuration.UI.IUiConfiguration
  parent: Innova.Prism.Library.Configuration.UI
  href: Innova.Prism.Library.Configuration.UI.IUiConfiguration.html
  name: IUiConfiguration
  nameWithType: IUiConfiguration
  fullName: Innova.Prism.Library.Configuration.UI.IUiConfiguration
- uid: Innova.Prism.Library.Configuration.UI.IVisibilityService
  commentId: T:Innova.Prism.Library.Configuration.UI.IVisibilityService
  parent: Innova.Prism.Library.Configuration.UI
  href: Innova.Prism.Library.Configuration.UI.IVisibilityService.html
  name: IVisibilityService
  nameWithType: IVisibilityService
  fullName: Innova.Prism.Library.Configuration.UI.IVisibilityService
- uid: Innova.Prism.Library.Configuration.UI.UiBase
  commentId: T:Innova.Prism.Library.Configuration.UI.UiBase
  parent: Innova.Prism.Library.Configuration.UI
  href: Innova.Prism.Library.Configuration.UI.UiBase.html
  name: UiBase
  nameWithType: UiBase
  fullName: Innova.Prism.Library.Configuration.UI.UiBase
- uid: Innova.Prism.Library.Configuration.UI.UiConfiguration
  commentId: T:Innova.Prism.Library.Configuration.UI.UiConfiguration
  href: Innova.Prism.Library.Configuration.UI.UiConfiguration.html
  name: UiConfiguration
  nameWithType: UiConfiguration
  fullName: Innova.Prism.Library.Configuration.UI.UiConfiguration
- uid: Innova.Prism.Library.Configuration.UI.UiEntity
  commentId: T:Innova.Prism.Library.Configuration.UI.UiEntity
  parent: Innova.Prism.Library.Configuration.UI
  href: Innova.Prism.Library.Configuration.UI.UiEntity.html
  name: UiEntity
  nameWithType: UiEntity
  fullName: Innova.Prism.Library.Configuration.UI.UiEntity
- uid: Innova.Prism.Library.Configuration.UI.UiField
  commentId: T:Innova.Prism.Library.Configuration.UI.UiField
  parent: Innova.Prism.Library.Configuration.UI
  href: Innova.Prism.Library.Configuration.UI.UiField.html
  name: UiField
  nameWithType: UiField
  fullName: Innova.Prism.Library.Configuration.UI.UiField
- uid: Innova.Prism.Library.Configuration.UI.UiGroup
  commentId: T:Innova.Prism.Library.Configuration.UI.UiGroup
  href: Innova.Prism.Library.Configuration.UI.UiGroup.html
  name: UiGroup
  nameWithType: UiGroup
  fullName: Innova.Prism.Library.Configuration.UI.UiGroup
- uid: Innova.Prism.Library.Configuration.UI.VisibilityService
  commentId: T:Innova.Prism.Library.Configuration.UI.VisibilityService
  href: Innova.Prism.Library.Configuration.UI.VisibilityService.html
  name: VisibilityService
  nameWithType: VisibilityService
  fullName: Innova.Prism.Library.Configuration.UI.VisibilityService
- uid: Innova.Prism.Library.Configuration.UI.VisibilityServiceLifecycle
  commentId: T:Innova.Prism.Library.Configuration.UI.VisibilityServiceLifecycle
  href: Innova.Prism.Library.Configuration.UI.VisibilityServiceLifecycle.html
  name: VisibilityServiceLifecycle
  nameWithType: VisibilityServiceLifecycle
  fullName: Innova.Prism.Library.Configuration.UI.VisibilityServiceLifecycle
- uid: Innova.Prism.Library.Configuration.UI
  commentId: N:Innova.Prism.Library.Configuration.UI
  href: Innova.html
  name: Innova.Prism.Library.Configuration.UI
  nameWithType: Innova.Prism.Library.Configuration.UI
  fullName: Innova.Prism.Library.Configuration.UI
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
memberLayout: SeparatePages
