### YamlMime:ManagedReference
items:
- uid: Innova.Rest.Server.Security.ServerApplicationSecurityOptions
  commentId: T:Innova.Rest.Server.Security.ServerApplicationSecurityOptions
  id: ServerApplicationSecurityOptions
  parent: Innova.Rest.Server.Security
  children:
  - Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes
  langs:
  - csharp
  - vb
  name: ServerApplicationSecurityOptions
  nameWithType: ServerApplicationSecurityOptions
  fullName: Innova.Rest.Server.Security.ServerApplicationSecurityOptions
  type: Class
  source:
    id: ServerApplicationSecurityOptions
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Security\ServerApplicationSecurityOptions.cs
    startLine: 8
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Security
  syntax:
    content: public class ServerApplicationSecurityOptions
    content.vb: Public Class ServerApplicationSecurityOptions
  inheritance:
  - System.Object
- uid: Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes
  commentId: P:Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes
  id: CacheTimeoutInMinutes
  parent: Innova.Rest.Server.Security.ServerApplicationSecurityOptions
  langs:
  - csharp
  - vb
  name: CacheTimeoutInMinutes
  nameWithType: ServerApplicationSecurityOptions.CacheTimeoutInMinutes
  fullName: Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes
  type: Property
  source:
    id: CacheTimeoutInMinutes
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Security\ServerApplicationSecurityOptions.cs
    startLine: 10
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Security
  syntax:
    content: public int CacheTimeoutInMinutes { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property CacheTimeoutInMinutes As Integer
  overload: Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes*
references:
- uid: Innova.Rest.Server.Security
  commentId: N:Innova.Rest.Server.Security
  href: Innova.html
  name: Innova.Rest.Server.Security
  nameWithType: Innova.Rest.Server.Security
  fullName: Innova.Rest.Server.Security
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Security
    name: Security
    href: Innova.Rest.Server.Security.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Security
    name: Security
    href: Innova.Rest.Server.Security.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes*
  commentId: Overload:Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes
  href: Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes.html#Innova_Rest_Server_Security_ServerApplicationSecurityOptions_CacheTimeoutInMinutes
  name: CacheTimeoutInMinutes
  nameWithType: ServerApplicationSecurityOptions.CacheTimeoutInMinutes
  fullName: Innova.Rest.Server.Security.ServerApplicationSecurityOptions.CacheTimeoutInMinutes
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
memberLayout: SeparatePages
