### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.EmailTemplate
  commentId: T:Innova.Data.AppSettings.EmailTemplate
  id: EmailTemplate
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.EmailTemplate.Body
  - Innova.Data.AppSettings.EmailTemplate.From
  - Innova.Data.AppSettings.EmailTemplate.Subject
  - Innova.Data.AppSettings.EmailTemplate.To
  langs:
  - csharp
  - vb
  name: EmailTemplate
  nameWithType: EmailTemplate
  fullName: Innova.Data.AppSettings.EmailTemplate
  type: Class
  source:
    id: EmailTemplate
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EmailTemplate.cs
    startLine: 7
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: The EmailTemplate to be used for configure emails in appsettings.
  example: []
  syntax:
    content: >-
      [Serializable]

      public class EmailTemplate
    content.vb: >-
      <Serializable>

      Public Class EmailTemplate
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Innova.Data.AppSettings.EmailTemplate.From
  commentId: P:Innova.Data.AppSettings.EmailTemplate.From
  id: From
  parent: Innova.Data.AppSettings.EmailTemplate
  langs:
  - csharp
  - vb
  name: From
  nameWithType: EmailTemplate.From
  fullName: Innova.Data.AppSettings.EmailTemplate.From
  type: Property
  source:
    id: From
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EmailTemplate.cs
    startLine: 13
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the email sender.
  example: []
  syntax:
    content: public string From { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property From As String
  overload: Innova.Data.AppSettings.EmailTemplate.From*
- uid: Innova.Data.AppSettings.EmailTemplate.To
  commentId: P:Innova.Data.AppSettings.EmailTemplate.To
  id: To
  parent: Innova.Data.AppSettings.EmailTemplate
  langs:
  - csharp
  - vb
  name: To
  nameWithType: EmailTemplate.To
  fullName: Innova.Data.AppSettings.EmailTemplate.To
  type: Property
  source:
    id: To
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EmailTemplate.cs
    startLine: 18
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the email recipient.
  example: []
  syntax:
    content: public string To { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property [To] As String
  overload: Innova.Data.AppSettings.EmailTemplate.To*
- uid: Innova.Data.AppSettings.EmailTemplate.Subject
  commentId: P:Innova.Data.AppSettings.EmailTemplate.Subject
  id: Subject
  parent: Innova.Data.AppSettings.EmailTemplate
  langs:
  - csharp
  - vb
  name: Subject
  nameWithType: EmailTemplate.Subject
  fullName: Innova.Data.AppSettings.EmailTemplate.Subject
  type: Property
  source:
    id: Subject
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EmailTemplate.cs
    startLine: 23
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the email subject.
  example: []
  syntax:
    content: public string Subject { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Subject As String
  overload: Innova.Data.AppSettings.EmailTemplate.Subject*
- uid: Innova.Data.AppSettings.EmailTemplate.Body
  commentId: P:Innova.Data.AppSettings.EmailTemplate.Body
  id: Body
  parent: Innova.Data.AppSettings.EmailTemplate
  langs:
  - csharp
  - vb
  name: Body
  nameWithType: EmailTemplate.Body
  fullName: Innova.Data.AppSettings.EmailTemplate.Body
  type: Property
  source:
    id: Body
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EmailTemplate.cs
    startLine: 28
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the email body.
  example: []
  syntax:
    content: public string Body { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Body As String
  overload: Innova.Data.AppSettings.EmailTemplate.Body*
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.EmailTemplate.From*
  commentId: Overload:Innova.Data.AppSettings.EmailTemplate.From
  href: Innova.Data.AppSettings.EmailTemplate.From.html#Innova_Data_AppSettings_EmailTemplate_From
  name: From
  nameWithType: EmailTemplate.From
  fullName: Innova.Data.AppSettings.EmailTemplate.From
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Data.AppSettings.EmailTemplate.To*
  commentId: Overload:Innova.Data.AppSettings.EmailTemplate.To
  href: Innova.Data.AppSettings.EmailTemplate.To.html#Innova_Data_AppSettings_EmailTemplate_To
  name: To
  nameWithType: EmailTemplate.To
  fullName: Innova.Data.AppSettings.EmailTemplate.To
- uid: Innova.Data.AppSettings.EmailTemplate.Subject*
  commentId: Overload:Innova.Data.AppSettings.EmailTemplate.Subject
  href: Innova.Data.AppSettings.EmailTemplate.Subject.html#Innova_Data_AppSettings_EmailTemplate_Subject
  name: Subject
  nameWithType: EmailTemplate.Subject
  fullName: Innova.Data.AppSettings.EmailTemplate.Subject
- uid: Innova.Data.AppSettings.EmailTemplate.Body*
  commentId: Overload:Innova.Data.AppSettings.EmailTemplate.Body
  href: Innova.Data.AppSettings.EmailTemplate.Body.html#Innova_Data_AppSettings_EmailTemplate_Body
  name: Body
  nameWithType: EmailTemplate.Body
  fullName: Innova.Data.AppSettings.EmailTemplate.Body
memberLayout: SeparatePages
