### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Library.Configuration.UI.UiEntity
  commentId: T:Innova.Prism.Library.Configuration.UI.UiEntity
  id: UiEntity
  parent: Innova.Prism.Library.Configuration.UI
  children:
  - Innova.Prism.Library.Configuration.UI.UiEntity.Fields
  - Innova.Prism.Library.Configuration.UI.UiEntity.Groups
  langs:
  - csharp
  - vb
  name: UiEntity
  nameWithType: UiEntity
  fullName: Innova.Prism.Library.Configuration.UI.UiEntity
  type: Class
  source:
    id: UiEntity
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\UiEntity.cs
    startLine: 11
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Represents a UI entity.
  example: []
  syntax:
    content: 'public class UiEntity : UiBase'
    content.vb: Public Class UiEntity Inherits UiBase
  inheritance:
  - System.Object
  - Innova.Prism.Library.Configuration.UI.UiBase
  inheritedMembers:
  - Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  - Innova.Prism.Library.Configuration.UI.UiBase.Name
- uid: Innova.Prism.Library.Configuration.UI.UiEntity.Fields
  commentId: P:Innova.Prism.Library.Configuration.UI.UiEntity.Fields
  id: Fields
  parent: Innova.Prism.Library.Configuration.UI.UiEntity
  langs:
  - csharp
  - vb
  name: Fields
  nameWithType: UiEntity.Fields
  fullName: Innova.Prism.Library.Configuration.UI.UiEntity.Fields
  type: Property
  source:
    id: Fields
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\UiEntity.cs
    startLine: 16
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Gets or sets the list of UI fields.
  example: []
  syntax:
    content: public List<UiField> Fields { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Innova.Prism.Library.Configuration.UI.UiField}
    content.vb: Public Property Fields As List(Of UiField)
  overload: Innova.Prism.Library.Configuration.UI.UiEntity.Fields*
- uid: Innova.Prism.Library.Configuration.UI.UiEntity.Groups
  commentId: P:Innova.Prism.Library.Configuration.UI.UiEntity.Groups
  id: Groups
  parent: Innova.Prism.Library.Configuration.UI.UiEntity
  langs:
  - csharp
  - vb
  name: Groups
  nameWithType: UiEntity.Groups
  fullName: Innova.Prism.Library.Configuration.UI.UiEntity.Groups
  type: Property
  source:
    id: Groups
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\UiEntity.cs
    startLine: 21
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Gets or sets the list of UI groups.
  example: []
  syntax:
    content: public List<UiGroup> Groups { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Innova.Prism.Library.Configuration.UI.UiGroup}
    content.vb: Public Property Groups As List(Of UiGroup)
  overload: Innova.Prism.Library.Configuration.UI.UiEntity.Groups*
references:
- uid: Innova.Prism.Library.Configuration.UI
  commentId: N:Innova.Prism.Library.Configuration.UI
  href: Innova.html
  name: Innova.Prism.Library.Configuration.UI
  nameWithType: Innova.Prism.Library.Configuration.UI
  fullName: Innova.Prism.Library.Configuration.UI
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Innova.Prism.Library.Configuration.UI.UiBase
  commentId: T:Innova.Prism.Library.Configuration.UI.UiBase
  parent: Innova.Prism.Library.Configuration.UI
  href: Innova.Prism.Library.Configuration.UI.UiBase.html
  name: UiBase
  nameWithType: UiBase
  fullName: Innova.Prism.Library.Configuration.UI.UiBase
- uid: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  commentId: P:Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  parent: Innova.Prism.Library.Configuration.UI.UiBase
  href: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible.html#Innova_Prism_Library_Configuration_UI_UiBase_IsVisible
  name: IsVisible
  nameWithType: UiBase.IsVisible
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
- uid: Innova.Prism.Library.Configuration.UI.UiBase.Name
  commentId: P:Innova.Prism.Library.Configuration.UI.UiBase.Name
  parent: Innova.Prism.Library.Configuration.UI.UiBase
  href: Innova.Prism.Library.Configuration.UI.UiBase.Name.html#Innova_Prism_Library_Configuration_UI_UiBase_Name
  name: Name
  nameWithType: UiBase.Name
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.Name
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Prism.Library.Configuration.UI.UiEntity.Fields*
  commentId: Overload:Innova.Prism.Library.Configuration.UI.UiEntity.Fields
  href: Innova.Prism.Library.Configuration.UI.UiEntity.Fields.html#Innova_Prism_Library_Configuration_UI_UiEntity_Fields
  name: Fields
  nameWithType: UiEntity.Fields
  fullName: Innova.Prism.Library.Configuration.UI.UiEntity.Fields
- uid: System.Collections.Generic.List{Innova.Prism.Library.Configuration.UI.UiField}
  commentId: T:System.Collections.Generic.List{Innova.Prism.Library.Configuration.UI.UiField}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<UiField>
  nameWithType: List<UiField>
  fullName: System.Collections.Generic.List<Innova.Prism.Library.Configuration.UI.UiField>
  nameWithType.vb: List(Of UiField)
  fullName.vb: System.Collections.Generic.List(Of Innova.Prism.Library.Configuration.UI.UiField)
  name.vb: List(Of UiField)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Innova.Prism.Library.Configuration.UI.UiField
    name: UiField
    href: Innova.Prism.Library.Configuration.UI.UiField.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Prism.Library.Configuration.UI.UiField
    name: UiField
    href: Innova.Prism.Library.Configuration.UI.UiField.html
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Innova.Prism.Library.Configuration.UI.UiEntity.Groups*
  commentId: Overload:Innova.Prism.Library.Configuration.UI.UiEntity.Groups
  href: Innova.Prism.Library.Configuration.UI.UiEntity.Groups.html#Innova_Prism_Library_Configuration_UI_UiEntity_Groups
  name: Groups
  nameWithType: UiEntity.Groups
  fullName: Innova.Prism.Library.Configuration.UI.UiEntity.Groups
- uid: System.Collections.Generic.List{Innova.Prism.Library.Configuration.UI.UiGroup}
  commentId: T:System.Collections.Generic.List{Innova.Prism.Library.Configuration.UI.UiGroup}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<UiGroup>
  nameWithType: List<UiGroup>
  fullName: System.Collections.Generic.List<Innova.Prism.Library.Configuration.UI.UiGroup>
  nameWithType.vb: List(Of UiGroup)
  fullName.vb: System.Collections.Generic.List(Of Innova.Prism.Library.Configuration.UI.UiGroup)
  name.vb: List(Of UiGroup)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Innova.Prism.Library.Configuration.UI.UiGroup
    name: UiGroup
    href: Innova.Prism.Library.Configuration.UI.UiGroup.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Prism.Library.Configuration.UI.UiGroup
    name: UiGroup
    href: Innova.Prism.Library.Configuration.UI.UiGroup.html
  - name: )
memberLayout: SeparatePages
