### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.Services.ServiceConstants
  commentId: T:Innova.Data.AppSettings.Services.ServiceConstants
  id: ServiceConstants
  parent: Innova.Data.AppSettings.Services
  children:
  - Innova.Data.AppSettings.Services.ServiceConstants.DefaultSid
  langs:
  - csharp
  - vb
  name: ServiceConstants
  nameWithType: ServiceConstants
  fullName: Innova.Data.AppSettings.Services.ServiceConstants
  type: Class
  source:
    id: ServiceConstants
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ServiceConstants.cs
    startLine: 5
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Constants related to services.
  example: []
  syntax:
    content: public class ServiceConstants
    content.vb: Public Class ServiceConstants
  inheritance:
  - System.Object
- uid: Innova.Data.AppSettings.Services.ServiceConstants.DefaultSid
  commentId: F:Innova.Data.AppSettings.Services.ServiceConstants.DefaultSid
  id: DefaultSid
  parent: Innova.Data.AppSettings.Services.ServiceConstants
  langs:
  - csharp
  - vb
  name: DefaultSid
  nameWithType: ServiceConstants.DefaultSid
  fullName: Innova.Data.AppSettings.Services.ServiceConstants.DefaultSid
  type: Field
  source:
    id: DefaultSid
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ServiceConstants.cs
    startLine: 10
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: The default SID.
  example: []
  syntax:
    content: public const string DefaultSid = "Sid-default"
    return:
      type: System.String
    content.vb: Public Const DefaultSid As String = "Sid-default"
references:
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  href: Innova.html
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
memberLayout: SeparatePages
