### YamlMime:ManagedReference
items:
- uid: Innova.Data.IInnovaApplicationBuilderExt
  commentId: T:Innova.Data.IInnovaApplicationBuilderExt
  id: IInnovaApplicationBuilderExt
  parent: Innova.Data
  children:
  - Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  - Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String,System.String,System.String)
  langs:
  - csharp
  - vb
  name: IInnovaApplicationBuilderExt
  nameWithType: IInnovaApplicationBuilderExt
  fullName: Innova.Data.IInnovaApplicationBuilderExt
  type: Class
  source:
    id: IInnovaApplicationBuilderExt
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\IInnovaApplicationBuilderExt.cs
    startLine: 14
  assemblies:
  - Innova.Data
  namespace: Innova.Data
  summary: Extension methods for <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref> to configure SQL Server connection.
  example: []
  syntax:
    content: public static class IInnovaApplicationBuilderExt
    content.vb: Public Module IInnovaApplicationBuilderExt
  inheritance:
  - System.Object
- uid: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  commentId: M:Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  id: UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  isExtensionMethod: true
  parent: Innova.Data.IInnovaApplicationBuilderExt
  langs:
  - csharp
  - vb
  name: UseSqlServer(IInnovaApplicationBuilderBase, string)
  nameWithType: IInnovaApplicationBuilderExt.UseSqlServer(IInnovaApplicationBuilderBase, string)
  fullName: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase, string)
  type: Method
  source:
    id: UseSqlServer
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\IInnovaApplicationBuilderExt.cs
    startLine: 22
  assemblies:
  - Innova.Data
  namespace: Innova.Data
  summary: Configures the SQL Server connection with the specified connection string.
  example: []
  syntax:
    content: public static IInnovaApplicationBuilderBase UseSqlServer(this IInnovaApplicationBuilderBase applicationBuilder, string connectionString)
    parameters:
    - id: applicationBuilder
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref> instance.
    - id: connectionString
      type: System.String
      description: The SQL Server connection string.
    return:
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref> instance.
    content.vb: Public Shared Function UseSqlServer(applicationBuilder As IInnovaApplicationBuilderBase, connectionString As String) As IInnovaApplicationBuilderBase
  overload: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer*
  nameWithType.vb: IInnovaApplicationBuilderExt.UseSqlServer(IInnovaApplicationBuilderBase, String)
  fullName.vb: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase, String)
  name.vb: UseSqlServer(IInnovaApplicationBuilderBase, String)
- uid: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String,System.String,System.String)
  commentId: M:Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String,System.String,System.String)
  id: UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String,System.String,System.String)
  isExtensionMethod: true
  parent: Innova.Data.IInnovaApplicationBuilderExt
  langs:
  - csharp
  - vb
  name: UseSqlServer(IInnovaApplicationBuilderBase, string, string, string)
  nameWithType: IInnovaApplicationBuilderExt.UseSqlServer(IInnovaApplicationBuilderBase, string, string, string)
  fullName: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase, string, string, string)
  type: Method
  source:
    id: UseSqlServer
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\IInnovaApplicationBuilderExt.cs
    startLine: 37
  assemblies:
  - Innova.Data
  namespace: Innova.Data
  summary: Configures the SQL Server connection with the specified connection string, application role name, and application role password.
  example: []
  syntax:
    content: public static IInnovaApplicationBuilderBase UseSqlServer(this IInnovaApplicationBuilderBase applicationBuilder, string connectionString, string applicationRoleName, string applicationRolePassword)
    parameters:
    - id: applicationBuilder
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref> instance.
    - id: connectionString
      type: System.String
      description: The SQL Server connection string.
    - id: applicationRoleName
      type: System.String
      description: The application role name.
    - id: applicationRolePassword
      type: System.String
      description: The application role password.
    return:
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref> instance.
    content.vb: Public Shared Function UseSqlServer(applicationBuilder As IInnovaApplicationBuilderBase, connectionString As String, applicationRoleName As String, applicationRolePassword As String) As IInnovaApplicationBuilderBase
  overload: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer*
  nameWithType.vb: IInnovaApplicationBuilderExt.UseSqlServer(IInnovaApplicationBuilderBase, String, String, String)
  fullName.vb: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase, String, String, String)
  name.vb: UseSqlServer(IInnovaApplicationBuilderBase, String, String, String)
references:
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  commentId: T:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  parent: Innova.Abstractions.Builder
  href: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.html
  name: IInnovaApplicationBuilderBase
  nameWithType: IInnovaApplicationBuilderBase
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
- uid: Innova.Data
  commentId: N:Innova.Data
  href: Innova.html
  name: Innova.Data
  nameWithType: Innova.Data
  fullName: Innova.Data
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Innova.Abstractions.Builder
  commentId: N:Innova.Abstractions.Builder
  href: Innova.html
  name: Innova.Abstractions.Builder
  nameWithType: Innova.Abstractions.Builder
  fullName: Innova.Abstractions.Builder
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer*
  commentId: Overload:Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer
  href: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer.html#Innova_Data_IInnovaApplicationBuilderExt_UseSqlServer_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_System_String_
  name: UseSqlServer
  nameWithType: IInnovaApplicationBuilderExt.UseSqlServer
  fullName: Innova.Data.IInnovaApplicationBuilderExt.UseSqlServer
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
memberLayout: SeparatePages
