### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.IApplicationSettingService`1
  commentId: T:Innova.Data.AppSettings.IApplicationSettingService`1
  id: IApplicationSettingService`1
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.IApplicationSettingService`1.Get
  langs:
  - csharp
  - vb
  name: IApplicationSettingService<T>
  nameWithType: IApplicationSettingService<T>
  fullName: Innova.Data.AppSettings.IApplicationSettingService<T>
  type: Interface
  source:
    id: IApplicationSettingService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IApplicationSettingService.cs
    startLine: 9
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents an interface for retrieving application settings of type <code class="typeparamref">T</code>.
  example: []
  syntax:
    content: 'public interface IApplicationSettingService<T> : IApplicationSettingService where T : class'
    typeParameters:
    - id: T
      description: The type of the application settings.
    content.vb: Public Interface IApplicationSettingService(Of T As Class) Inherits IApplicationSettingService
  inheritedMembers:
  - Innova.Data.AppSettings.IApplicationSettingService.Save
  - Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
  - Innova.Data.AppSettings.IApplicationSettingService.LoadData
  nameWithType.vb: IApplicationSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.IApplicationSettingService(Of T)
  name.vb: IApplicationSettingService(Of T)
- uid: Innova.Data.AppSettings.IApplicationSettingService`1.Get
  commentId: M:Innova.Data.AppSettings.IApplicationSettingService`1.Get
  id: Get
  parent: Innova.Data.AppSettings.IApplicationSettingService`1
  langs:
  - csharp
  - vb
  name: Get()
  nameWithType: IApplicationSettingService<T>.Get()
  fullName: Innova.Data.AppSettings.IApplicationSettingService<T>.Get()
  type: Method
  source:
    id: Get
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IApplicationSettingService.cs
    startLine: 15
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the application settings of type <code class="typeparamref">T</code>.
  example: []
  syntax:
    content: T Get()
    return:
      type: '{T}'
      description: The application settings of type <code class="typeparamref">T</code>.
    content.vb: Function [Get]() As T
  overload: Innova.Data.AppSettings.IApplicationSettingService`1.Get*
  nameWithType.vb: IApplicationSettingService(Of T).Get()
  fullName.vb: Innova.Data.AppSettings.IApplicationSettingService(Of T).Get()
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Data.AppSettings.IApplicationSettingService.Save
  commentId: M:Innova.Data.AppSettings.IApplicationSettingService.Save
  parent: Innova.Data.AppSettings.IApplicationSettingService
  href: Innova.Data.AppSettings.IApplicationSettingService.Save.html#Innova_Data_AppSettings_IApplicationSettingService_Save
  name: Save()
  nameWithType: IApplicationSettingService.Save()
  fullName: Innova.Data.AppSettings.IApplicationSettingService.Save()
  spec.csharp:
  - uid: Innova.Data.AppSettings.IApplicationSettingService.Save
    name: Save
    href: Innova.Data.AppSettings.IApplicationSettingService.Save.html#Innova_Data_AppSettings_IApplicationSettingService_Save
  - name: (
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.IApplicationSettingService.Save
    name: Save
    href: Innova.Data.AppSettings.IApplicationSettingService.Save.html#Innova_Data_AppSettings_IApplicationSettingService_Save
  - name: (
  - name: )
- uid: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
  commentId: M:Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
  parent: Innova.Data.AppSettings.IApplicationSettingService
  href: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject.html#Innova_Data_AppSettings_IApplicationSettingService_GetSettingsAsObject
  name: GetSettingsAsObject()
  nameWithType: IApplicationSettingService.GetSettingsAsObject()
  fullName: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject()
  spec.csharp:
  - uid: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
    name: GetSettingsAsObject
    href: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject.html#Innova_Data_AppSettings_IApplicationSettingService_GetSettingsAsObject
  - name: (
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
    name: GetSettingsAsObject
    href: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject.html#Innova_Data_AppSettings_IApplicationSettingService_GetSettingsAsObject
  - name: (
  - name: )
- uid: Innova.Data.AppSettings.IApplicationSettingService.LoadData
  commentId: M:Innova.Data.AppSettings.IApplicationSettingService.LoadData
  parent: Innova.Data.AppSettings.IApplicationSettingService
  href: Innova.Data.AppSettings.IApplicationSettingService.LoadData.html#Innova_Data_AppSettings_IApplicationSettingService_LoadData
  name: LoadData()
  nameWithType: IApplicationSettingService.LoadData()
  fullName: Innova.Data.AppSettings.IApplicationSettingService.LoadData()
  spec.csharp:
  - uid: Innova.Data.AppSettings.IApplicationSettingService.LoadData
    name: LoadData
    href: Innova.Data.AppSettings.IApplicationSettingService.LoadData.html#Innova_Data_AppSettings_IApplicationSettingService_LoadData
  - name: (
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.IApplicationSettingService.LoadData
    name: LoadData
    href: Innova.Data.AppSettings.IApplicationSettingService.LoadData.html#Innova_Data_AppSettings_IApplicationSettingService_LoadData
  - name: (
  - name: )
- uid: Innova.Data.AppSettings.IApplicationSettingService
  commentId: T:Innova.Data.AppSettings.IApplicationSettingService
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.IApplicationSettingService.html
  name: IApplicationSettingService
  nameWithType: IApplicationSettingService
  fullName: Innova.Data.AppSettings.IApplicationSettingService
- uid: Innova.Data.AppSettings.IApplicationSettingService`1.Get*
  commentId: Overload:Innova.Data.AppSettings.IApplicationSettingService`1.Get
  href: Innova.Data.AppSettings.IApplicationSettingService-1.Get.html#Innova_Data_AppSettings_IApplicationSettingService_1_Get
  name: Get
  nameWithType: IApplicationSettingService<T>.Get
  fullName: Innova.Data.AppSettings.IApplicationSettingService<T>.Get
  nameWithType.vb: IApplicationSettingService(Of T).Get
  fullName.vb: Innova.Data.AppSettings.IApplicationSettingService(Of T).Get
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
memberLayout: SeparatePages
