### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.MyQueue`1
  commentId: T:Innova.Data.AppSettings.MyQueue`1
  id: MyQueue`1
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.MyQueue`1.#ctor
  - Innova.Data.AppSettings.MyQueue`1.Add(`0)
  - Innova.Data.AppSettings.MyQueue`1.List
  - Innova.Data.AppSettings.MyQueue`1.MaxCount
  - Innova.Data.AppSettings.MyQueue`1.Remove(`0)
  langs:
  - csharp
  - vb
  name: MyQueue<KeyType>
  nameWithType: MyQueue<KeyType>
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>
  type: Class
  source:
    id: MyQueue
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyQueue.cs
    startLine: 8
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents a generic queue with a maximum count.
  example: []
  syntax:
    content: public class MyQueue<KeyType>
    typeParameters:
    - id: KeyType
      description: The type of the elements in the queue.
    content.vb: Public Class MyQueue(Of KeyType)
  inheritance:
  - System.Object
  derivedClasses:
  - Innova.Data.AppSettings.MyLatestList`1
  nameWithType.vb: MyQueue(Of KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType)
  name.vb: MyQueue(Of KeyType)
- uid: Innova.Data.AppSettings.MyQueue`1.MaxCount
  commentId: P:Innova.Data.AppSettings.MyQueue`1.MaxCount
  id: MaxCount
  parent: Innova.Data.AppSettings.MyQueue`1
  langs:
  - csharp
  - vb
  name: MaxCount
  nameWithType: MyQueue<KeyType>.MaxCount
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.MaxCount
  type: Property
  source:
    id: MaxCount
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyQueue.cs
    startLine: 13
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the maximum count of the queue.
  example: []
  syntax:
    content: public int MaxCount { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxCount As Integer
  overload: Innova.Data.AppSettings.MyQueue`1.MaxCount*
  nameWithType.vb: MyQueue(Of KeyType).MaxCount
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).MaxCount
- uid: Innova.Data.AppSettings.MyQueue`1.List
  commentId: P:Innova.Data.AppSettings.MyQueue`1.List
  id: List
  parent: Innova.Data.AppSettings.MyQueue`1
  langs:
  - csharp
  - vb
  name: List
  nameWithType: MyQueue<KeyType>.List
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.List
  type: Property
  source:
    id: List
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyQueue.cs
    startLine: 18
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the list of elements in the queue.
  example: []
  syntax:
    content: public List<KeyType> List { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{{KeyType}}
    content.vb: Public Property List As List(Of KeyType)
  overload: Innova.Data.AppSettings.MyQueue`1.List*
  nameWithType.vb: MyQueue(Of KeyType).List
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).List
- uid: Innova.Data.AppSettings.MyQueue`1.Remove(`0)
  commentId: M:Innova.Data.AppSettings.MyQueue`1.Remove(`0)
  id: Remove(`0)
  parent: Innova.Data.AppSettings.MyQueue`1
  langs:
  - csharp
  - vb
  name: Remove(KeyType)
  nameWithType: MyQueue<KeyType>.Remove(KeyType)
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.Remove(KeyType)
  type: Method
  source:
    id: Remove
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyQueue.cs
    startLine: 24
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Removes the specified value from the queue.
  example: []
  syntax:
    content: public virtual void Remove(KeyType value)
    parameters:
    - id: value
      type: '{KeyType}'
      description: The value to remove.
    content.vb: Public Overridable Sub Remove(value As KeyType)
  overload: Innova.Data.AppSettings.MyQueue`1.Remove*
  nameWithType.vb: MyQueue(Of KeyType).Remove(KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).Remove(KeyType)
- uid: Innova.Data.AppSettings.MyQueue`1.Add(`0)
  commentId: M:Innova.Data.AppSettings.MyQueue`1.Add(`0)
  id: Add(`0)
  parent: Innova.Data.AppSettings.MyQueue`1
  langs:
  - csharp
  - vb
  name: Add(KeyType)
  nameWithType: MyQueue<KeyType>.Add(KeyType)
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.Add(KeyType)
  type: Method
  source:
    id: Add
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyQueue.cs
    startLine: 36
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Adds the specified value to the queue.
  example: []
  syntax:
    content: public virtual void Add(KeyType value)
    parameters:
    - id: value
      type: '{KeyType}'
      description: The value to add.
    content.vb: Public Overridable Sub Add(value As KeyType)
  overload: Innova.Data.AppSettings.MyQueue`1.Add*
  nameWithType.vb: MyQueue(Of KeyType).Add(KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).Add(KeyType)
- uid: Innova.Data.AppSettings.MyQueue`1.#ctor
  commentId: M:Innova.Data.AppSettings.MyQueue`1.#ctor
  id: '#ctor'
  parent: Innova.Data.AppSettings.MyQueue`1
  langs:
  - csharp
  - vb
  name: MyQueue()
  nameWithType: MyQueue<KeyType>.MyQueue()
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.MyQueue()
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyQueue.cs
    startLine: 44
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  syntax:
    content: public MyQueue()
    content.vb: Public Sub New()
  overload: Innova.Data.AppSettings.MyQueue`1.#ctor*
  nameWithType.vb: MyQueue(Of KeyType).New()
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).New()
  name.vb: New()
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.MyQueue`1.MaxCount*
  commentId: Overload:Innova.Data.AppSettings.MyQueue`1.MaxCount
  href: Innova.Data.AppSettings.MyQueue-1.MaxCount.html#Innova_Data_AppSettings_MyQueue_1_MaxCount
  name: MaxCount
  nameWithType: MyQueue<KeyType>.MaxCount
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.MaxCount
  nameWithType.vb: MyQueue(Of KeyType).MaxCount
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).MaxCount
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Innova.Data.AppSettings.MyQueue`1.List*
  commentId: Overload:Innova.Data.AppSettings.MyQueue`1.List
  href: Innova.Data.AppSettings.MyQueue-1.List.html#Innova_Data_AppSettings_MyQueue_1_List
  name: List
  nameWithType: MyQueue<KeyType>.List
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.List
  nameWithType.vb: MyQueue(Of KeyType).List
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).List
- uid: System.Collections.Generic.List{{KeyType}}
  commentId: T:System.Collections.Generic.List{`0}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<KeyType>
  nameWithType: List<KeyType>
  fullName: System.Collections.Generic.List<KeyType>
  nameWithType.vb: List(Of KeyType)
  fullName.vb: System.Collections.Generic.List(Of KeyType)
  name.vb: List(Of KeyType)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Innova.Data.AppSettings.MyQueue`1.Remove*
  commentId: Overload:Innova.Data.AppSettings.MyQueue`1.Remove
  href: Innova.Data.AppSettings.MyQueue-1.Remove.html#Innova_Data_AppSettings_MyQueue_1_Remove__0_
  name: Remove
  nameWithType: MyQueue<KeyType>.Remove
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.Remove
  nameWithType.vb: MyQueue(Of KeyType).Remove
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).Remove
- uid: '{KeyType}'
  commentId: '!:KeyType'
  definition: KeyType
  name: KeyType
  nameWithType: KeyType
  fullName: KeyType
- uid: KeyType
  name: KeyType
  nameWithType: KeyType
  fullName: KeyType
- uid: Innova.Data.AppSettings.MyQueue`1.Add*
  commentId: Overload:Innova.Data.AppSettings.MyQueue`1.Add
  href: Innova.Data.AppSettings.MyQueue-1.Add.html#Innova_Data_AppSettings_MyQueue_1_Add__0_
  name: Add
  nameWithType: MyQueue<KeyType>.Add
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.Add
  nameWithType.vb: MyQueue(Of KeyType).Add
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).Add
- uid: Innova.Data.AppSettings.MyQueue`1.#ctor*
  commentId: Overload:Innova.Data.AppSettings.MyQueue`1.#ctor
  href: Innova.Data.AppSettings.MyQueue-1.-ctor.html#Innova_Data_AppSettings_MyQueue_1__ctor
  name: MyQueue
  nameWithType: MyQueue<KeyType>.MyQueue
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.MyQueue
  nameWithType.vb: MyQueue(Of KeyType).New
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).New
  name.vb: New
memberLayout: SeparatePages
