### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.Interfaces
  commentId: N:Innova.Data.AppSettings.Interfaces
  id: Interfaces
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.Interfaces.IBaseSettings
  langs:
  - csharp
  - vb
  name: Innova.Data.AppSettings.Interfaces
  nameWithType: Innova.Data.AppSettings.Interfaces
  fullName: Innova.Data.AppSettings.Interfaces
  type: Namespace
  assemblies:
  - Innova.Data
references:
- uid: Innova.Data.AppSettings.Interfaces.IBaseSettings
  commentId: T:Innova.Data.AppSettings.Interfaces.IBaseSettings
  parent: Innova.Data.AppSettings.Interfaces
  href: Innova.Data.AppSettings.Interfaces.IBaseSettings.html
  name: IBaseSettings
  nameWithType: IBaseSettings
  fullName: Innova.Data.AppSettings.Interfaces.IBaseSettings
- uid: Innova.Data.AppSettings.Interfaces
  commentId: N:Innova.Data.AppSettings.Interfaces
  href: Innova.html
  name: Innova.Data.AppSettings.Interfaces
  nameWithType: Innova.Data.AppSettings.Interfaces
  fullName: Innova.Data.AppSettings.Interfaces
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Interfaces
    name: Interfaces
    href: Innova.Data.AppSettings.Interfaces.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Interfaces
    name: Interfaces
    href: Innova.Data.AppSettings.Interfaces.html
memberLayout: SeparatePages
