### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.UserSettingsTypeConfiguration
  commentId: T:Innova.Data.AppSettings.UserSettingsTypeConfiguration
  id: UserSettingsTypeConfiguration
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
  langs:
  - csharp
  - vb
  name: UserSettingsTypeConfiguration
  nameWithType: UserSettingsTypeConfiguration
  fullName: Innova.Data.AppSettings.UserSettingsTypeConfiguration
  type: Class
  source:
    id: UserSettingsTypeConfiguration
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\UserSettingsTypeConfiguration.cs
    startLine: 8
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents the configuration for the UserSettings entity in the database.
  example: []
  syntax:
    content: 'public class UserSettingsTypeConfiguration : IEntityTypeConfiguration<UserSettings>'
    content.vb: Public Class UserSettingsTypeConfiguration Implements IEntityTypeConfiguration(Of UserSettings)
  inheritance:
  - System.Object
  implements:
  - Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}
- uid: Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
  commentId: M:Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
  id: Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
  parent: Innova.Data.AppSettings.UserSettingsTypeConfiguration
  langs:
  - csharp
  - vb
  name: Configure(EntityTypeBuilder<UserSettings>)
  nameWithType: UserSettingsTypeConfiguration.Configure(EntityTypeBuilder<UserSettings>)
  fullName: Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.AppSettings.UserSettings>)
  type: Method
  source:
    id: Configure
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\UserSettingsTypeConfiguration.cs
    startLine: 14
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Configures the UserSettings entity.
  example: []
  syntax:
    content: public void Configure(EntityTypeBuilder<UserSettings> builder)
    parameters:
    - id: builder
      type: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings}
      description: The entity type builder used to configure the entity.
    content.vb: Public Sub Configure(builder As EntityTypeBuilder(Of UserSettings))
  overload: Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure*
  implements:
  - Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
  nameWithType.vb: UserSettingsTypeConfiguration.Configure(EntityTypeBuilder(Of UserSettings))
  fullName.vb: Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.AppSettings.UserSettings))
  name.vb: Configure(EntityTypeBuilder(Of UserSettings))
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}
  commentId: T:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}
  parent: Microsoft.EntityFrameworkCore
  definition: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  name: IEntityTypeConfiguration<UserSettings>
  nameWithType: IEntityTypeConfiguration<UserSettings>
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Innova.Data.AppSettings.UserSettings>
  nameWithType.vb: IEntityTypeConfiguration(Of UserSettings)
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of Innova.Data.AppSettings.UserSettings)
  name.vb: IEntityTypeConfiguration(Of UserSettings)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: <
  - uid: Innova.Data.AppSettings.UserSettings
    name: UserSettings
    href: Innova.Data.AppSettings.UserSettings.html
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.AppSettings.UserSettings
    name: UserSettings
    href: Innova.Data.AppSettings.UserSettings.html
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  commentId: T:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  name: IEntityTypeConfiguration<TEntity>
  nameWithType: IEntityTypeConfiguration<TEntity>
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<TEntity>
  nameWithType.vb: IEntityTypeConfiguration(Of TEntity)
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of TEntity)
  name.vb: IEntityTypeConfiguration(Of TEntity)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
- uid: Microsoft.EntityFrameworkCore
  commentId: N:Microsoft.EntityFrameworkCore
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.EntityFrameworkCore
  nameWithType: Microsoft.EntityFrameworkCore
  fullName: Microsoft.EntityFrameworkCore
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
- uid: Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure*
  commentId: Overload:Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure
  href: Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure.html#Innova_Data_AppSettings_UserSettingsTypeConfiguration_Configure_Microsoft_EntityFrameworkCore_Metadata_Builders_EntityTypeBuilder_Innova_Data_AppSettings_UserSettings__
  name: Configure
  nameWithType: UserSettingsTypeConfiguration.Configure
  fullName: Innova.Data.AppSettings.UserSettingsTypeConfiguration.Configure
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
  commentId: M:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
  parent: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}
  definition: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  name: Configure(EntityTypeBuilder<UserSettings>)
  nameWithType: IEntityTypeConfiguration<UserSettings>.Configure(EntityTypeBuilder<UserSettings>)
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Innova.Data.AppSettings.UserSettings>.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.AppSettings.UserSettings>)
  nameWithType.vb: IEntityTypeConfiguration(Of UserSettings).Configure(EntityTypeBuilder(Of UserSettings))
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of Innova.Data.AppSettings.UserSettings).Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.AppSettings.UserSettings))
  name.vb: Configure(EntityTypeBuilder(Of UserSettings))
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - uid: Innova.Data.AppSettings.UserSettings
    name: UserSettings
    href: Innova.Data.AppSettings.UserSettings.html
  - name: '>'
  - name: )
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.AppSettings.UserSettings}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.AppSettings.UserSettings
    name: UserSettings
    href: Innova.Data.AppSettings.UserSettings.html
  - name: )
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings}
  commentId: T:Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.AppSettings.UserSettings}
  parent: Microsoft.EntityFrameworkCore.Metadata.Builders
  definition: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  name: EntityTypeBuilder<UserSettings>
  nameWithType: EntityTypeBuilder<UserSettings>
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.AppSettings.UserSettings>
  nameWithType.vb: EntityTypeBuilder(Of UserSettings)
  fullName.vb: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.AppSettings.UserSettings)
  name.vb: EntityTypeBuilder(Of UserSettings)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - uid: Innova.Data.AppSettings.UserSettings
    name: UserSettings
    href: Innova.Data.AppSettings.UserSettings.html
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.AppSettings.UserSettings
    name: UserSettings
    href: Innova.Data.AppSettings.UserSettings.html
  - name: )
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  commentId: M:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  name: Configure(EntityTypeBuilder<TEntity>)
  nameWithType: IEntityTypeConfiguration<TEntity>.Configure(EntityTypeBuilder<TEntity>)
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<TEntity>.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>)
  nameWithType.vb: IEntityTypeConfiguration(Of TEntity).Configure(EntityTypeBuilder(Of TEntity))
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of TEntity).Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity))
  name.vb: Configure(EntityTypeBuilder(Of TEntity))
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - name: TEntity
  - name: '>'
  - name: )
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  commentId: T:Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  name: EntityTypeBuilder<TEntity>
  nameWithType: EntityTypeBuilder<TEntity>
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>
  nameWithType.vb: EntityTypeBuilder(Of TEntity)
  fullName.vb: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity)
  name.vb: EntityTypeBuilder(Of TEntity)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders
  commentId: N:Microsoft.EntityFrameworkCore.Metadata.Builders
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.EntityFrameworkCore.Metadata.Builders
  nameWithType: Microsoft.EntityFrameworkCore.Metadata.Builders
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata
    name: Metadata
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders
    name: Builders
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata
    name: Metadata
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders
    name: Builders
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders
memberLayout: SeparatePages
