### YamlMime:ManagedReference
items:
- uid: Innova.Rest.Server.Security.IApplicationSecurityProvider`1
  commentId: T:Innova.Rest.Server.Security.IApplicationSecurityProvider`1
  id: IApplicationSecurityProvider`1
  parent: Innova.Rest.Server.Security
  children:
  - Innova.Rest.Server.Security.IApplicationSecurityProvider`1.ClearUserCache(System.String)
  - Innova.Rest.Server.Security.IApplicationSecurityProvider`1.GetCurrentUserApplicationSecurity
  langs:
  - csharp
  - vb
  name: IApplicationSecurityProvider<T>
  nameWithType: IApplicationSecurityProvider<T>
  fullName: Innova.Rest.Server.Security.IApplicationSecurityProvider<T>
  type: Interface
  source:
    id: IApplicationSecurityProvider
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Security\IApplicationSecurityProvider.cs
    startLine: 2
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Security
  syntax:
    content: 'public interface IApplicationSecurityProvider<T> where T : class'
    typeParameters:
    - id: T
    content.vb: Public Interface IApplicationSecurityProvider(Of T As Class)
  nameWithType.vb: IApplicationSecurityProvider(Of T)
  fullName.vb: Innova.Rest.Server.Security.IApplicationSecurityProvider(Of T)
  name.vb: IApplicationSecurityProvider(Of T)
- uid: Innova.Rest.Server.Security.IApplicationSecurityProvider`1.ClearUserCache(System.String)
  commentId: M:Innova.Rest.Server.Security.IApplicationSecurityProvider`1.ClearUserCache(System.String)
  id: ClearUserCache(System.String)
  parent: Innova.Rest.Server.Security.IApplicationSecurityProvider`1
  langs:
  - csharp
  - vb
  name: ClearUserCache(string)
  nameWithType: IApplicationSecurityProvider<T>.ClearUserCache(string)
  fullName: Innova.Rest.Server.Security.IApplicationSecurityProvider<T>.ClearUserCache(string)
  type: Method
  source:
    id: ClearUserCache
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Security\IApplicationSecurityProvider.cs
    startLine: 4
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Security
  syntax:
    content: void ClearUserCache(string userId)
    parameters:
    - id: userId
      type: System.String
    content.vb: Sub ClearUserCache(userId As String)
  overload: Innova.Rest.Server.Security.IApplicationSecurityProvider`1.ClearUserCache*
  nameWithType.vb: IApplicationSecurityProvider(Of T).ClearUserCache(String)
  fullName.vb: Innova.Rest.Server.Security.IApplicationSecurityProvider(Of T).ClearUserCache(String)
  name.vb: ClearUserCache(String)
- uid: Innova.Rest.Server.Security.IApplicationSecurityProvider`1.GetCurrentUserApplicationSecurity
  commentId: M:Innova.Rest.Server.Security.IApplicationSecurityProvider`1.GetCurrentUserApplicationSecurity
  id: GetCurrentUserApplicationSecurity
  parent: Innova.Rest.Server.Security.IApplicationSecurityProvider`1
  langs:
  - csharp
  - vb
  name: GetCurrentUserApplicationSecurity()
  nameWithType: IApplicationSecurityProvider<T>.GetCurrentUserApplicationSecurity()
  fullName: Innova.Rest.Server.Security.IApplicationSecurityProvider<T>.GetCurrentUserApplicationSecurity()
  type: Method
  source:
    id: GetCurrentUserApplicationSecurity
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Security\IApplicationSecurityProvider.cs
    startLine: 5
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Security
  syntax:
    content: T GetCurrentUserApplicationSecurity()
    return:
      type: '{T}'
    content.vb: Function GetCurrentUserApplicationSecurity() As T
  overload: Innova.Rest.Server.Security.IApplicationSecurityProvider`1.GetCurrentUserApplicationSecurity*
  nameWithType.vb: IApplicationSecurityProvider(Of T).GetCurrentUserApplicationSecurity()
  fullName.vb: Innova.Rest.Server.Security.IApplicationSecurityProvider(Of T).GetCurrentUserApplicationSecurity()
references:
- uid: Innova.Rest.Server.Security
  commentId: N:Innova.Rest.Server.Security
  href: Innova.html
  name: Innova.Rest.Server.Security
  nameWithType: Innova.Rest.Server.Security
  fullName: Innova.Rest.Server.Security
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Security
    name: Security
    href: Innova.Rest.Server.Security.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Security
    name: Security
    href: Innova.Rest.Server.Security.html
- uid: Innova.Rest.Server.Security.IApplicationSecurityProvider`1.ClearUserCache*
  commentId: Overload:Innova.Rest.Server.Security.IApplicationSecurityProvider`1.ClearUserCache
  href: Innova.Rest.Server.Security.IApplicationSecurityProvider-1.ClearUserCache.html#Innova_Rest_Server_Security_IApplicationSecurityProvider_1_ClearUserCache_System_String_
  name: ClearUserCache
  nameWithType: IApplicationSecurityProvider<T>.ClearUserCache
  fullName: Innova.Rest.Server.Security.IApplicationSecurityProvider<T>.ClearUserCache
  nameWithType.vb: IApplicationSecurityProvider(Of T).ClearUserCache
  fullName.vb: Innova.Rest.Server.Security.IApplicationSecurityProvider(Of T).ClearUserCache
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Rest.Server.Security.IApplicationSecurityProvider`1.GetCurrentUserApplicationSecurity*
  commentId: Overload:Innova.Rest.Server.Security.IApplicationSecurityProvider`1.GetCurrentUserApplicationSecurity
  href: Innova.Rest.Server.Security.IApplicationSecurityProvider-1.GetCurrentUserApplicationSecurity.html#Innova_Rest_Server_Security_IApplicationSecurityProvider_1_GetCurrentUserApplicationSecurity
  name: GetCurrentUserApplicationSecurity
  nameWithType: IApplicationSecurityProvider<T>.GetCurrentUserApplicationSecurity
  fullName: Innova.Rest.Server.Security.IApplicationSecurityProvider<T>.GetCurrentUserApplicationSecurity
  nameWithType.vb: IApplicationSecurityProvider(Of T).GetCurrentUserApplicationSecurity
  fullName.vb: Innova.Rest.Server.Security.IApplicationSecurityProvider(Of T).GetCurrentUserApplicationSecurity
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
memberLayout: SeparatePages
