### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Infrastructure.Logging.ApplicationEventIds
  commentId: T:Innova.Prism.Infrastructure.Logging.ApplicationEventIds
  id: ApplicationEventIds
  parent: Innova.Prism.Infrastructure.Logging
  children:
  - Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Application
  - Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Menu
  - Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Search
  - Innova.Prism.Infrastructure.Logging.ApplicationEventIds.View
  langs:
  - csharp
  - vb
  name: ApplicationEventIds
  nameWithType: ApplicationEventIds
  fullName: Innova.Prism.Infrastructure.Logging.ApplicationEventIds
  type: Class
  source:
    id: ApplicationEventIds
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Logging\ApplicationEventIds.cs
    startLine: 7
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Logging
  summary: Contains the event IDs for application logging.
  example: []
  syntax:
    content: public class ApplicationEventIds
    content.vb: Public Class ApplicationEventIds
  inheritance:
  - System.Object
- uid: Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Application
  commentId: F:Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Application
  id: Application
  parent: Innova.Prism.Infrastructure.Logging.ApplicationEventIds
  langs:
  - csharp
  - vb
  name: Application
  nameWithType: ApplicationEventIds.Application
  fullName: Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Application
  type: Field
  source:
    id: Application
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Logging\ApplicationEventIds.cs
    startLine: 12
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Logging
  summary: Gets the event ID for application events.
  example: []
  syntax:
    content: public static EventId Application
    return:
      type: Microsoft.Extensions.Logging.EventId
    content.vb: Public Shared Application As EventId
- uid: Innova.Prism.Infrastructure.Logging.ApplicationEventIds.View
  commentId: F:Innova.Prism.Infrastructure.Logging.ApplicationEventIds.View
  id: View
  parent: Innova.Prism.Infrastructure.Logging.ApplicationEventIds
  langs:
  - csharp
  - vb
  name: View
  nameWithType: ApplicationEventIds.View
  fullName: Innova.Prism.Infrastructure.Logging.ApplicationEventIds.View
  type: Field
  source:
    id: View
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Logging\ApplicationEventIds.cs
    startLine: 17
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Logging
  summary: Gets the event ID for view events.
  example: []
  syntax:
    content: public static EventId View
    return:
      type: Microsoft.Extensions.Logging.EventId
    content.vb: Public Shared View As EventId
- uid: Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Search
  commentId: F:Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Search
  id: Search
  parent: Innova.Prism.Infrastructure.Logging.ApplicationEventIds
  langs:
  - csharp
  - vb
  name: Search
  nameWithType: ApplicationEventIds.Search
  fullName: Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Search
  type: Field
  source:
    id: Search
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Logging\ApplicationEventIds.cs
    startLine: 22
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Logging
  summary: Gets the event ID for search events.
  example: []
  syntax:
    content: public static EventId Search
    return:
      type: Microsoft.Extensions.Logging.EventId
    content.vb: Public Shared Search As EventId
- uid: Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Menu
  commentId: F:Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Menu
  id: Menu
  parent: Innova.Prism.Infrastructure.Logging.ApplicationEventIds
  langs:
  - csharp
  - vb
  name: Menu
  nameWithType: ApplicationEventIds.Menu
  fullName: Innova.Prism.Infrastructure.Logging.ApplicationEventIds.Menu
  type: Field
  source:
    id: Menu
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Logging\ApplicationEventIds.cs
    startLine: 27
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Logging
  summary: Gets the event ID for menu events.
  example: []
  syntax:
    content: public static EventId Menu
    return:
      type: Microsoft.Extensions.Logging.EventId
    content.vb: Public Shared Menu As EventId
references:
- uid: Innova.Prism.Infrastructure.Logging
  commentId: N:Innova.Prism.Infrastructure.Logging
  href: Innova.html
  name: Innova.Prism.Infrastructure.Logging
  nameWithType: Innova.Prism.Infrastructure.Logging
  fullName: Innova.Prism.Infrastructure.Logging
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Infrastructure
    name: Infrastructure
    href: Innova.Prism.Infrastructure.html
  - name: .
  - uid: Innova.Prism.Infrastructure.Logging
    name: Logging
    href: Innova.Prism.Infrastructure.Logging.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Infrastructure
    name: Infrastructure
    href: Innova.Prism.Infrastructure.html
  - name: .
  - uid: Innova.Prism.Infrastructure.Logging
    name: Logging
    href: Innova.Prism.Infrastructure.Logging.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.Extensions.Logging.EventId
  commentId: T:Microsoft.Extensions.Logging.EventId
  parent: Microsoft.Extensions.Logging
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging.eventid
  name: EventId
  nameWithType: EventId
  fullName: Microsoft.Extensions.Logging.EventId
- uid: Microsoft.Extensions.Logging
  commentId: N:Microsoft.Extensions.Logging
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.Extensions.Logging
  nameWithType: Microsoft.Extensions.Logging
  fullName: Microsoft.Extensions.Logging
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Logging
    name: Logging
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.Logging
    name: Logging
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.logging
memberLayout: SeparatePages
