### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Library.Configuration.UI.UiBase
  commentId: T:Innova.Prism.Library.Configuration.UI.UiBase
  id: UiBase
  parent: Innova.Prism.Library.Configuration.UI
  children:
  - Innova.Prism.Library.Configuration.UI.UiBase.#ctor
  - Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  - Innova.Prism.Library.Configuration.UI.UiBase.Name
  langs:
  - csharp
  - vb
  name: UiBase
  nameWithType: UiBase
  fullName: Innova.Prism.Library.Configuration.UI.UiBase
  type: Class
  source:
    id: UiBase
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\UiBase.cs
    startLine: 11
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Represents the base class for UI elements.
  example: []
  syntax:
    content: public class UiBase
    content.vb: Public Class UiBase
  inheritance:
  - System.Object
  derivedClasses:
  - Innova.Prism.Library.Configuration.UI.UiEntity
  - Innova.Prism.Library.Configuration.UI.UiField
  - Innova.Prism.Library.Configuration.UI.UiGroup
- uid: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  commentId: P:Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  id: IsVisible
  parent: Innova.Prism.Library.Configuration.UI.UiBase
  langs:
  - csharp
  - vb
  name: IsVisible
  nameWithType: UiBase.IsVisible
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  type: Property
  source:
    id: IsVisible
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\UiBase.cs
    startLine: 16
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Gets or sets a value indicating whether the UI element is visible.
  example: []
  syntax:
    content: public bool IsVisible { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsVisible As Boolean
  overload: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible*
- uid: Innova.Prism.Library.Configuration.UI.UiBase.Name
  commentId: P:Innova.Prism.Library.Configuration.UI.UiBase.Name
  id: Name
  parent: Innova.Prism.Library.Configuration.UI.UiBase
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: UiBase.Name
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.Name
  type: Property
  source:
    id: Name
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\UiBase.cs
    startLine: 21
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Gets or sets the name of the UI element.
  example: []
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: Innova.Prism.Library.Configuration.UI.UiBase.Name*
- uid: Innova.Prism.Library.Configuration.UI.UiBase.#ctor
  commentId: M:Innova.Prism.Library.Configuration.UI.UiBase.#ctor
  id: '#ctor'
  parent: Innova.Prism.Library.Configuration.UI.UiBase
  langs:
  - csharp
  - vb
  name: UiBase()
  nameWithType: UiBase.UiBase()
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.UiBase()
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\UiBase.cs
    startLine: 26
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Initializes a new instance of the <xref href="Innova.Prism.Library.Configuration.UI.UiBase" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public UiBase()
    content.vb: Public Sub New()
  overload: Innova.Prism.Library.Configuration.UI.UiBase.#ctor*
  nameWithType.vb: UiBase.New()
  fullName.vb: Innova.Prism.Library.Configuration.UI.UiBase.New()
  name.vb: New()
references:
- uid: Innova.Prism.Library.Configuration.UI
  commentId: N:Innova.Prism.Library.Configuration.UI
  href: Innova.html
  name: Innova.Prism.Library.Configuration.UI
  nameWithType: Innova.Prism.Library.Configuration.UI
  fullName: Innova.Prism.Library.Configuration.UI
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible*
  commentId: Overload:Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  href: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible.html#Innova_Prism_Library_Configuration_UI_UiBase_IsVisible
  name: IsVisible
  nameWithType: UiBase.IsVisible
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Innova.Prism.Library.Configuration.UI.UiBase.Name*
  commentId: Overload:Innova.Prism.Library.Configuration.UI.UiBase.Name
  href: Innova.Prism.Library.Configuration.UI.UiBase.Name.html#Innova_Prism_Library_Configuration_UI_UiBase_Name
  name: Name
  nameWithType: UiBase.Name
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Prism.Library.Configuration.UI.UiBase
  commentId: T:Innova.Prism.Library.Configuration.UI.UiBase
  parent: Innova.Prism.Library.Configuration.UI
  href: Innova.Prism.Library.Configuration.UI.UiBase.html
  name: UiBase
  nameWithType: UiBase
  fullName: Innova.Prism.Library.Configuration.UI.UiBase
- uid: Innova.Prism.Library.Configuration.UI.UiBase.#ctor*
  commentId: Overload:Innova.Prism.Library.Configuration.UI.UiBase.#ctor
  href: Innova.Prism.Library.Configuration.UI.UiBase.-ctor.html#Innova_Prism_Library_Configuration_UI_UiBase__ctor
  name: UiBase
  nameWithType: UiBase.UiBase
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.UiBase
  nameWithType.vb: UiBase.New
  fullName.vb: Innova.Prism.Library.Configuration.UI.UiBase.New
  name.vb: New
memberLayout: SeparatePages
