### YamlMime:ManagedReference
items:
- uid: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
  commentId: T:Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
  id: IServiceCollectionExtensionsRestServer
  parent: Innova.Rest.Server.Settings
  children:
  - Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService``2(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  - Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService``2(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  langs:
  - csharp
  - vb
  name: IServiceCollectionExtensionsRestServer
  nameWithType: IServiceCollectionExtensionsRestServer
  fullName: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
  type: Class
  source:
    id: IServiceCollectionExtensionsRestServer
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Settings\IServiceCollectionExtensionsRestServer.cs
    startLine: 7
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Settings
  syntax:
    content: public static class IServiceCollectionExtensionsRestServer
    content.vb: Public Module IServiceCollectionExtensionsRestServer
  inheritance:
  - System.Object
- uid: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService``2(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  commentId: M:Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService``2(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  id: AddServerUserSettingsService``2(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  isExtensionMethod: true
  parent: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
  langs:
  - csharp
  - vb
  name: AddServerUserSettingsService<TUserSetting, TSettingService>(IServiceCollection)
  nameWithType: IServiceCollectionExtensionsRestServer.AddServerUserSettingsService<TUserSetting, TSettingService>(IServiceCollection)
  fullName: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService<TUserSetting, TSettingService>(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  type: Method
  source:
    id: AddServerUserSettingsService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Settings\IServiceCollectionExtensionsRestServer.cs
    startLine: 9
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Settings
  syntax:
    content: 'public static IServiceCollection AddServerUserSettingsService<TUserSetting, TSettingService>(this IServiceCollection services) where TUserSetting : class, new() where TSettingService : class, ISettingEntityService'
    parameters:
    - id: services
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    typeParameters:
    - id: TUserSetting
    - id: TSettingService
    return:
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    content.vb: Public Shared Function AddServerUserSettingsService(Of TUserSetting As {Class, New}, TSettingService As {Class, ISettingEntityService})(services As IServiceCollection) As IServiceCollection
  overload: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService*
  nameWithType.vb: IServiceCollectionExtensionsRestServer.AddServerUserSettingsService(Of TUserSetting, TSettingService)(IServiceCollection)
  fullName.vb: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService(Of TUserSetting, TSettingService)(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  name.vb: AddServerUserSettingsService(Of TUserSetting, TSettingService)(IServiceCollection)
- uid: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService``2(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  commentId: M:Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService``2(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  id: AddServerAppSettingsService``2(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  isExtensionMethod: true
  parent: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
  langs:
  - csharp
  - vb
  name: AddServerAppSettingsService<TAppSetting, TSettingService>(IServiceCollection)
  nameWithType: IServiceCollectionExtensionsRestServer.AddServerAppSettingsService<TAppSetting, TSettingService>(IServiceCollection)
  fullName: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService<TAppSetting, TSettingService>(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  type: Method
  source:
    id: AddServerAppSettingsService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Rest\Innova.Rest.Server\Settings\IServiceCollectionExtensionsRestServer.cs
    startLine: 25
  assemblies:
  - Innova.Rest.Server
  namespace: Innova.Rest.Server.Settings
  syntax:
    content: 'public static IServiceCollection AddServerAppSettingsService<TAppSetting, TSettingService>(this IServiceCollection services) where TAppSetting : class, new() where TSettingService : class, ISettingEntityService'
    parameters:
    - id: services
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    typeParameters:
    - id: TAppSetting
    - id: TSettingService
    return:
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    content.vb: Public Shared Function AddServerAppSettingsService(Of TAppSetting As {Class, New}, TSettingService As {Class, ISettingEntityService})(services As IServiceCollection) As IServiceCollection
  overload: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService*
  nameWithType.vb: IServiceCollectionExtensionsRestServer.AddServerAppSettingsService(Of TAppSetting, TSettingService)(IServiceCollection)
  fullName.vb: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService(Of TAppSetting, TSettingService)(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  name.vb: AddServerAppSettingsService(Of TAppSetting, TSettingService)(IServiceCollection)
references:
- uid: Innova.Rest.Server.Settings
  commentId: N:Innova.Rest.Server.Settings
  href: Innova.html
  name: Innova.Rest.Server.Settings
  nameWithType: Innova.Rest.Server.Settings
  fullName: Innova.Rest.Server.Settings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Settings
    name: Settings
    href: Innova.Rest.Server.Settings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Settings
    name: Settings
    href: Innova.Rest.Server.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService*
  commentId: Overload:Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService
  href: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService.html#Innova_Rest_Server_Settings_IServiceCollectionExtensionsRestServer_AddServerUserSettingsService__2_Microsoft_Extensions_DependencyInjection_IServiceCollection_
  name: AddServerUserSettingsService
  nameWithType: IServiceCollectionExtensionsRestServer.AddServerUserSettingsService
  fullName: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerUserSettingsService
- uid: Microsoft.Extensions.DependencyInjection.IServiceCollection
  commentId: T:Microsoft.Extensions.DependencyInjection.IServiceCollection
  parent: Microsoft.Extensions.DependencyInjection
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.iservicecollection
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: Microsoft.Extensions.DependencyInjection.IServiceCollection
- uid: Microsoft.Extensions.DependencyInjection
  commentId: N:Microsoft.Extensions.DependencyInjection
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.Extensions.DependencyInjection
  nameWithType: Microsoft.Extensions.DependencyInjection
  fullName: Microsoft.Extensions.DependencyInjection
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.DependencyInjection
    name: DependencyInjection
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions
  - name: .
  - uid: Microsoft.Extensions.DependencyInjection
    name: DependencyInjection
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection
- uid: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService*
  commentId: Overload:Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService
  href: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService.html#Innova_Rest_Server_Settings_IServiceCollectionExtensionsRestServer_AddServerAppSettingsService__2_Microsoft_Extensions_DependencyInjection_IServiceCollection_
  name: AddServerAppSettingsService
  nameWithType: IServiceCollectionExtensionsRestServer.AddServerAppSettingsService
  fullName: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.AddServerAppSettingsService
memberLayout: SeparatePages
