### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Library.IInnovaApplicationBuilderExt
  commentId: T:Innova.Prism.Library.IInnovaApplicationBuilderExt
  id: IInnovaApplicationBuilderExt
  parent: Innova.Prism.Library
  children:
  - Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  langs:
  - csharp
  - vb
  name: IInnovaApplicationBuilderExt
  nameWithType: IInnovaApplicationBuilderExt
  fullName: Innova.Prism.Library.IInnovaApplicationBuilderExt
  type: Class
  source:
    id: IInnovaApplicationBuilderExt
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\IInnovaApplicationBuilderExt.cs
    startLine: 10
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library
  summary: Extension methods for <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static class IInnovaApplicationBuilderExt
    content.vb: Public Module IInnovaApplicationBuilderExt
  inheritance:
  - System.Object
- uid: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  commentId: M:Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  id: AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  isExtensionMethod: true
  parent: Innova.Prism.Library.IInnovaApplicationBuilderExt
  langs:
  - csharp
  - vb
  name: AddMainWindow<TView, TViewModel>(IInnovaApplicationBuilderBase)
  nameWithType: IInnovaApplicationBuilderExt.AddMainWindow<TView, TViewModel>(IInnovaApplicationBuilderBase)
  fullName: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow<TView, TViewModel>(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  type: Method
  source:
    id: AddMainWindow
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\IInnovaApplicationBuilderExt.cs
    startLine: 19
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library
  summary: Adds the main window of the application to the <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: 'public static IInnovaApplicationBuilderBase AddMainWindow<TView, TViewModel>(this IInnovaApplicationBuilderBase innovaApplicationBuilder) where TView : Window'
    parameters:
    - id: innovaApplicationBuilder
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The instance of <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref> to which the main window is added.
    typeParameters:
    - id: TView
      description: The type of the view that inherits from <xref href="System.Windows.Window" data-throw-if-not-resolved="false"></xref>.
    - id: TViewModel
      description: The type of the view model.
    return:
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The instance of <xref href="Innova.Abstractions.Builder.IInnovaApplicationBuilderBase" data-throw-if-not-resolved="false"></xref> with the main window added.
    content.vb: Public Shared Function AddMainWindow(Of TView As Window, TViewModel)(innovaApplicationBuilder As IInnovaApplicationBuilderBase) As IInnovaApplicationBuilderBase
  overload: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow*
  nameWithType.vb: IInnovaApplicationBuilderExt.AddMainWindow(Of TView, TViewModel)(IInnovaApplicationBuilderBase)
  fullName.vb: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow(Of TView, TViewModel)(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  name.vb: AddMainWindow(Of TView, TViewModel)(IInnovaApplicationBuilderBase)
references:
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  commentId: T:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  parent: Innova.Abstractions.Builder
  href: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.html
  name: IInnovaApplicationBuilderBase
  nameWithType: IInnovaApplicationBuilderBase
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
- uid: Innova.Prism.Library
  commentId: N:Innova.Prism.Library
  href: Innova.html
  name: Innova.Prism.Library
  nameWithType: Innova.Prism.Library
  fullName: Innova.Prism.Library
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Innova.Abstractions.Builder
  commentId: N:Innova.Abstractions.Builder
  href: Innova.html
  name: Innova.Abstractions.Builder
  nameWithType: Innova.Abstractions.Builder
  fullName: Innova.Abstractions.Builder
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Windows.Window
  commentId: T:System.Windows.Window
  parent: System.Windows
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.windows.window
  name: Window
  nameWithType: Window
  fullName: System.Windows.Window
- uid: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow*
  commentId: Overload:Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow
  href: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow.html#Innova_Prism_Library_IInnovaApplicationBuilderExt_AddMainWindow__2_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_
  name: AddMainWindow
  nameWithType: IInnovaApplicationBuilderExt.AddMainWindow
  fullName: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow
- uid: System.Windows
  commentId: N:System.Windows
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Windows
  nameWithType: System.Windows
  fullName: System.Windows
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
memberLayout: SeparatePages
