### YamlMime:ManagedReference
items:
- uid: Innova.Data.Security.ApplicationRole
  commentId: T:Innova.Data.Security.ApplicationRole
  id: ApplicationRole
  parent: Innova.Data.Security
  children:
  - Innova.Data.Security.ApplicationRole.#ctor(System.Guid,System.String)
  - Innova.Data.Security.ApplicationRole.RoleGuid
  - Innova.Data.Security.ApplicationRole.RoleName
  langs:
  - csharp
  - vb
  name: ApplicationRole
  nameWithType: ApplicationRole
  fullName: Innova.Data.Security.ApplicationRole
  type: Class
  source:
    id: ApplicationRole
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Security\Role.cs
    startLine: 11
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Security
  summary: Represents an application role.
  example: []
  syntax:
    content: public class ApplicationRole
    content.vb: Public Class ApplicationRole
  inheritance:
  - System.Object
- uid: Innova.Data.Security.ApplicationRole.RoleGuid
  commentId: P:Innova.Data.Security.ApplicationRole.RoleGuid
  id: RoleGuid
  parent: Innova.Data.Security.ApplicationRole
  langs:
  - csharp
  - vb
  name: RoleGuid
  nameWithType: ApplicationRole.RoleGuid
  fullName: Innova.Data.Security.ApplicationRole.RoleGuid
  type: Property
  source:
    id: RoleGuid
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Security\Role.cs
    startLine: 16
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Security
  summary: Gets or sets the unique identifier of the role.
  example: []
  syntax:
    content: public Guid RoleGuid { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property RoleGuid As Guid
  overload: Innova.Data.Security.ApplicationRole.RoleGuid*
- uid: Innova.Data.Security.ApplicationRole.RoleName
  commentId: P:Innova.Data.Security.ApplicationRole.RoleName
  id: RoleName
  parent: Innova.Data.Security.ApplicationRole
  langs:
  - csharp
  - vb
  name: RoleName
  nameWithType: ApplicationRole.RoleName
  fullName: Innova.Data.Security.ApplicationRole.RoleName
  type: Property
  source:
    id: RoleName
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Security\Role.cs
    startLine: 21
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Security
  summary: Gets or sets the name of the role.
  example: []
  syntax:
    content: public string RoleName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property RoleName As String
  overload: Innova.Data.Security.ApplicationRole.RoleName*
- uid: Innova.Data.Security.ApplicationRole.#ctor(System.Guid,System.String)
  commentId: M:Innova.Data.Security.ApplicationRole.#ctor(System.Guid,System.String)
  id: '#ctor(System.Guid,System.String)'
  parent: Innova.Data.Security.ApplicationRole
  langs:
  - csharp
  - vb
  name: ApplicationRole(Guid, string)
  nameWithType: ApplicationRole.ApplicationRole(Guid, string)
  fullName: Innova.Data.Security.ApplicationRole.ApplicationRole(System.Guid, string)
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Security\Role.cs
    startLine: 28
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Security
  summary: Initializes a new instance of the <xref href="Innova.Data.Security.ApplicationRole" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public ApplicationRole(Guid roleGuid, string roleName)
    parameters:
    - id: roleGuid
      type: System.Guid
      description: The unique identifier of the role.
    - id: roleName
      type: System.String
      description: The name of the role.
    content.vb: Public Sub New(roleGuid As Guid, roleName As String)
  overload: Innova.Data.Security.ApplicationRole.#ctor*
  nameWithType.vb: ApplicationRole.New(Guid, String)
  fullName.vb: Innova.Data.Security.ApplicationRole.New(System.Guid, String)
  name.vb: New(Guid, String)
references:
- uid: Innova.Data.Security
  commentId: N:Innova.Data.Security
  href: Innova.html
  name: Innova.Data.Security
  nameWithType: Innova.Data.Security
  fullName: Innova.Data.Security
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Security
    name: Security
    href: Innova.Data.Security.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Security
    name: Security
    href: Innova.Data.Security.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.Security.ApplicationRole.RoleGuid*
  commentId: Overload:Innova.Data.Security.ApplicationRole.RoleGuid
  href: Innova.Data.Security.ApplicationRole.RoleGuid.html#Innova_Data_Security_ApplicationRole_RoleGuid
  name: RoleGuid
  nameWithType: ApplicationRole.RoleGuid
  fullName: Innova.Data.Security.ApplicationRole.RoleGuid
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: Innova.Data.Security.ApplicationRole.RoleName*
  commentId: Overload:Innova.Data.Security.ApplicationRole.RoleName
  href: Innova.Data.Security.ApplicationRole.RoleName.html#Innova_Data_Security_ApplicationRole_RoleName
  name: RoleName
  nameWithType: ApplicationRole.RoleName
  fullName: Innova.Data.Security.ApplicationRole.RoleName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Data.Security.ApplicationRole
  commentId: T:Innova.Data.Security.ApplicationRole
  href: Innova.Data.Security.ApplicationRole.html
  name: ApplicationRole
  nameWithType: ApplicationRole
  fullName: Innova.Data.Security.ApplicationRole
- uid: Innova.Data.Security.ApplicationRole.#ctor*
  commentId: Overload:Innova.Data.Security.ApplicationRole.#ctor
  href: Innova.Data.Security.ApplicationRole.-ctor.html#Innova_Data_Security_ApplicationRole__ctor_System_Guid_System_String_
  name: ApplicationRole
  nameWithType: ApplicationRole.ApplicationRole
  fullName: Innova.Data.Security.ApplicationRole.ApplicationRole
  nameWithType.vb: ApplicationRole.New
  fullName.vb: Innova.Data.Security.ApplicationRole.New
  name.vb: New
memberLayout: SeparatePages
