### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew
  commentId: T:Innova.Data.AppSettings.ViewLayoutSettingNew
  id: ViewLayoutSettingNew
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.ViewLayoutSettingNew.#ctor
  - Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(System.String)
  - Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(System.String,System.String)
  - Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout(System.String)
  - Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout(System.String,System.String,System.String)
  - Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts
  langs:
  - csharp
  - vb
  name: ViewLayoutSettingNew
  nameWithType: ViewLayoutSettingNew
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew
  type: Class
  source:
    id: ViewLayoutSettingNew
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayoutSettingNew.cs
    startLine: 8
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents the settings for view layouts.
  example: []
  syntax:
    content: public class ViewLayoutSettingNew
    content.vb: Public Class ViewLayoutSettingNew
  inheritance:
  - System.Object
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts
  commentId: P:Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts
  id: ViewLayouts
  parent: Innova.Data.AppSettings.ViewLayoutSettingNew
  langs:
  - csharp
  - vb
  name: ViewLayouts
  nameWithType: ViewLayoutSettingNew.ViewLayouts
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts
  type: Property
  source:
    id: ViewLayouts
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayoutSettingNew.cs
    startLine: 15
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the list of view layouts.
  example: []
  syntax:
    content: public List<ViewLayout> ViewLayouts { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Innova.Data.AppSettings.ViewLayout}
    content.vb: Public Property ViewLayouts As List(Of ViewLayout)
  overload: Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts*
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.#ctor
  commentId: M:Innova.Data.AppSettings.ViewLayoutSettingNew.#ctor
  id: '#ctor'
  parent: Innova.Data.AppSettings.ViewLayoutSettingNew
  langs:
  - csharp
  - vb
  name: ViewLayoutSettingNew()
  nameWithType: ViewLayoutSettingNew.ViewLayoutSettingNew()
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayoutSettingNew()
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayoutSettingNew.cs
    startLine: 20
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Initializes a new instance of the <xref href="Innova.Data.AppSettings.ViewLayoutSettingNew" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public ViewLayoutSettingNew()
    content.vb: Public Sub New()
  overload: Innova.Data.AppSettings.ViewLayoutSettingNew.#ctor*
  nameWithType.vb: ViewLayoutSettingNew.New()
  fullName.vb: Innova.Data.AppSettings.ViewLayoutSettingNew.New()
  name.vb: New()
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout(System.String)
  commentId: M:Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout(System.String)
  id: GetViewLayout(System.String)
  parent: Innova.Data.AppSettings.ViewLayoutSettingNew
  langs:
  - csharp
  - vb
  name: GetViewLayout(string)
  nameWithType: ViewLayoutSettingNew.GetViewLayout(string)
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout(string)
  type: Method
  source:
    id: GetViewLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayoutSettingNew.cs
    startLine: 30
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the view layout with the specified view name.
  example: []
  syntax:
    content: public ViewLayout GetViewLayout(string viewname)
    parameters:
    - id: viewname
      type: System.String
      description: The name of the view.
    return:
      type: Innova.Data.AppSettings.ViewLayout
      description: The view layout.
    content.vb: Public Function GetViewLayout(viewname As String) As ViewLayout
  overload: Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout*
  nameWithType.vb: ViewLayoutSettingNew.GetViewLayout(String)
  fullName.vb: Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout(String)
  name.vb: GetViewLayout(String)
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout(System.String,System.String,System.String)
  commentId: M:Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout(System.String,System.String,System.String)
  id: SaveLayout(System.String,System.String,System.String)
  parent: Innova.Data.AppSettings.ViewLayoutSettingNew
  langs:
  - csharp
  - vb
  name: SaveLayout(string, string, string)
  nameWithType: ViewLayoutSettingNew.SaveLayout(string, string, string)
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout(string, string, string)
  type: Method
  source:
    id: SaveLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayoutSettingNew.cs
    startLine: 46
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Saves the layout for the specified view.
  example: []
  syntax:
    content: public void SaveLayout(string viewname, string layoutname, string layout)
    parameters:
    - id: viewname
      type: System.String
      description: The name of the view.
    - id: layoutname
      type: System.String
      description: The name of the layout.
    - id: layout
      type: System.String
      description: The layout string.
    content.vb: Public Sub SaveLayout(viewname As String, layoutname As String, layout As String)
  overload: Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout*
  nameWithType.vb: ViewLayoutSettingNew.SaveLayout(String, String, String)
  fullName.vb: Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout(String, String, String)
  name.vb: SaveLayout(String, String, String)
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(System.String,System.String)
  commentId: M:Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(System.String,System.String)
  id: DeleteLayout(System.String,System.String)
  parent: Innova.Data.AppSettings.ViewLayoutSettingNew
  langs:
  - csharp
  - vb
  name: DeleteLayout(string, string)
  nameWithType: ViewLayoutSettingNew.DeleteLayout(string, string)
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(string, string)
  type: Method
  source:
    id: DeleteLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayoutSettingNew.cs
    startLine: 75
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Deletes the layout for the specified view and layout name.
  example: []
  syntax:
    content: public void DeleteLayout(string viewname, string layoutname)
    parameters:
    - id: viewname
      type: System.String
      description: The name of the view.
    - id: layoutname
      type: System.String
      description: The name of the layout.
    content.vb: Public Sub DeleteLayout(viewname As String, layoutname As String)
  overload: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout*
  nameWithType.vb: ViewLayoutSettingNew.DeleteLayout(String, String)
  fullName.vb: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(String, String)
  name.vb: DeleteLayout(String, String)
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(System.String)
  commentId: M:Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(System.String)
  id: DeleteLayout(System.String)
  parent: Innova.Data.AppSettings.ViewLayoutSettingNew
  langs:
  - csharp
  - vb
  name: DeleteLayout(string)
  nameWithType: ViewLayoutSettingNew.DeleteLayout(string)
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(string)
  type: Method
  source:
    id: DeleteLayout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\ViewLayoutSettingNew.cs
    startLine: 97
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Deletes all layouts for the specified view.
  example: []
  syntax:
    content: public void DeleteLayout(string viewname)
    parameters:
    - id: viewname
      type: System.String
      description: The name of the view.
    content.vb: Public Sub DeleteLayout(viewname As String)
  overload: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout*
  nameWithType.vb: ViewLayoutSettingNew.DeleteLayout(String)
  fullName.vb: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout(String)
  name.vb: DeleteLayout(String)
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts*
  commentId: Overload:Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts
  href: Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts.html#Innova_Data_AppSettings_ViewLayoutSettingNew_ViewLayouts
  name: ViewLayouts
  nameWithType: ViewLayoutSettingNew.ViewLayouts
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayouts
- uid: System.Collections.Generic.List{Innova.Data.AppSettings.ViewLayout}
  commentId: T:System.Collections.Generic.List{Innova.Data.AppSettings.ViewLayout}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<ViewLayout>
  nameWithType: List<ViewLayout>
  fullName: System.Collections.Generic.List<Innova.Data.AppSettings.ViewLayout>
  nameWithType.vb: List(Of ViewLayout)
  fullName.vb: System.Collections.Generic.List(Of Innova.Data.AppSettings.ViewLayout)
  name.vb: List(Of ViewLayout)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Innova.Data.AppSettings.ViewLayout
    name: ViewLayout
    href: Innova.Data.AppSettings.ViewLayout.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.AppSettings.ViewLayout
    name: ViewLayout
    href: Innova.Data.AppSettings.ViewLayout.html
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew
  commentId: T:Innova.Data.AppSettings.ViewLayoutSettingNew
  href: Innova.Data.AppSettings.ViewLayoutSettingNew.html
  name: ViewLayoutSettingNew
  nameWithType: ViewLayoutSettingNew
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.#ctor*
  commentId: Overload:Innova.Data.AppSettings.ViewLayoutSettingNew.#ctor
  href: Innova.Data.AppSettings.ViewLayoutSettingNew.-ctor.html#Innova_Data_AppSettings_ViewLayoutSettingNew__ctor
  name: ViewLayoutSettingNew
  nameWithType: ViewLayoutSettingNew.ViewLayoutSettingNew
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.ViewLayoutSettingNew
  nameWithType.vb: ViewLayoutSettingNew.New
  fullName.vb: Innova.Data.AppSettings.ViewLayoutSettingNew.New
  name.vb: New
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout*
  commentId: Overload:Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout
  href: Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout.html#Innova_Data_AppSettings_ViewLayoutSettingNew_GetViewLayout_System_String_
  name: GetViewLayout
  nameWithType: ViewLayoutSettingNew.GetViewLayout
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.GetViewLayout
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Data.AppSettings.ViewLayout
  commentId: T:Innova.Data.AppSettings.ViewLayout
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.ViewLayout.html
  name: ViewLayout
  nameWithType: ViewLayout
  fullName: Innova.Data.AppSettings.ViewLayout
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout*
  commentId: Overload:Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout
  href: Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout.html#Innova_Data_AppSettings_ViewLayoutSettingNew_SaveLayout_System_String_System_String_System_String_
  name: SaveLayout
  nameWithType: ViewLayoutSettingNew.SaveLayout
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.SaveLayout
- uid: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout*
  commentId: Overload:Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout
  href: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout.html#Innova_Data_AppSettings_ViewLayoutSettingNew_DeleteLayout_System_String_System_String_
  name: DeleteLayout
  nameWithType: ViewLayoutSettingNew.DeleteLayout
  fullName: Innova.Data.AppSettings.ViewLayoutSettingNew.DeleteLayout
memberLayout: SeparatePages
