### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Telerik.Controls.FilterSettingState
  commentId: T:Innova.Prism.Telerik.Controls.FilterSettingState
  id: FilterSettingState
  parent: Innova.Prism.Telerik.Controls
  children:
  - Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName
  - Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator
  - Innova.Prism.Telerik.Controls.FilterSettingState.Filter1
  - Innova.Prism.Telerik.Controls.FilterSettingState.Filter2
  - Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues
  langs:
  - csharp
  - vb
  name: FilterSettingState
  nameWithType: FilterSettingState
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState
  type: Class
  source:
    id: FilterSettingState
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Telerik\Controls\FilterSettingState.cs
    startLine: 5
  assemblies:
  - Innova.Prism.Telerik
  namespace: Innova.Prism.Telerik.Controls
  syntax:
    content: public class FilterSettingState
    content.vb: Public Class FilterSettingState
  inheritance:
  - System.Object
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName
  commentId: P:Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName
  id: ColumnUniqueName
  parent: Innova.Prism.Telerik.Controls.FilterSettingState
  langs:
  - csharp
  - vb
  name: ColumnUniqueName
  nameWithType: FilterSettingState.ColumnUniqueName
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName
  type: Property
  source:
    id: ColumnUniqueName
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Telerik\Controls\FilterSettingState.cs
    startLine: 7
  assemblies:
  - Innova.Prism.Telerik
  namespace: Innova.Prism.Telerik.Controls
  syntax:
    content: public string ColumnUniqueName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ColumnUniqueName As String
  overload: Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName*
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues
  commentId: P:Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues
  id: SelectedDistinctValues
  parent: Innova.Prism.Telerik.Controls.FilterSettingState
  langs:
  - csharp
  - vb
  name: SelectedDistinctValues
  nameWithType: FilterSettingState.SelectedDistinctValues
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues
  type: Property
  source:
    id: SelectedDistinctValues
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Telerik\Controls\FilterSettingState.cs
    startLine: 10
  assemblies:
  - Innova.Prism.Telerik
  namespace: Innova.Prism.Telerik.Controls
  syntax:
    content: public List<object> SelectedDistinctValues { get; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.Object}
    content.vb: Public ReadOnly Property SelectedDistinctValues As List(Of Object)
  overload: Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues*
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.Filter1
  commentId: P:Innova.Prism.Telerik.Controls.FilterSettingState.Filter1
  id: Filter1
  parent: Innova.Prism.Telerik.Controls.FilterSettingState
  langs:
  - csharp
  - vb
  name: Filter1
  nameWithType: FilterSettingState.Filter1
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.Filter1
  type: Property
  source:
    id: Filter1
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Telerik\Controls\FilterSettingState.cs
    startLine: 23
  assemblies:
  - Innova.Prism.Telerik
  namespace: Innova.Prism.Telerik.Controls
  syntax:
    content: public FilterDescriptorState Filter1 { get; set; }
    parameters: []
    return:
      type: Innova.Prism.Telerik.Controls.FilterDescriptorState
    content.vb: Public Property Filter1 As FilterDescriptorState
  overload: Innova.Prism.Telerik.Controls.FilterSettingState.Filter1*
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator
  commentId: P:Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator
  id: FieldFilterLogicalOperator
  parent: Innova.Prism.Telerik.Controls.FilterSettingState
  langs:
  - csharp
  - vb
  name: FieldFilterLogicalOperator
  nameWithType: FilterSettingState.FieldFilterLogicalOperator
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator
  type: Property
  source:
    id: FieldFilterLogicalOperator
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Telerik\Controls\FilterSettingState.cs
    startLine: 24
  assemblies:
  - Innova.Prism.Telerik
  namespace: Innova.Prism.Telerik.Controls
  syntax:
    content: public FilterCompositionLogicalOperator FieldFilterLogicalOperator { get; set; }
    parameters: []
    return:
      type: Telerik.Windows.Data.FilterCompositionLogicalOperator
    content.vb: Public Property FieldFilterLogicalOperator As FilterCompositionLogicalOperator
  overload: Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator*
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.Filter2
  commentId: P:Innova.Prism.Telerik.Controls.FilterSettingState.Filter2
  id: Filter2
  parent: Innova.Prism.Telerik.Controls.FilterSettingState
  langs:
  - csharp
  - vb
  name: Filter2
  nameWithType: FilterSettingState.Filter2
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.Filter2
  type: Property
  source:
    id: Filter2
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Telerik\Controls\FilterSettingState.cs
    startLine: 25
  assemblies:
  - Innova.Prism.Telerik
  namespace: Innova.Prism.Telerik.Controls
  syntax:
    content: public FilterDescriptorState Filter2 { get; set; }
    parameters: []
    return:
      type: Innova.Prism.Telerik.Controls.FilterDescriptorState
    content.vb: Public Property Filter2 As FilterDescriptorState
  overload: Innova.Prism.Telerik.Controls.FilterSettingState.Filter2*
references:
- uid: Innova.Prism.Telerik.Controls
  commentId: N:Innova.Prism.Telerik.Controls
  href: Innova.html
  name: Innova.Prism.Telerik.Controls
  nameWithType: Innova.Prism.Telerik.Controls
  fullName: Innova.Prism.Telerik.Controls
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Telerik
    name: Telerik
    href: Innova.Prism.Telerik.html
  - name: .
  - uid: Innova.Prism.Telerik.Controls
    name: Controls
    href: Innova.Prism.Telerik.Controls.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Telerik
    name: Telerik
    href: Innova.Prism.Telerik.html
  - name: .
  - uid: Innova.Prism.Telerik.Controls
    name: Controls
    href: Innova.Prism.Telerik.Controls.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName*
  commentId: Overload:Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName
  href: Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName.html#Innova_Prism_Telerik_Controls_FilterSettingState_ColumnUniqueName
  name: ColumnUniqueName
  nameWithType: FilterSettingState.ColumnUniqueName
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.ColumnUniqueName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues*
  commentId: Overload:Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues
  href: Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues.html#Innova_Prism_Telerik_Controls_FilterSettingState_SelectedDistinctValues
  name: SelectedDistinctValues
  nameWithType: FilterSettingState.SelectedDistinctValues
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.SelectedDistinctValues
- uid: System.Collections.Generic.List{System.Object}
  commentId: T:System.Collections.Generic.List{System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<object>
  nameWithType: List<object>
  fullName: System.Collections.Generic.List<object>
  nameWithType.vb: List(Of Object)
  fullName.vb: System.Collections.Generic.List(Of Object)
  name.vb: List(Of Object)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: System.Object
    name: object
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.Filter1*
  commentId: Overload:Innova.Prism.Telerik.Controls.FilterSettingState.Filter1
  href: Innova.Prism.Telerik.Controls.FilterSettingState.Filter1.html#Innova_Prism_Telerik_Controls_FilterSettingState_Filter1
  name: Filter1
  nameWithType: FilterSettingState.Filter1
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.Filter1
- uid: Innova.Prism.Telerik.Controls.FilterDescriptorState
  commentId: T:Innova.Prism.Telerik.Controls.FilterDescriptorState
  parent: Innova.Prism.Telerik.Controls
  href: Innova.Prism.Telerik.Controls.FilterDescriptorState.html
  name: FilterDescriptorState
  nameWithType: FilterDescriptorState
  fullName: Innova.Prism.Telerik.Controls.FilterDescriptorState
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator*
  commentId: Overload:Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator
  href: Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator.html#Innova_Prism_Telerik_Controls_FilterSettingState_FieldFilterLogicalOperator
  name: FieldFilterLogicalOperator
  nameWithType: FilterSettingState.FieldFilterLogicalOperator
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.FieldFilterLogicalOperator
- uid: Telerik.Windows.Data.FilterCompositionLogicalOperator
  commentId: T:Telerik.Windows.Data.FilterCompositionLogicalOperator
  parent: Telerik.Windows.Data
  isExternal: true
  name: FilterCompositionLogicalOperator
  nameWithType: FilterCompositionLogicalOperator
  fullName: Telerik.Windows.Data.FilterCompositionLogicalOperator
- uid: Telerik.Windows.Data
  commentId: N:Telerik.Windows.Data
  isExternal: true
  name: Telerik.Windows.Data
  nameWithType: Telerik.Windows.Data
  fullName: Telerik.Windows.Data
  spec.csharp:
  - uid: Telerik
    name: Telerik
    isExternal: true
  - name: .
  - uid: Telerik.Windows
    name: Windows
    isExternal: true
  - name: .
  - uid: Telerik.Windows.Data
    name: Data
    isExternal: true
  spec.vb:
  - uid: Telerik
    name: Telerik
    isExternal: true
  - name: .
  - uid: Telerik.Windows
    name: Windows
    isExternal: true
  - name: .
  - uid: Telerik.Windows.Data
    name: Data
    isExternal: true
- uid: Innova.Prism.Telerik.Controls.FilterSettingState.Filter2*
  commentId: Overload:Innova.Prism.Telerik.Controls.FilterSettingState.Filter2
  href: Innova.Prism.Telerik.Controls.FilterSettingState.Filter2.html#Innova_Prism_Telerik_Controls_FilterSettingState_Filter2
  name: Filter2
  nameWithType: FilterSettingState.Filter2
  fullName: Innova.Prism.Telerik.Controls.FilterSettingState.Filter2
memberLayout: SeparatePages
