### YamlMime:ManagedReference
items:
- uid: Innova.Data.Security
  commentId: N:Innova.Data.Security
  id: Security
  parent: Innova.Data
  children:
  - Innova.Data.Security.ApplicationRole
  - Innova.Data.Security.Builder
  - Innova.Data.Security.CurrentUser
  - Innova.Data.Security.EntitySecurity`1
  - Innova.Data.Security.ICurrentUser
  - Innova.Data.Security.IEntitySecurityExtensions
  - Innova.Data.Security.IEntitySecurity`1
  - Innova.Data.Security.IUserProvider
  - Innova.Data.Security.Operation
  - Innova.Data.Security.SecurityException
  - Innova.Data.Security.UserProvider`1
  langs:
  - csharp
  - vb
  name: Innova.Data.Security
  nameWithType: Innova.Data.Security
  fullName: Innova.Data.Security
  type: Namespace
  assemblies:
  - Innova.Data
references:
- uid: Innova.Data.Security.Builder
  commentId: N:Innova.Data.Security.Builder
  href: Innova.html
  name: Innova.Data.Security.Builder
  nameWithType: Innova.Data.Security.Builder
  fullName: Innova.Data.Security.Builder
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Security
    name: Security
    href: Innova.Data.Security.html
  - name: .
  - uid: Innova.Data.Security.Builder
    name: Builder
    href: Innova.Data.Security.Builder.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Security
    name: Security
    href: Innova.Data.Security.html
  - name: .
  - uid: Innova.Data.Security.Builder
    name: Builder
    href: Innova.Data.Security.Builder.html
- uid: Innova.Data.Security.ApplicationRole
  commentId: T:Innova.Data.Security.ApplicationRole
  href: Innova.Data.Security.ApplicationRole.html
  name: ApplicationRole
  nameWithType: ApplicationRole
  fullName: Innova.Data.Security.ApplicationRole
- uid: Innova.Data.Security.CurrentUser
  commentId: T:Innova.Data.Security.CurrentUser
  href: Innova.Data.Security.CurrentUser.html
  name: CurrentUser
  nameWithType: CurrentUser
  fullName: Innova.Data.Security.CurrentUser
- uid: Innova.Data.Security.EntitySecurity`1
  commentId: T:Innova.Data.Security.EntitySecurity`1
  href: Innova.Data.Security.EntitySecurity-1.html
  name: EntitySecurity<T>
  nameWithType: EntitySecurity<T>
  fullName: Innova.Data.Security.EntitySecurity<T>
  nameWithType.vb: EntitySecurity(Of T)
  fullName.vb: Innova.Data.Security.EntitySecurity(Of T)
  name.vb: EntitySecurity(Of T)
  spec.csharp:
  - uid: Innova.Data.Security.EntitySecurity`1
    name: EntitySecurity
    href: Innova.Data.Security.EntitySecurity-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.Security.EntitySecurity`1
    name: EntitySecurity
    href: Innova.Data.Security.EntitySecurity-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.Security.ICurrentUser
  commentId: T:Innova.Data.Security.ICurrentUser
  parent: Innova.Data.Security
  href: Innova.Data.Security.ICurrentUser.html
  name: ICurrentUser
  nameWithType: ICurrentUser
  fullName: Innova.Data.Security.ICurrentUser
- uid: Innova.Data.Security.IEntitySecurityExtensions
  commentId: T:Innova.Data.Security.IEntitySecurityExtensions
  parent: Innova.Data.Security
  href: Innova.Data.Security.IEntitySecurityExtensions.html
  name: IEntitySecurityExtensions
  nameWithType: IEntitySecurityExtensions
  fullName: Innova.Data.Security.IEntitySecurityExtensions
- uid: Innova.Data.Security.IEntitySecurity`1
  commentId: T:Innova.Data.Security.IEntitySecurity`1
  href: Innova.Data.Security.IEntitySecurity-1.html
  name: IEntitySecurity<T>
  nameWithType: IEntitySecurity<T>
  fullName: Innova.Data.Security.IEntitySecurity<T>
  nameWithType.vb: IEntitySecurity(Of T)
  fullName.vb: Innova.Data.Security.IEntitySecurity(Of T)
  name.vb: IEntitySecurity(Of T)
  spec.csharp:
  - uid: Innova.Data.Security.IEntitySecurity`1
    name: IEntitySecurity
    href: Innova.Data.Security.IEntitySecurity-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.Security.IEntitySecurity`1
    name: IEntitySecurity
    href: Innova.Data.Security.IEntitySecurity-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.Security.IUserProvider
  commentId: T:Innova.Data.Security.IUserProvider
  parent: Innova.Data.Security
  href: Innova.Data.Security.IUserProvider.html
  name: IUserProvider
  nameWithType: IUserProvider
  fullName: Innova.Data.Security.IUserProvider
- uid: Innova.Data.Security.Operation
  commentId: T:Innova.Data.Security.Operation
  parent: Innova.Data.Security
  href: Innova.Data.Security.Operation.html
  name: Operation
  nameWithType: Operation
  fullName: Innova.Data.Security.Operation
- uid: Innova.Data.Security.SecurityException
  commentId: T:Innova.Data.Security.SecurityException
  href: Innova.Data.Security.SecurityException.html
  name: SecurityException
  nameWithType: SecurityException
  fullName: Innova.Data.Security.SecurityException
- uid: Innova.Data.Security.UserProvider`1
  commentId: T:Innova.Data.Security.UserProvider`1
  href: Innova.Data.Security.UserProvider-1.html
  name: UserProvider<TUser>
  nameWithType: UserProvider<TUser>
  fullName: Innova.Data.Security.UserProvider<TUser>
  nameWithType.vb: UserProvider(Of TUser)
  fullName.vb: Innova.Data.Security.UserProvider(Of TUser)
  name.vb: UserProvider(Of TUser)
  spec.csharp:
  - uid: Innova.Data.Security.UserProvider`1
    name: UserProvider
    href: Innova.Data.Security.UserProvider-1.html
  - name: <
  - name: TUser
  - name: '>'
  spec.vb:
  - uid: Innova.Data.Security.UserProvider`1
    name: UserProvider
    href: Innova.Data.Security.UserProvider-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TUser
  - name: )
- uid: Innova.Data.Security
  commentId: N:Innova.Data.Security
  href: Innova.html
  name: Innova.Data.Security
  nameWithType: Innova.Data.Security
  fullName: Innova.Data.Security
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Security
    name: Security
    href: Innova.Data.Security.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Security
    name: Security
    href: Innova.Data.Security.html
memberLayout: SeparatePages
