### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.MyLatestList`1
  commentId: T:Innova.Data.AppSettings.MyLatestList`1
  id: MyLatestList`1
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.MyLatestList`1.Add(`0)
  langs:
  - csharp
  - vb
  name: MyLatestList<KeyType>
  nameWithType: MyLatestList<KeyType>
  fullName: Innova.Data.AppSettings.MyLatestList<KeyType>
  type: Class
  source:
    id: MyLatestList
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyLatestList.cs
    startLine: 8
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents a generic list that keeps track of the latest items added, similar to a queue.
  example: []
  syntax:
    content: 'public class MyLatestList<KeyType> : MyQueue<KeyType>'
    typeParameters:
    - id: KeyType
      description: The type of the elements in the list.
    content.vb: Public Class MyLatestList(Of KeyType) Inherits MyQueue(Of KeyType)
  inheritance:
  - System.Object
  - Innova.Data.AppSettings.MyQueue{{KeyType}}
  inheritedMembers:
  - Innova.Data.AppSettings.MyQueue{{KeyType}}.MaxCount
  - Innova.Data.AppSettings.MyQueue{{KeyType}}.List
  - Innova.Data.AppSettings.MyQueue{{KeyType}}.Remove({KeyType})
  nameWithType.vb: MyLatestList(Of KeyType)
  fullName.vb: Innova.Data.AppSettings.MyLatestList(Of KeyType)
  name.vb: MyLatestList(Of KeyType)
- uid: Innova.Data.AppSettings.MyLatestList`1.Add(`0)
  commentId: M:Innova.Data.AppSettings.MyLatestList`1.Add(`0)
  id: Add(`0)
  parent: Innova.Data.AppSettings.MyLatestList`1
  langs:
  - csharp
  - vb
  name: Add(KeyType)
  nameWithType: MyLatestList<KeyType>.Add(KeyType)
  fullName: Innova.Data.AppSettings.MyLatestList<KeyType>.Add(KeyType)
  type: Method
  source:
    id: Add
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\MyLatestList.cs
    startLine: 14
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Adds the specified value to the list.
  example: []
  syntax:
    content: public override void Add(KeyType value)
    parameters:
    - id: value
      type: '{KeyType}'
      description: The value to add.
    content.vb: Public Overrides Sub Add(value As KeyType)
  overridden: Innova.Data.AppSettings.MyQueue{{KeyType}}.Add({KeyType})
  overload: Innova.Data.AppSettings.MyLatestList`1.Add*
  nameWithType.vb: MyLatestList(Of KeyType).Add(KeyType)
  fullName.vb: Innova.Data.AppSettings.MyLatestList(Of KeyType).Add(KeyType)
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Innova.Data.AppSettings.MyQueue{{KeyType}}
  commentId: T:Innova.Data.AppSettings.MyQueue{`0}
  parent: Innova.Data.AppSettings
  definition: Innova.Data.AppSettings.MyQueue`1
  href: Innova.Data.AppSettings.MyQueue-1.html
  name: MyQueue<KeyType>
  nameWithType: MyQueue<KeyType>
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>
  nameWithType.vb: MyQueue(Of KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType)
  name.vb: MyQueue(Of KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyQueue`1
    name: MyQueue
    href: Innova.Data.AppSettings.MyQueue-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.MyQueue`1
    name: MyQueue
    href: Innova.Data.AppSettings.MyQueue-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Data.AppSettings.MyQueue{{KeyType}}.MaxCount
  commentId: P:Innova.Data.AppSettings.MyQueue{`0}.MaxCount
  parent: Innova.Data.AppSettings.MyQueue{{KeyType}}
  definition: Innova.Data.AppSettings.MyQueue`1.MaxCount
  href: Innova.Data.AppSettings.MyQueue-1.MaxCount.html#Innova_Data_AppSettings_MyQueue_1_MaxCount
  name: MaxCount
  nameWithType: MyQueue<KeyType>.MaxCount
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.MaxCount
  nameWithType.vb: MyQueue(Of KeyType).MaxCount
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).MaxCount
- uid: Innova.Data.AppSettings.MyQueue{{KeyType}}.List
  commentId: P:Innova.Data.AppSettings.MyQueue{`0}.List
  parent: Innova.Data.AppSettings.MyQueue{{KeyType}}
  definition: Innova.Data.AppSettings.MyQueue`1.List
  href: Innova.Data.AppSettings.MyQueue-1.List.html#Innova_Data_AppSettings_MyQueue_1_List
  name: List
  nameWithType: MyQueue<KeyType>.List
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.List
  nameWithType.vb: MyQueue(Of KeyType).List
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).List
- uid: Innova.Data.AppSettings.MyQueue{{KeyType}}.Remove({KeyType})
  commentId: M:Innova.Data.AppSettings.MyQueue{`0}.Remove(`0)
  parent: Innova.Data.AppSettings.MyQueue{{KeyType}}
  definition: Innova.Data.AppSettings.MyQueue`1.Remove(`0)
  href: Innova.Data.AppSettings.MyQueue-1.Remove.html#Innova_Data_AppSettings_MyQueue_1_Remove__0_
  name: Remove(KeyType)
  nameWithType: MyQueue<KeyType>.Remove(KeyType)
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.Remove(KeyType)
  nameWithType.vb: MyQueue(Of KeyType).Remove(KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).Remove(KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyQueue{`0}.Remove(`0)
    name: Remove
    href: Innova.Data.AppSettings.MyQueue-1.Remove.html#Innova_Data_AppSettings_MyQueue_1_Remove__0_
  - name: (
  - name: KeyType
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.MyQueue{`0}.Remove(`0)
    name: Remove
    href: Innova.Data.AppSettings.MyQueue-1.Remove.html#Innova_Data_AppSettings_MyQueue_1_Remove__0_
  - name: (
  - name: KeyType
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.MyQueue`1
  commentId: T:Innova.Data.AppSettings.MyQueue`1
  href: Innova.Data.AppSettings.MyQueue-1.html
  name: MyQueue<KeyType>
  nameWithType: MyQueue<KeyType>
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>
  nameWithType.vb: MyQueue(Of KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType)
  name.vb: MyQueue(Of KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyQueue`1
    name: MyQueue
    href: Innova.Data.AppSettings.MyQueue-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.MyQueue`1
    name: MyQueue
    href: Innova.Data.AppSettings.MyQueue-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Data.AppSettings.MyQueue`1.MaxCount
  commentId: P:Innova.Data.AppSettings.MyQueue`1.MaxCount
  href: Innova.Data.AppSettings.MyQueue-1.MaxCount.html#Innova_Data_AppSettings_MyQueue_1_MaxCount
  name: MaxCount
  nameWithType: MyQueue<KeyType>.MaxCount
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.MaxCount
  nameWithType.vb: MyQueue(Of KeyType).MaxCount
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).MaxCount
- uid: Innova.Data.AppSettings.MyQueue`1.List
  commentId: P:Innova.Data.AppSettings.MyQueue`1.List
  href: Innova.Data.AppSettings.MyQueue-1.List.html#Innova_Data_AppSettings_MyQueue_1_List
  name: List
  nameWithType: MyQueue<KeyType>.List
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.List
  nameWithType.vb: MyQueue(Of KeyType).List
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).List
- uid: Innova.Data.AppSettings.MyQueue`1.Remove(`0)
  commentId: M:Innova.Data.AppSettings.MyQueue`1.Remove(`0)
  href: Innova.Data.AppSettings.MyQueue-1.Remove.html#Innova_Data_AppSettings_MyQueue_1_Remove__0_
  name: Remove(KeyType)
  nameWithType: MyQueue<KeyType>.Remove(KeyType)
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.Remove(KeyType)
  nameWithType.vb: MyQueue(Of KeyType).Remove(KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).Remove(KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyQueue`1.Remove(`0)
    name: Remove
    href: Innova.Data.AppSettings.MyQueue-1.Remove.html#Innova_Data_AppSettings_MyQueue_1_Remove__0_
  - name: (
  - name: KeyType
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.MyQueue`1.Remove(`0)
    name: Remove
    href: Innova.Data.AppSettings.MyQueue-1.Remove.html#Innova_Data_AppSettings_MyQueue_1_Remove__0_
  - name: (
  - name: KeyType
  - name: )
- uid: Innova.Data.AppSettings.MyQueue{{KeyType}}.Add({KeyType})
  commentId: M:Innova.Data.AppSettings.MyQueue{`0}.Add(`0)
  parent: Innova.Data.AppSettings.MyQueue{{KeyType}}
  definition: Innova.Data.AppSettings.MyQueue`1.Add(`0)
  href: Innova.Data.AppSettings.MyQueue-1.Add.html#Innova_Data_AppSettings_MyQueue_1_Add__0_
  name: Add(KeyType)
  nameWithType: MyQueue<KeyType>.Add(KeyType)
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.Add(KeyType)
  nameWithType.vb: MyQueue(Of KeyType).Add(KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).Add(KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyQueue{`0}.Add(`0)
    name: Add
    href: Innova.Data.AppSettings.MyQueue-1.Add.html#Innova_Data_AppSettings_MyQueue_1_Add__0_
  - name: (
  - name: KeyType
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.MyQueue{`0}.Add(`0)
    name: Add
    href: Innova.Data.AppSettings.MyQueue-1.Add.html#Innova_Data_AppSettings_MyQueue_1_Add__0_
  - name: (
  - name: KeyType
  - name: )
- uid: Innova.Data.AppSettings.MyLatestList`1.Add*
  commentId: Overload:Innova.Data.AppSettings.MyLatestList`1.Add
  href: Innova.Data.AppSettings.MyLatestList-1.Add.html#Innova_Data_AppSettings_MyLatestList_1_Add__0_
  name: Add
  nameWithType: MyLatestList<KeyType>.Add
  fullName: Innova.Data.AppSettings.MyLatestList<KeyType>.Add
  nameWithType.vb: MyLatestList(Of KeyType).Add
  fullName.vb: Innova.Data.AppSettings.MyLatestList(Of KeyType).Add
- uid: '{KeyType}'
  commentId: '!:KeyType'
  definition: KeyType
  name: KeyType
  nameWithType: KeyType
  fullName: KeyType
- uid: Innova.Data.AppSettings.MyQueue`1.Add(`0)
  commentId: M:Innova.Data.AppSettings.MyQueue`1.Add(`0)
  href: Innova.Data.AppSettings.MyQueue-1.Add.html#Innova_Data_AppSettings_MyQueue_1_Add__0_
  name: Add(KeyType)
  nameWithType: MyQueue<KeyType>.Add(KeyType)
  fullName: Innova.Data.AppSettings.MyQueue<KeyType>.Add(KeyType)
  nameWithType.vb: MyQueue(Of KeyType).Add(KeyType)
  fullName.vb: Innova.Data.AppSettings.MyQueue(Of KeyType).Add(KeyType)
  spec.csharp:
  - uid: Innova.Data.AppSettings.MyQueue`1.Add(`0)
    name: Add
    href: Innova.Data.AppSettings.MyQueue-1.Add.html#Innova_Data_AppSettings_MyQueue_1_Add__0_
  - name: (
  - name: KeyType
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.MyQueue`1.Add(`0)
    name: Add
    href: Innova.Data.AppSettings.MyQueue-1.Add.html#Innova_Data_AppSettings_MyQueue_1_Add__0_
  - name: (
  - name: KeyType
  - name: )
- uid: KeyType
  name: KeyType
  nameWithType: KeyType
  fullName: KeyType
memberLayout: SeparatePages
