### YamlMime:ManagedReference
items:
- uid: Innova.Rest.Server.Security
  commentId: N:Innova.Rest.Server.Security
  id: Security
  parent: Innova.Rest.Server
  children:
  - Innova.Rest.Server.Security.ApplicationSecurityProvider`1
  - Innova.Rest.Server.Security.CachedUserProviderBase`1
  - Innova.Rest.Server.Security.IApplicationSecurityProvider`1
  - Innova.Rest.Server.Security.ISecurityBuilderFactory`1
  - Innova.Rest.Server.Security.IServiceCollectionExtensionsRestServer
  - Innova.Rest.Server.Security.SecurityBuilderFactory`3
  - Innova.Rest.Server.Security.ServerApplicationSecurityOptions
  - Innova.Rest.Server.Security.UserCacheOptions
  langs:
  - csharp
  - vb
  name: Innova.Rest.Server.Security
  nameWithType: Innova.Rest.Server.Security
  fullName: Innova.Rest.Server.Security
  type: Namespace
  assemblies:
  - Innova.Rest.Server
references:
- uid: Innova.Rest.Server.Security.ApplicationSecurityProvider`1
  commentId: T:Innova.Rest.Server.Security.ApplicationSecurityProvider`1
  href: Innova.Rest.Server.Security.ApplicationSecurityProvider-1.html
  name: ApplicationSecurityProvider<T>
  nameWithType: ApplicationSecurityProvider<T>
  fullName: Innova.Rest.Server.Security.ApplicationSecurityProvider<T>
  nameWithType.vb: ApplicationSecurityProvider(Of T)
  fullName.vb: Innova.Rest.Server.Security.ApplicationSecurityProvider(Of T)
  name.vb: ApplicationSecurityProvider(Of T)
  spec.csharp:
  - uid: Innova.Rest.Server.Security.ApplicationSecurityProvider`1
    name: ApplicationSecurityProvider
    href: Innova.Rest.Server.Security.ApplicationSecurityProvider-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Rest.Server.Security.ApplicationSecurityProvider`1
    name: ApplicationSecurityProvider
    href: Innova.Rest.Server.Security.ApplicationSecurityProvider-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Rest.Server.Security.CachedUserProviderBase`1
  commentId: T:Innova.Rest.Server.Security.CachedUserProviderBase`1
  href: Innova.Rest.Server.Security.CachedUserProviderBase-1.html
  name: CachedUserProviderBase<TUser>
  nameWithType: CachedUserProviderBase<TUser>
  fullName: Innova.Rest.Server.Security.CachedUserProviderBase<TUser>
  nameWithType.vb: CachedUserProviderBase(Of TUser)
  fullName.vb: Innova.Rest.Server.Security.CachedUserProviderBase(Of TUser)
  name.vb: CachedUserProviderBase(Of TUser)
  spec.csharp:
  - uid: Innova.Rest.Server.Security.CachedUserProviderBase`1
    name: CachedUserProviderBase
    href: Innova.Rest.Server.Security.CachedUserProviderBase-1.html
  - name: <
  - name: TUser
  - name: '>'
  spec.vb:
  - uid: Innova.Rest.Server.Security.CachedUserProviderBase`1
    name: CachedUserProviderBase
    href: Innova.Rest.Server.Security.CachedUserProviderBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TUser
  - name: )
- uid: Innova.Rest.Server.Security.IApplicationSecurityProvider`1
  commentId: T:Innova.Rest.Server.Security.IApplicationSecurityProvider`1
  href: Innova.Rest.Server.Security.IApplicationSecurityProvider-1.html
  name: IApplicationSecurityProvider<T>
  nameWithType: IApplicationSecurityProvider<T>
  fullName: Innova.Rest.Server.Security.IApplicationSecurityProvider<T>
  nameWithType.vb: IApplicationSecurityProvider(Of T)
  fullName.vb: Innova.Rest.Server.Security.IApplicationSecurityProvider(Of T)
  name.vb: IApplicationSecurityProvider(Of T)
  spec.csharp:
  - uid: Innova.Rest.Server.Security.IApplicationSecurityProvider`1
    name: IApplicationSecurityProvider
    href: Innova.Rest.Server.Security.IApplicationSecurityProvider-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Rest.Server.Security.IApplicationSecurityProvider`1
    name: IApplicationSecurityProvider
    href: Innova.Rest.Server.Security.IApplicationSecurityProvider-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Rest.Server.Security.ISecurityBuilderFactory`1
  commentId: T:Innova.Rest.Server.Security.ISecurityBuilderFactory`1
  href: Innova.Rest.Server.Security.ISecurityBuilderFactory-1.html
  name: ISecurityBuilderFactory<T>
  nameWithType: ISecurityBuilderFactory<T>
  fullName: Innova.Rest.Server.Security.ISecurityBuilderFactory<T>
  nameWithType.vb: ISecurityBuilderFactory(Of T)
  fullName.vb: Innova.Rest.Server.Security.ISecurityBuilderFactory(Of T)
  name.vb: ISecurityBuilderFactory(Of T)
  spec.csharp:
  - uid: Innova.Rest.Server.Security.ISecurityBuilderFactory`1
    name: ISecurityBuilderFactory
    href: Innova.Rest.Server.Security.ISecurityBuilderFactory-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Rest.Server.Security.ISecurityBuilderFactory`1
    name: ISecurityBuilderFactory
    href: Innova.Rest.Server.Security.ISecurityBuilderFactory-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Rest.Server.Security.IServiceCollectionExtensionsRestServer
  commentId: T:Innova.Rest.Server.Security.IServiceCollectionExtensionsRestServer
  href: Innova.Rest.Server.Security.IServiceCollectionExtensionsRestServer.html
  name: IServiceCollectionExtensionsRestServer
  nameWithType: IServiceCollectionExtensionsRestServer
  fullName: Innova.Rest.Server.Security.IServiceCollectionExtensionsRestServer
- uid: Innova.Rest.Server.Security.SecurityBuilderFactory`3
  commentId: T:Innova.Rest.Server.Security.SecurityBuilderFactory`3
  href: Innova.Rest.Server.Security.SecurityBuilderFactory-3.html
  name: SecurityBuilderFactory<TSecurityBuilder, TIApplicationSecurity, TApplicationSecurity>
  nameWithType: SecurityBuilderFactory<TSecurityBuilder, TIApplicationSecurity, TApplicationSecurity>
  fullName: Innova.Rest.Server.Security.SecurityBuilderFactory<TSecurityBuilder, TIApplicationSecurity, TApplicationSecurity>
  nameWithType.vb: SecurityBuilderFactory(Of TSecurityBuilder, TIApplicationSecurity, TApplicationSecurity)
  fullName.vb: Innova.Rest.Server.Security.SecurityBuilderFactory(Of TSecurityBuilder, TIApplicationSecurity, TApplicationSecurity)
  name.vb: SecurityBuilderFactory(Of TSecurityBuilder, TIApplicationSecurity, TApplicationSecurity)
  spec.csharp:
  - uid: Innova.Rest.Server.Security.SecurityBuilderFactory`3
    name: SecurityBuilderFactory
    href: Innova.Rest.Server.Security.SecurityBuilderFactory-3.html
  - name: <
  - name: TSecurityBuilder
  - name: ','
  - name: " "
  - name: TIApplicationSecurity
  - name: ','
  - name: " "
  - name: TApplicationSecurity
  - name: '>'
  spec.vb:
  - uid: Innova.Rest.Server.Security.SecurityBuilderFactory`3
    name: SecurityBuilderFactory
    href: Innova.Rest.Server.Security.SecurityBuilderFactory-3.html
  - name: (
  - name: Of
  - name: " "
  - name: TSecurityBuilder
  - name: ','
  - name: " "
  - name: TIApplicationSecurity
  - name: ','
  - name: " "
  - name: TApplicationSecurity
  - name: )
- uid: Innova.Rest.Server.Security.ServerApplicationSecurityOptions
  commentId: T:Innova.Rest.Server.Security.ServerApplicationSecurityOptions
  href: Innova.Rest.Server.Security.ServerApplicationSecurityOptions.html
  name: ServerApplicationSecurityOptions
  nameWithType: ServerApplicationSecurityOptions
  fullName: Innova.Rest.Server.Security.ServerApplicationSecurityOptions
- uid: Innova.Rest.Server.Security.UserCacheOptions
  commentId: T:Innova.Rest.Server.Security.UserCacheOptions
  href: Innova.Rest.Server.Security.UserCacheOptions.html
  name: UserCacheOptions
  nameWithType: UserCacheOptions
  fullName: Innova.Rest.Server.Security.UserCacheOptions
memberLayout: SeparatePages
