### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.EntitySavedQueryType
  commentId: T:Innova.Data.AppSettings.EntitySavedQueryType
  id: EntitySavedQueryType
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.EntitySavedQueryType.#ctor
  - Innova.Data.AppSettings.EntitySavedQueryType.#ctor(System.String)
  - Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId
  - Innova.Data.AppSettings.EntitySavedQueryType.EntityType
  - Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery(System.Nullable{System.Guid})
  - Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries
  - Innova.Data.AppSettings.EntitySavedQueryType.ViewKey
  langs:
  - csharp
  - vb
  name: EntitySavedQueryType
  nameWithType: EntitySavedQueryType
  fullName: Innova.Data.AppSettings.EntitySavedQueryType
  type: Class
  source:
    id: EntitySavedQueryType
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EntitySavedQueryType.cs
    startLine: 12
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents the type of entity saved query.
  example: []
  syntax:
    content: public class EntitySavedQueryType
    content.vb: Public Class EntitySavedQueryType
  inheritance:
  - System.Object
- uid: Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId
  commentId: P:Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId
  id: DefaultQueryId
  parent: Innova.Data.AppSettings.EntitySavedQueryType
  langs:
  - csharp
  - vb
  name: DefaultQueryId
  nameWithType: EntitySavedQueryType.DefaultQueryId
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId
  type: Property
  source:
    id: DefaultQueryId
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EntitySavedQueryType.cs
    startLine: 21
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the default query ID.
  example: []
  syntax:
    content: public Guid? DefaultQueryId { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Guid}
    content.vb: Public Property DefaultQueryId As Guid?
  overload: Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId*
- uid: Innova.Data.AppSettings.EntitySavedQueryType.EntityType
  commentId: P:Innova.Data.AppSettings.EntitySavedQueryType.EntityType
  id: EntityType
  parent: Innova.Data.AppSettings.EntitySavedQueryType
  langs:
  - csharp
  - vb
  name: EntityType
  nameWithType: EntitySavedQueryType.EntityType
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.EntityType
  type: Property
  source:
    id: EntityType
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EntitySavedQueryType.cs
    startLine: 33
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the EntityType.
  example: []
  syntax:
    content: public string EntityType { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property EntityType As String
  overload: Innova.Data.AppSettings.EntitySavedQueryType.EntityType*
- uid: Innova.Data.AppSettings.EntitySavedQueryType.ViewKey
  commentId: P:Innova.Data.AppSettings.EntitySavedQueryType.ViewKey
  id: ViewKey
  parent: Innova.Data.AppSettings.EntitySavedQueryType
  langs:
  - csharp
  - vb
  name: ViewKey
  nameWithType: EntitySavedQueryType.ViewKey
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.ViewKey
  type: Property
  source:
    id: ViewKey
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EntitySavedQueryType.cs
    startLine: 39
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the ViewKey.
  example: []
  syntax:
    content: public string ViewKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ViewKey As String
  overload: Innova.Data.AppSettings.EntitySavedQueryType.ViewKey*
- uid: Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries
  commentId: P:Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries
  id: SavedQueries
  parent: Innova.Data.AppSettings.EntitySavedQueryType
  langs:
  - csharp
  - vb
  name: SavedQueries
  nameWithType: EntitySavedQueryType.SavedQueries
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries
  type: Property
  source:
    id: SavedQueries
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EntitySavedQueryType.cs
    startLine: 45
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the list of saved queries.
  example: []
  syntax:
    content: public List<EntitySavedQuery> SavedQueries { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Innova.Data.StructuredSearch.EntitySavedQuery}
    content.vb: Public Property SavedQueries As List(Of EntitySavedQuery)
  overload: Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries*
- uid: Innova.Data.AppSettings.EntitySavedQueryType.#ctor(System.String)
  commentId: M:Innova.Data.AppSettings.EntitySavedQueryType.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Innova.Data.AppSettings.EntitySavedQueryType
  langs:
  - csharp
  - vb
  name: EntitySavedQueryType(string)
  nameWithType: EntitySavedQueryType.EntitySavedQueryType(string)
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.EntitySavedQueryType(string)
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EntitySavedQueryType.cs
    startLine: 52
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Initializes a new instance of the <xref href="Innova.Data.AppSettings.EntitySavedQueryType" data-throw-if-not-resolved="false"></xref> class with the specified entity type.
  example: []
  syntax:
    content: public EntitySavedQueryType(string entityType)
    parameters:
    - id: entityType
      type: System.String
      description: The entity type.
    content.vb: Public Sub New(entityType As String)
  overload: Innova.Data.AppSettings.EntitySavedQueryType.#ctor*
  nameWithType.vb: EntitySavedQueryType.New(String)
  fullName.vb: Innova.Data.AppSettings.EntitySavedQueryType.New(String)
  name.vb: New(String)
- uid: Innova.Data.AppSettings.EntitySavedQueryType.#ctor
  commentId: M:Innova.Data.AppSettings.EntitySavedQueryType.#ctor
  id: '#ctor'
  parent: Innova.Data.AppSettings.EntitySavedQueryType
  langs:
  - csharp
  - vb
  name: EntitySavedQueryType()
  nameWithType: EntitySavedQueryType.EntitySavedQueryType()
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.EntitySavedQueryType()
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EntitySavedQueryType.cs
    startLine: 60
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Initializes a new instance of the <xref href="Innova.Data.AppSettings.EntitySavedQueryType" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public EntitySavedQueryType()
    content.vb: Public Sub New()
  overload: Innova.Data.AppSettings.EntitySavedQueryType.#ctor*
  nameWithType.vb: EntitySavedQueryType.New()
  fullName.vb: Innova.Data.AppSettings.EntitySavedQueryType.New()
  name.vb: New()
- uid: Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery(System.Nullable{System.Guid})
  commentId: M:Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery(System.Nullable{System.Guid})
  id: GetDefaultSavedQuery(System.Nullable{System.Guid})
  parent: Innova.Data.AppSettings.EntitySavedQueryType
  langs:
  - csharp
  - vb
  name: GetDefaultSavedQuery(Guid?)
  nameWithType: EntitySavedQueryType.GetDefaultSavedQuery(Guid?)
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery(System.Guid?)
  type: Method
  source:
    id: GetDefaultSavedQuery
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\EntitySavedQueryType.cs
    startLine: 70
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the default saved query based on the specified default query ID.
  example: []
  syntax:
    content: public EntitySavedQuery GetDefaultSavedQuery(Guid? defaultQueryId)
    parameters:
    - id: defaultQueryId
      type: System.Nullable{System.Guid}
      description: The default query ID.
    return:
      type: Innova.Data.StructuredSearch.EntitySavedQuery
      description: The default saved query.
    content.vb: Public Function GetDefaultSavedQuery(defaultQueryId As Guid?) As EntitySavedQuery
  overload: Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery*
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId*
  commentId: Overload:Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId
  href: Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId.html#Innova_Data_AppSettings_EntitySavedQueryType_DefaultQueryId
  name: DefaultQueryId
  nameWithType: EntitySavedQueryType.DefaultQueryId
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.DefaultQueryId
- uid: System.Nullable{System.Guid}
  commentId: T:System.Nullable{System.Guid}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid?
  nameWithType: Guid?
  fullName: System.Guid?
  spec.csharp:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '?'
  spec.vb:
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.EntitySavedQueryType.EntityType*
  commentId: Overload:Innova.Data.AppSettings.EntitySavedQueryType.EntityType
  href: Innova.Data.AppSettings.EntitySavedQueryType.EntityType.html#Innova_Data_AppSettings_EntitySavedQueryType_EntityType
  name: EntityType
  nameWithType: EntitySavedQueryType.EntityType
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.EntityType
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Data.AppSettings.EntitySavedQueryType.ViewKey*
  commentId: Overload:Innova.Data.AppSettings.EntitySavedQueryType.ViewKey
  href: Innova.Data.AppSettings.EntitySavedQueryType.ViewKey.html#Innova_Data_AppSettings_EntitySavedQueryType_ViewKey
  name: ViewKey
  nameWithType: EntitySavedQueryType.ViewKey
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.ViewKey
- uid: Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries*
  commentId: Overload:Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries
  href: Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries.html#Innova_Data_AppSettings_EntitySavedQueryType_SavedQueries
  name: SavedQueries
  nameWithType: EntitySavedQueryType.SavedQueries
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.SavedQueries
- uid: System.Collections.Generic.List{Innova.Data.StructuredSearch.EntitySavedQuery}
  commentId: T:System.Collections.Generic.List{Innova.Data.StructuredSearch.EntitySavedQuery}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<EntitySavedQuery>
  nameWithType: List<EntitySavedQuery>
  fullName: System.Collections.Generic.List<Innova.Data.StructuredSearch.EntitySavedQuery>
  nameWithType.vb: List(Of EntitySavedQuery)
  fullName.vb: System.Collections.Generic.List(Of Innova.Data.StructuredSearch.EntitySavedQuery)
  name.vb: List(Of EntitySavedQuery)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: Innova.Data.StructuredSearch.EntitySavedQuery
    name: EntitySavedQuery
    href: Innova.Data.StructuredSearch.EntitySavedQuery.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.StructuredSearch.EntitySavedQuery
    name: EntitySavedQuery
    href: Innova.Data.StructuredSearch.EntitySavedQuery.html
  - name: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: Innova.Data.AppSettings.EntitySavedQueryType
  commentId: T:Innova.Data.AppSettings.EntitySavedQueryType
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.EntitySavedQueryType.html
  name: EntitySavedQueryType
  nameWithType: EntitySavedQueryType
  fullName: Innova.Data.AppSettings.EntitySavedQueryType
- uid: Innova.Data.AppSettings.EntitySavedQueryType.#ctor*
  commentId: Overload:Innova.Data.AppSettings.EntitySavedQueryType.#ctor
  href: Innova.Data.AppSettings.EntitySavedQueryType.-ctor.html#Innova_Data_AppSettings_EntitySavedQueryType__ctor_System_String_
  name: EntitySavedQueryType
  nameWithType: EntitySavedQueryType.EntitySavedQueryType
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.EntitySavedQueryType
  nameWithType.vb: EntitySavedQueryType.New
  fullName.vb: Innova.Data.AppSettings.EntitySavedQueryType.New
  name.vb: New
- uid: Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery*
  commentId: Overload:Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery
  href: Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery.html#Innova_Data_AppSettings_EntitySavedQueryType_GetDefaultSavedQuery_System_Nullable_System_Guid__
  name: GetDefaultSavedQuery
  nameWithType: EntitySavedQueryType.GetDefaultSavedQuery
  fullName: Innova.Data.AppSettings.EntitySavedQueryType.GetDefaultSavedQuery
- uid: Innova.Data.StructuredSearch.EntitySavedQuery
  commentId: T:Innova.Data.StructuredSearch.EntitySavedQuery
  parent: Innova.Data.StructuredSearch
  href: Innova.Data.StructuredSearch.EntitySavedQuery.html
  name: EntitySavedQuery
  nameWithType: EntitySavedQuery
  fullName: Innova.Data.StructuredSearch.EntitySavedQuery
- uid: Innova.Data.StructuredSearch
  commentId: N:Innova.Data.StructuredSearch
  href: Innova.html
  name: Innova.Data.StructuredSearch
  nameWithType: Innova.Data.StructuredSearch
  fullName: Innova.Data.StructuredSearch
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.StructuredSearch
    name: StructuredSearch
    href: Innova.Data.StructuredSearch.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.StructuredSearch
    name: StructuredSearch
    href: Innova.Data.StructuredSearch.html
memberLayout: SeparatePages
