### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.IUserSettingService`1
  commentId: T:Innova.Data.AppSettings.IUserSettingService`1
  id: IUserSettingService`1
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.IUserSettingService`1.Get
  langs:
  - csharp
  - vb
  name: IUserSettingService<T>
  nameWithType: IUserSettingService<T>
  fullName: Innova.Data.AppSettings.IUserSettingService<T>
  type: Interface
  source:
    id: IUserSettingService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IUserSettingService.cs
    startLine: 9
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents a user setting service that provides operations for retrieving and manipulating user settings.
  example: []
  syntax:
    content: 'public interface IUserSettingService<T> : IUserSettingService where T : class'
    typeParameters:
    - id: T
      description: The type of the user setting.
    content.vb: Public Interface IUserSettingService(Of T As Class) Inherits IUserSettingService
  inheritedMembers:
  - Innova.Data.AppSettings.IUserSettingService.GetValue``1(System.String)
  - Innova.Data.AppSettings.IUserSettingService.SetValue(System.String,System.Object)
  - Innova.Data.AppSettings.IUserSettingService.Save
  - Innova.Data.AppSettings.IUserSettingService.LoadData
  nameWithType.vb: IUserSettingService(Of T)
  fullName.vb: Innova.Data.AppSettings.IUserSettingService(Of T)
  name.vb: IUserSettingService(Of T)
- uid: Innova.Data.AppSettings.IUserSettingService`1.Get
  commentId: M:Innova.Data.AppSettings.IUserSettingService`1.Get
  id: Get
  parent: Innova.Data.AppSettings.IUserSettingService`1
  langs:
  - csharp
  - vb
  name: Get()
  nameWithType: IUserSettingService<T>.Get()
  fullName: Innova.Data.AppSettings.IUserSettingService<T>.Get()
  type: Method
  source:
    id: Get
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IUserSettingService.cs
    startLine: 15
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the user setting.
  example: []
  syntax:
    content: T Get()
    return:
      type: '{T}'
      description: The user setting.
    content.vb: Function [Get]() As T
  overload: Innova.Data.AppSettings.IUserSettingService`1.Get*
  nameWithType.vb: IUserSettingService(Of T).Get()
  fullName.vb: Innova.Data.AppSettings.IUserSettingService(Of T).Get()
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Data.AppSettings.IUserSettingService.GetValue``1(System.String)
  commentId: M:Innova.Data.AppSettings.IUserSettingService.GetValue``1(System.String)
  parent: Innova.Data.AppSettings.IUserSettingService
  isExternal: true
  href: Innova.Data.AppSettings.IUserSettingService.GetValue.html#Innova_Data_AppSettings_IUserSettingService_GetValue__1_System_String_
  name: GetValue<ValueType>(string)
  nameWithType: IUserSettingService.GetValue<ValueType>(string)
  fullName: Innova.Data.AppSettings.IUserSettingService.GetValue<ValueType>(string)
  nameWithType.vb: IUserSettingService.GetValue(Of ValueType)(String)
  fullName.vb: Innova.Data.AppSettings.IUserSettingService.GetValue(Of ValueType)(String)
  name.vb: GetValue(Of ValueType)(String)
  spec.csharp:
  - uid: Innova.Data.AppSettings.IUserSettingService.GetValue``1(System.String)
    name: GetValue
    href: Innova.Data.AppSettings.IUserSettingService.GetValue.html#Innova_Data_AppSettings_IUserSettingService_GetValue__1_System_String_
  - name: <
  - name: ValueType
  - name: '>'
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.IUserSettingService.GetValue``1(System.String)
    name: GetValue
    href: Innova.Data.AppSettings.IUserSettingService.GetValue.html#Innova_Data_AppSettings_IUserSettingService_GetValue__1_System_String_
  - name: (
  - name: Of
  - name: " "
  - name: ValueType
  - name: )
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: Innova.Data.AppSettings.IUserSettingService.SetValue(System.String,System.Object)
  commentId: M:Innova.Data.AppSettings.IUserSettingService.SetValue(System.String,System.Object)
  parent: Innova.Data.AppSettings.IUserSettingService
  isExternal: true
  href: Innova.Data.AppSettings.IUserSettingService.SetValue.html#Innova_Data_AppSettings_IUserSettingService_SetValue_System_String_System_Object_
  name: SetValue(string, object)
  nameWithType: IUserSettingService.SetValue(string, object)
  fullName: Innova.Data.AppSettings.IUserSettingService.SetValue(string, object)
  nameWithType.vb: IUserSettingService.SetValue(String, Object)
  fullName.vb: Innova.Data.AppSettings.IUserSettingService.SetValue(String, Object)
  name.vb: SetValue(String, Object)
  spec.csharp:
  - uid: Innova.Data.AppSettings.IUserSettingService.SetValue(System.String,System.Object)
    name: SetValue
    href: Innova.Data.AppSettings.IUserSettingService.SetValue.html#Innova_Data_AppSettings_IUserSettingService_SetValue_System_String_System_Object_
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.IUserSettingService.SetValue(System.String,System.Object)
    name: SetValue
    href: Innova.Data.AppSettings.IUserSettingService.SetValue.html#Innova_Data_AppSettings_IUserSettingService_SetValue_System_String_System_Object_
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: Innova.Data.AppSettings.IUserSettingService.Save
  commentId: M:Innova.Data.AppSettings.IUserSettingService.Save
  parent: Innova.Data.AppSettings.IUserSettingService
  href: Innova.Data.AppSettings.IUserSettingService.Save.html#Innova_Data_AppSettings_IUserSettingService_Save
  name: Save()
  nameWithType: IUserSettingService.Save()
  fullName: Innova.Data.AppSettings.IUserSettingService.Save()
  spec.csharp:
  - uid: Innova.Data.AppSettings.IUserSettingService.Save
    name: Save
    href: Innova.Data.AppSettings.IUserSettingService.Save.html#Innova_Data_AppSettings_IUserSettingService_Save
  - name: (
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.IUserSettingService.Save
    name: Save
    href: Innova.Data.AppSettings.IUserSettingService.Save.html#Innova_Data_AppSettings_IUserSettingService_Save
  - name: (
  - name: )
- uid: Innova.Data.AppSettings.IUserSettingService.LoadData
  commentId: M:Innova.Data.AppSettings.IUserSettingService.LoadData
  parent: Innova.Data.AppSettings.IUserSettingService
  href: Innova.Data.AppSettings.IUserSettingService.LoadData.html#Innova_Data_AppSettings_IUserSettingService_LoadData
  name: LoadData()
  nameWithType: IUserSettingService.LoadData()
  fullName: Innova.Data.AppSettings.IUserSettingService.LoadData()
  spec.csharp:
  - uid: Innova.Data.AppSettings.IUserSettingService.LoadData
    name: LoadData
    href: Innova.Data.AppSettings.IUserSettingService.LoadData.html#Innova_Data_AppSettings_IUserSettingService_LoadData
  - name: (
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.IUserSettingService.LoadData
    name: LoadData
    href: Innova.Data.AppSettings.IUserSettingService.LoadData.html#Innova_Data_AppSettings_IUserSettingService_LoadData
  - name: (
  - name: )
- uid: Innova.Data.AppSettings.IUserSettingService
  commentId: T:Innova.Data.AppSettings.IUserSettingService
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.IUserSettingService.html
  name: IUserSettingService
  nameWithType: IUserSettingService
  fullName: Innova.Data.AppSettings.IUserSettingService
- uid: Innova.Data.AppSettings.IUserSettingService`1.Get*
  commentId: Overload:Innova.Data.AppSettings.IUserSettingService`1.Get
  href: Innova.Data.AppSettings.IUserSettingService-1.Get.html#Innova_Data_AppSettings_IUserSettingService_1_Get
  name: Get
  nameWithType: IUserSettingService<T>.Get
  fullName: Innova.Data.AppSettings.IUserSettingService<T>.Get
  nameWithType.vb: IUserSettingService(Of T).Get
  fullName.vb: Innova.Data.AppSettings.IUserSettingService(Of T).Get
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
memberLayout: SeparatePages
