### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.IApplicationSettingService
  commentId: T:Innova.Data.AppSettings.IApplicationSettingService
  id: IApplicationSettingService
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
  - Innova.Data.AppSettings.IApplicationSettingService.LoadData
  - Innova.Data.AppSettings.IApplicationSettingService.Save
  langs:
  - csharp
  - vb
  name: IApplicationSettingService
  nameWithType: IApplicationSettingService
  fullName: Innova.Data.AppSettings.IApplicationSettingService
  type: Interface
  source:
    id: IApplicationSettingService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IApplicationSettingService.cs
    startLine: 21
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents an interface for managing application settings.
  example: []
  syntax:
    content: public interface IApplicationSettingService
    content.vb: Public Interface IApplicationSettingService
- uid: Innova.Data.AppSettings.IApplicationSettingService.Save
  commentId: M:Innova.Data.AppSettings.IApplicationSettingService.Save
  id: Save
  parent: Innova.Data.AppSettings.IApplicationSettingService
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: IApplicationSettingService.Save()
  fullName: Innova.Data.AppSettings.IApplicationSettingService.Save()
  type: Method
  source:
    id: Save
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IApplicationSettingService.cs
    startLine: 27
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Saves the application settings.
  example: []
  syntax:
    content: Task Save()
    return:
      type: System.Threading.Tasks.Task
      description: A task representing the asynchronous save operation.
    content.vb: Function Save() As Task
  overload: Innova.Data.AppSettings.IApplicationSettingService.Save*
- uid: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
  commentId: M:Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
  id: GetSettingsAsObject
  parent: Innova.Data.AppSettings.IApplicationSettingService
  langs:
  - csharp
  - vb
  name: GetSettingsAsObject()
  nameWithType: IApplicationSettingService.GetSettingsAsObject()
  fullName: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject()
  type: Method
  source:
    id: GetSettingsAsObject
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IApplicationSettingService.cs
    startLine: 33
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the application settings as an object.
  example: []
  syntax:
    content: object GetSettingsAsObject()
    return:
      type: System.Object
      description: The application settings as an object.
    content.vb: Function GetSettingsAsObject() As Object
  overload: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject*
- uid: Innova.Data.AppSettings.IApplicationSettingService.LoadData
  commentId: M:Innova.Data.AppSettings.IApplicationSettingService.LoadData
  id: LoadData
  parent: Innova.Data.AppSettings.IApplicationSettingService
  langs:
  - csharp
  - vb
  name: LoadData()
  nameWithType: IApplicationSettingService.LoadData()
  fullName: Innova.Data.AppSettings.IApplicationSettingService.LoadData()
  type: Method
  source:
    id: LoadData
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\IApplicationSettingService.cs
    startLine: 39
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Loads the data for the application settings.
  example: []
  syntax:
    content: Task LoadData()
    return:
      type: System.Threading.Tasks.Task
      description: A task representing the asynchronous load operation.
    content.vb: Function LoadData() As Task
  overload: Innova.Data.AppSettings.IApplicationSettingService.LoadData*
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Data.AppSettings.IApplicationSettingService.Save*
  commentId: Overload:Innova.Data.AppSettings.IApplicationSettingService.Save
  href: Innova.Data.AppSettings.IApplicationSettingService.Save.html#Innova_Data_AppSettings_IApplicationSettingService_Save
  name: Save
  nameWithType: IApplicationSettingService.Save
  fullName: Innova.Data.AppSettings.IApplicationSettingService.Save
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject*
  commentId: Overload:Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
  href: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject.html#Innova_Data_AppSettings_IApplicationSettingService_GetSettingsAsObject
  name: GetSettingsAsObject
  nameWithType: IApplicationSettingService.GetSettingsAsObject
  fullName: Innova.Data.AppSettings.IApplicationSettingService.GetSettingsAsObject
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.IApplicationSettingService.LoadData*
  commentId: Overload:Innova.Data.AppSettings.IApplicationSettingService.LoadData
  href: Innova.Data.AppSettings.IApplicationSettingService.LoadData.html#Innova_Data_AppSettings_IApplicationSettingService_LoadData
  name: LoadData
  nameWithType: IApplicationSettingService.LoadData
  fullName: Innova.Data.AppSettings.IApplicationSettingService.LoadData
memberLayout: SeparatePages
