### YamlMime:ManagedReference
items:
- uid: Innova.Data.Revision.RevisionDetailTypeConfiguration
  commentId: T:Innova.Data.Revision.RevisionDetailTypeConfiguration
  id: RevisionDetailTypeConfiguration
  parent: Innova.Data.Revision
  children:
  - Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
  langs:
  - csharp
  - vb
  name: RevisionDetailTypeConfiguration
  nameWithType: RevisionDetailTypeConfiguration
  fullName: Innova.Data.Revision.RevisionDetailTypeConfiguration
  type: Class
  source:
    id: RevisionDetailTypeConfiguration
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Revision\RevisionDbContextTypeConfigurations.cs
    startLine: 25
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Revision
  summary: Represents the configuration for the <xref href="Innova.Data.Revision.RevisionDetail" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: 'public class RevisionDetailTypeConfiguration : IEntityTypeConfiguration<RevisionDetail>'
    content.vb: Public Class RevisionDetailTypeConfiguration Implements IEntityTypeConfiguration(Of RevisionDetail)
  inheritance:
  - System.Object
  implements:
  - Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}
- uid: Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
  commentId: M:Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
  id: Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
  parent: Innova.Data.Revision.RevisionDetailTypeConfiguration
  langs:
  - csharp
  - vb
  name: Configure(EntityTypeBuilder<RevisionDetail>)
  nameWithType: RevisionDetailTypeConfiguration.Configure(EntityTypeBuilder<RevisionDetail>)
  fullName: Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.Revision.RevisionDetail>)
  type: Method
  source:
    id: Configure
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Revision\RevisionDbContextTypeConfigurations.cs
    startLine: 31
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Revision
  summary: Configures the <xref href="Innova.Data.Revision.RevisionDetail" data-throw-if-not-resolved="false"></xref> entity.
  example: []
  syntax:
    content: public void Configure(EntityTypeBuilder<RevisionDetail> builder)
    parameters:
    - id: builder
      type: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail}
      description: The entity type builder used to configure the entity.
    content.vb: Public Sub Configure(builder As EntityTypeBuilder(Of RevisionDetail))
  overload: Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure*
  implements:
  - Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
  nameWithType.vb: RevisionDetailTypeConfiguration.Configure(EntityTypeBuilder(Of RevisionDetail))
  fullName.vb: Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.Revision.RevisionDetail))
  name.vb: Configure(EntityTypeBuilder(Of RevisionDetail))
references:
- uid: Innova.Data.Revision.RevisionDetail
  commentId: T:Innova.Data.Revision.RevisionDetail
  href: Innova.Data.Revision.RevisionDetail.html
  name: RevisionDetail
  nameWithType: RevisionDetail
  fullName: Innova.Data.Revision.RevisionDetail
- uid: Innova.Data.Revision
  commentId: N:Innova.Data.Revision
  href: Innova.html
  name: Innova.Data.Revision
  nameWithType: Innova.Data.Revision
  fullName: Innova.Data.Revision
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Revision
    name: Revision
    href: Innova.Data.Revision.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Revision
    name: Revision
    href: Innova.Data.Revision.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}
  commentId: T:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}
  parent: Microsoft.EntityFrameworkCore
  definition: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  name: IEntityTypeConfiguration<RevisionDetail>
  nameWithType: IEntityTypeConfiguration<RevisionDetail>
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Innova.Data.Revision.RevisionDetail>
  nameWithType.vb: IEntityTypeConfiguration(Of RevisionDetail)
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of Innova.Data.Revision.RevisionDetail)
  name.vb: IEntityTypeConfiguration(Of RevisionDetail)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: <
  - uid: Innova.Data.Revision.RevisionDetail
    name: RevisionDetail
    href: Innova.Data.Revision.RevisionDetail.html
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.Revision.RevisionDetail
    name: RevisionDetail
    href: Innova.Data.Revision.RevisionDetail.html
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  commentId: T:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  name: IEntityTypeConfiguration<TEntity>
  nameWithType: IEntityTypeConfiguration<TEntity>
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<TEntity>
  nameWithType.vb: IEntityTypeConfiguration(Of TEntity)
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of TEntity)
  name.vb: IEntityTypeConfiguration(Of TEntity)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
- uid: Microsoft.EntityFrameworkCore
  commentId: N:Microsoft.EntityFrameworkCore
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.EntityFrameworkCore
  nameWithType: Microsoft.EntityFrameworkCore
  fullName: Microsoft.EntityFrameworkCore
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
- uid: Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure*
  commentId: Overload:Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure
  href: Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure.html#Innova_Data_Revision_RevisionDetailTypeConfiguration_Configure_Microsoft_EntityFrameworkCore_Metadata_Builders_EntityTypeBuilder_Innova_Data_Revision_RevisionDetail__
  name: Configure
  nameWithType: RevisionDetailTypeConfiguration.Configure
  fullName: Innova.Data.Revision.RevisionDetailTypeConfiguration.Configure
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
  commentId: M:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
  parent: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}
  definition: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  name: Configure(EntityTypeBuilder<RevisionDetail>)
  nameWithType: IEntityTypeConfiguration<RevisionDetail>.Configure(EntityTypeBuilder<RevisionDetail>)
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Innova.Data.Revision.RevisionDetail>.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.Revision.RevisionDetail>)
  nameWithType.vb: IEntityTypeConfiguration(Of RevisionDetail).Configure(EntityTypeBuilder(Of RevisionDetail))
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of Innova.Data.Revision.RevisionDetail).Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.Revision.RevisionDetail))
  name.vb: Configure(EntityTypeBuilder(Of RevisionDetail))
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - uid: Innova.Data.Revision.RevisionDetail
    name: RevisionDetail
    href: Innova.Data.Revision.RevisionDetail.html
  - name: '>'
  - name: )
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionDetail}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.Revision.RevisionDetail
    name: RevisionDetail
    href: Innova.Data.Revision.RevisionDetail.html
  - name: )
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail}
  commentId: T:Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionDetail}
  parent: Microsoft.EntityFrameworkCore.Metadata.Builders
  definition: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  name: EntityTypeBuilder<RevisionDetail>
  nameWithType: EntityTypeBuilder<RevisionDetail>
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.Revision.RevisionDetail>
  nameWithType.vb: EntityTypeBuilder(Of RevisionDetail)
  fullName.vb: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.Revision.RevisionDetail)
  name.vb: EntityTypeBuilder(Of RevisionDetail)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - uid: Innova.Data.Revision.RevisionDetail
    name: RevisionDetail
    href: Innova.Data.Revision.RevisionDetail.html
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.Revision.RevisionDetail
    name: RevisionDetail
    href: Innova.Data.Revision.RevisionDetail.html
  - name: )
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  commentId: M:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  name: Configure(EntityTypeBuilder<TEntity>)
  nameWithType: IEntityTypeConfiguration<TEntity>.Configure(EntityTypeBuilder<TEntity>)
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<TEntity>.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>)
  nameWithType.vb: IEntityTypeConfiguration(Of TEntity).Configure(EntityTypeBuilder(Of TEntity))
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of TEntity).Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity))
  name.vb: Configure(EntityTypeBuilder(Of TEntity))
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - name: TEntity
  - name: '>'
  - name: )
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  commentId: T:Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  name: EntityTypeBuilder<TEntity>
  nameWithType: EntityTypeBuilder<TEntity>
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>
  nameWithType.vb: EntityTypeBuilder(Of TEntity)
  fullName.vb: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity)
  name.vb: EntityTypeBuilder(Of TEntity)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders
  commentId: N:Microsoft.EntityFrameworkCore.Metadata.Builders
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.EntityFrameworkCore.Metadata.Builders
  nameWithType: Microsoft.EntityFrameworkCore.Metadata.Builders
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata
    name: Metadata
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders
    name: Builders
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata
    name: Metadata
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders
    name: Builders
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders
memberLayout: SeparatePages
