### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Library.IInnovaApplicationBuilder
  commentId: T:Innova.Prism.Library.IInnovaApplicationBuilder
  id: IInnovaApplicationBuilder
  parent: Innova.Prism.Library
  children:
  - Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity(Unity.IUnityContainer)
  - Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow
  - Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule(Prism.Modularity.IModuleCatalog)
  langs:
  - csharp
  - vb
  name: IInnovaApplicationBuilder
  nameWithType: IInnovaApplicationBuilder
  fullName: Innova.Prism.Library.IInnovaApplicationBuilder
  type: Interface
  source:
    id: IInnovaApplicationBuilder
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\IInnovaApplicationBuilder.cs
    startLine: 13
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library
  summary: Represents an interface for building an Innova application.
  example: []
  syntax:
    content: 'public interface IInnovaApplicationBuilder : IInnovaApplicationBuilderBase'
    content.vb: Public Interface IInnovaApplicationBuilder Inherits IInnovaApplicationBuilderBase
  inheritedMembers:
  - Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.AppExtensionBuilders
  - Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Services
  - Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Connection
  - Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.HttpPath
  extensionMethods:
  - Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2
- uid: Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity(Unity.IUnityContainer)
  commentId: M:Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity(Unity.IUnityContainer)
  id: BuildWithUnity(Unity.IUnityContainer)
  parent: Innova.Prism.Library.IInnovaApplicationBuilder
  langs:
  - csharp
  - vb
  name: BuildWithUnity(IUnityContainer)
  nameWithType: IInnovaApplicationBuilder.BuildWithUnity(IUnityContainer)
  fullName: Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity(Unity.IUnityContainer)
  type: Method
  source:
    id: BuildWithUnity
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\IInnovaApplicationBuilder.cs
    startLine: 19
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library
  summary: Builds the application with Unity container.
  example: []
  syntax:
    content: void BuildWithUnity(IUnityContainer container)
    parameters:
    - id: container
      type: Unity.IUnityContainer
      description: The Unity container.
    content.vb: Sub BuildWithUnity(container As IUnityContainer)
  overload: Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity*
- uid: Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow
  commentId: M:Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow
  id: CreateMainWindow
  parent: Innova.Prism.Library.IInnovaApplicationBuilder
  langs:
  - csharp
  - vb
  name: CreateMainWindow()
  nameWithType: IInnovaApplicationBuilder.CreateMainWindow()
  fullName: Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow()
  type: Method
  source:
    id: CreateMainWindow
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\IInnovaApplicationBuilder.cs
    startLine: 25
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library
  summary: Creates the main window of the application.
  example: []
  syntax:
    content: Window CreateMainWindow()
    return:
      type: System.Windows.Window
      description: The main window.
    content.vb: Function CreateMainWindow() As Window
  overload: Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow*
- uid: Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule(Prism.Modularity.IModuleCatalog)
  commentId: M:Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule(Prism.Modularity.IModuleCatalog)
  id: LoadPrismModule(Prism.Modularity.IModuleCatalog)
  parent: Innova.Prism.Library.IInnovaApplicationBuilder
  langs:
  - csharp
  - vb
  name: LoadPrismModule(IModuleCatalog)
  nameWithType: IInnovaApplicationBuilder.LoadPrismModule(IModuleCatalog)
  fullName: Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule(Prism.Modularity.IModuleCatalog)
  type: Method
  source:
    id: LoadPrismModule
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\IInnovaApplicationBuilder.cs
    startLine: 31
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library
  summary: Loads the Prism module using the specified module catalog.
  example: []
  syntax:
    content: void LoadPrismModule(IModuleCatalog moduleCatalog)
    parameters:
    - id: moduleCatalog
      type: Prism.Modularity.IModuleCatalog
      description: The module catalog.
    content.vb: Sub LoadPrismModule(moduleCatalog As IModuleCatalog)
  overload: Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule*
references:
- uid: Innova.Prism.Library
  commentId: N:Innova.Prism.Library
  href: Innova.html
  name: Innova.Prism.Library
  nameWithType: Innova.Prism.Library
  fullName: Innova.Prism.Library
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.AppExtensionBuilders
  commentId: P:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.AppExtensionBuilders
  parent: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  name: AppExtensionBuilders
  nameWithType: IInnovaApplicationBuilderBase.AppExtensionBuilders
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.AppExtensionBuilders
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Services
  commentId: P:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Services
  parent: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  name: Services
  nameWithType: IInnovaApplicationBuilderBase.Services
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Services
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Connection
  commentId: P:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Connection
  parent: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  name: Connection
  nameWithType: IInnovaApplicationBuilderBase.Connection
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Connection
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.HttpPath
  commentId: P:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.HttpPath
  parent: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  name: HttpPath
  nameWithType: IInnovaApplicationBuilderBase.HttpPath
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.HttpPath
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2
  commentId: M:Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  parent: Innova.Prism.Library.IInnovaApplicationBuilderExt
  definition: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  href: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow.html#Innova_Prism_Library_IInnovaApplicationBuilderExt_AddMainWindow__2_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_
  name: AddMainWindow<TView, TViewModel>(IInnovaApplicationBuilderBase)
  nameWithType: IInnovaApplicationBuilderExt.AddMainWindow<TView, TViewModel>(IInnovaApplicationBuilderBase)
  fullName: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow<TView, TViewModel>(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  nameWithType.vb: IInnovaApplicationBuilderExt.AddMainWindow(Of TView, TViewModel)(IInnovaApplicationBuilderBase)
  fullName.vb: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow(Of TView, TViewModel)(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  name.vb: AddMainWindow(Of TView, TViewModel)(IInnovaApplicationBuilderBase)
  spec.csharp:
  - uid: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
    name: AddMainWindow
    href: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow.html#Innova_Prism_Library_IInnovaApplicationBuilderExt_AddMainWindow__2_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_
  - name: <
  - name: TView
  - name: ','
  - name: " "
  - name: TViewModel
  - name: '>'
  - name: (
  - uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
    name: IInnovaApplicationBuilderBase
  - name: )
  spec.vb:
  - uid: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
    name: AddMainWindow
    href: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow.html#Innova_Prism_Library_IInnovaApplicationBuilderExt_AddMainWindow__2_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_
  - name: (
  - name: Of
  - name: " "
  - name: TView
  - name: ','
  - name: " "
  - name: TViewModel
  - name: )
  - name: (
  - uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
    name: IInnovaApplicationBuilderBase
  - name: )
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  commentId: T:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  parent: Innova.Abstractions.Builder
  href: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.html
  name: IInnovaApplicationBuilderBase
  nameWithType: IInnovaApplicationBuilderBase
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
- uid: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  commentId: M:Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  href: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow.html#Innova_Prism_Library_IInnovaApplicationBuilderExt_AddMainWindow__2_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_
  name: AddMainWindow<TView, TViewModel>(IInnovaApplicationBuilderBase)
  nameWithType: IInnovaApplicationBuilderExt.AddMainWindow<TView, TViewModel>(IInnovaApplicationBuilderBase)
  fullName: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow<TView, TViewModel>(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  nameWithType.vb: IInnovaApplicationBuilderExt.AddMainWindow(Of TView, TViewModel)(IInnovaApplicationBuilderBase)
  fullName.vb: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow(Of TView, TViewModel)(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  name.vb: AddMainWindow(Of TView, TViewModel)(IInnovaApplicationBuilderBase)
  spec.csharp:
  - uid: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
    name: AddMainWindow
    href: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow.html#Innova_Prism_Library_IInnovaApplicationBuilderExt_AddMainWindow__2_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_
  - name: <
  - name: TView
  - name: ','
  - name: " "
  - name: TViewModel
  - name: '>'
  - name: (
  - uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
    name: IInnovaApplicationBuilderBase
  - name: )
  spec.vb:
  - uid: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow``2(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
    name: AddMainWindow
    href: Innova.Prism.Library.IInnovaApplicationBuilderExt.AddMainWindow.html#Innova_Prism_Library_IInnovaApplicationBuilderExt_AddMainWindow__2_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_
  - name: (
  - name: Of
  - name: " "
  - name: TView
  - name: ','
  - name: " "
  - name: TViewModel
  - name: )
  - name: (
  - uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
    name: IInnovaApplicationBuilderBase
  - name: )
- uid: Innova.Prism.Library.IInnovaApplicationBuilderExt
  commentId: T:Innova.Prism.Library.IInnovaApplicationBuilderExt
  parent: Innova.Prism.Library
  href: Innova.Prism.Library.IInnovaApplicationBuilderExt.html
  name: IInnovaApplicationBuilderExt
  nameWithType: IInnovaApplicationBuilderExt
  fullName: Innova.Prism.Library.IInnovaApplicationBuilderExt
- uid: Innova.Abstractions.Builder
  commentId: N:Innova.Abstractions.Builder
  href: Innova.html
  name: Innova.Abstractions.Builder
  nameWithType: Innova.Abstractions.Builder
  fullName: Innova.Abstractions.Builder
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
- uid: Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity*
  commentId: Overload:Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity
  href: Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity.html#Innova_Prism_Library_IInnovaApplicationBuilder_BuildWithUnity_Unity_IUnityContainer_
  name: BuildWithUnity
  nameWithType: IInnovaApplicationBuilder.BuildWithUnity
  fullName: Innova.Prism.Library.IInnovaApplicationBuilder.BuildWithUnity
- uid: Unity.IUnityContainer
  commentId: T:Unity.IUnityContainer
  parent: Unity
  isExternal: true
  name: IUnityContainer
  nameWithType: IUnityContainer
  fullName: Unity.IUnityContainer
- uid: Unity
  commentId: N:Unity
  isExternal: true
  name: Unity
  nameWithType: Unity
  fullName: Unity
- uid: Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow*
  commentId: Overload:Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow
  href: Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow.html#Innova_Prism_Library_IInnovaApplicationBuilder_CreateMainWindow
  name: CreateMainWindow
  nameWithType: IInnovaApplicationBuilder.CreateMainWindow
  fullName: Innova.Prism.Library.IInnovaApplicationBuilder.CreateMainWindow
- uid: System.Windows.Window
  commentId: T:System.Windows.Window
  parent: System.Windows
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.windows.window
  name: Window
  nameWithType: Window
  fullName: System.Windows.Window
- uid: System.Windows
  commentId: N:System.Windows
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Windows
  nameWithType: System.Windows
  fullName: System.Windows
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Windows
    name: Windows
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.windows
- uid: Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule*
  commentId: Overload:Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule
  href: Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule.html#Innova_Prism_Library_IInnovaApplicationBuilder_LoadPrismModule_Prism_Modularity_IModuleCatalog_
  name: LoadPrismModule
  nameWithType: IInnovaApplicationBuilder.LoadPrismModule
  fullName: Innova.Prism.Library.IInnovaApplicationBuilder.LoadPrismModule
- uid: Prism.Modularity.IModuleCatalog
  commentId: T:Prism.Modularity.IModuleCatalog
  parent: Prism.Modularity
  isExternal: true
  name: IModuleCatalog
  nameWithType: IModuleCatalog
  fullName: Prism.Modularity.IModuleCatalog
- uid: Prism.Modularity
  commentId: N:Prism.Modularity
  isExternal: true
  name: Prism.Modularity
  nameWithType: Prism.Modularity
  fullName: Prism.Modularity
  spec.csharp:
  - uid: Prism
    name: Prism
    isExternal: true
  - name: .
  - uid: Prism.Modularity
    name: Modularity
    isExternal: true
  spec.vb:
  - uid: Prism
    name: Prism
    isExternal: true
  - name: .
  - uid: Prism.Modularity
    name: Modularity
    isExternal: true
memberLayout: SeparatePages
