### YamlMime:ManagedReference
items:
- uid: Innova.Data.Entity.Localization.LanguageConfiguration
  commentId: T:Innova.Data.Entity.Localization.LanguageConfiguration
  id: LanguageConfiguration
  parent: Innova.Data.Entity.Localization
  children:
  - Innova.Data.Entity.Localization.LanguageConfiguration.Language
  langs:
  - csharp
  - vb
  name: LanguageConfiguration
  nameWithType: LanguageConfiguration
  fullName: Innova.Data.Entity.Localization.LanguageConfiguration
  type: Class
  source:
    id: LanguageConfiguration
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Entity\Localization\LanguageConfiguration.cs
    startLine: 10
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Entity.Localization
  summary: Represents the configuration for language settings.
  example: []
  syntax:
    content: public class LanguageConfiguration
    content.vb: Public Class LanguageConfiguration
  inheritance:
  - System.Object
- uid: Innova.Data.Entity.Localization.LanguageConfiguration.Language
  commentId: P:Innova.Data.Entity.Localization.LanguageConfiguration.Language
  id: Language
  parent: Innova.Data.Entity.Localization.LanguageConfiguration
  langs:
  - csharp
  - vb
  name: Language
  nameWithType: LanguageConfiguration.Language
  fullName: Innova.Data.Entity.Localization.LanguageConfiguration.Language
  type: Property
  source:
    id: Language
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Entity\Localization\LanguageConfiguration.cs
    startLine: 17
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Entity.Localization
  summary: Gets or sets the language.
  example: []
  syntax:
    content: public string Language { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Language As String
  overload: Innova.Data.Entity.Localization.LanguageConfiguration.Language*
references:
- uid: Innova.Data.Entity.Localization
  commentId: N:Innova.Data.Entity.Localization
  href: Innova.html
  name: Innova.Data.Entity.Localization
  nameWithType: Innova.Data.Entity.Localization
  fullName: Innova.Data.Entity.Localization
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Entity
    name: Entity
    href: Innova.Data.Entity.html
  - name: .
  - uid: Innova.Data.Entity.Localization
    name: Localization
    href: Innova.Data.Entity.Localization.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Entity
    name: Entity
    href: Innova.Data.Entity.html
  - name: .
  - uid: Innova.Data.Entity.Localization
    name: Localization
    href: Innova.Data.Entity.Localization.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.Entity.Localization.LanguageConfiguration.Language*
  commentId: Overload:Innova.Data.Entity.Localization.LanguageConfiguration.Language
  href: Innova.Data.Entity.Localization.LanguageConfiguration.Language.html#Innova_Data_Entity_Localization_LanguageConfiguration_Language
  name: Language
  nameWithType: LanguageConfiguration.Language
  fullName: Innova.Data.Entity.Localization.LanguageConfiguration.Language
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
memberLayout: SeparatePages
