### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Infrastructure.Settings.MyList`1
  commentId: T:Innova.Prism.Infrastructure.Settings.MyList`1
  id: MyList`1
  parent: Innova.Prism.Infrastructure.Settings
  children:
  - Innova.Prism.Infrastructure.Settings.MyList`1.#ctor
  - Innova.Prism.Infrastructure.Settings.MyList`1.LatestList
  - Innova.Prism.Infrastructure.Settings.MyList`1.PinnedList
  langs:
  - csharp
  - vb
  name: MyList<KeyType>
  nameWithType: MyList<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>
  type: Class
  source:
    id: MyList
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Settings\MyList.cs
    startLine: 6
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Settings
  summary: Represents a list that contains a pinned list and a latest list.
  example: []
  syntax:
    content: public class MyList<KeyType>
    typeParameters:
    - id: KeyType
      description: The type of the keys in the list.
    content.vb: Public Class MyList(Of KeyType)
  inheritance:
  - System.Object
  nameWithType.vb: MyList(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType)
  name.vb: MyList(Of KeyType)
- uid: Innova.Prism.Infrastructure.Settings.MyList`1.PinnedList
  commentId: P:Innova.Prism.Infrastructure.Settings.MyList`1.PinnedList
  id: PinnedList
  parent: Innova.Prism.Infrastructure.Settings.MyList`1
  langs:
  - csharp
  - vb
  name: PinnedList
  nameWithType: MyList<KeyType>.PinnedList
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>.PinnedList
  type: Property
  source:
    id: PinnedList
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Settings\MyList.cs
    startLine: 11
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Settings
  summary: Gets or sets the pinned list.
  example: []
  syntax:
    content: public MyQueue<KeyType> PinnedList { get; set; }
    parameters: []
    return:
      type: Innova.Prism.Infrastructure.Settings.MyQueue{{KeyType}}
    content.vb: Public Property PinnedList As MyQueue(Of KeyType)
  overload: Innova.Prism.Infrastructure.Settings.MyList`1.PinnedList*
  nameWithType.vb: MyList(Of KeyType).PinnedList
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType).PinnedList
- uid: Innova.Prism.Infrastructure.Settings.MyList`1.LatestList
  commentId: P:Innova.Prism.Infrastructure.Settings.MyList`1.LatestList
  id: LatestList
  parent: Innova.Prism.Infrastructure.Settings.MyList`1
  langs:
  - csharp
  - vb
  name: LatestList
  nameWithType: MyList<KeyType>.LatestList
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>.LatestList
  type: Property
  source:
    id: LatestList
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Settings\MyList.cs
    startLine: 16
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Settings
  summary: Gets or sets the latest list.
  example: []
  syntax:
    content: public MyLatestList<KeyType> LatestList { get; set; }
    parameters: []
    return:
      type: Innova.Prism.Infrastructure.Settings.MyLatestList{{KeyType}}
    content.vb: Public Property LatestList As MyLatestList(Of KeyType)
  overload: Innova.Prism.Infrastructure.Settings.MyList`1.LatestList*
  nameWithType.vb: MyList(Of KeyType).LatestList
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType).LatestList
- uid: Innova.Prism.Infrastructure.Settings.MyList`1.#ctor
  commentId: M:Innova.Prism.Infrastructure.Settings.MyList`1.#ctor
  id: '#ctor'
  parent: Innova.Prism.Infrastructure.Settings.MyList`1
  langs:
  - csharp
  - vb
  name: MyList()
  nameWithType: MyList<KeyType>.MyList()
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>.MyList()
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Infrastructure\Settings\MyList.cs
    startLine: 21
  assemblies:
  - Innova.Prism.Infrastructure
  namespace: Innova.Prism.Infrastructure.Settings
  summary: Initializes a new instance of the <xref href="Innova.Prism.Infrastructure.Settings.MyList%601" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public MyList()
    content.vb: Public Sub New()
  overload: Innova.Prism.Infrastructure.Settings.MyList`1.#ctor*
  nameWithType.vb: MyList(Of KeyType).New()
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType).New()
  name.vb: New()
references:
- uid: Innova.Prism.Infrastructure.Settings
  commentId: N:Innova.Prism.Infrastructure.Settings
  href: Innova.html
  name: Innova.Prism.Infrastructure.Settings
  nameWithType: Innova.Prism.Infrastructure.Settings
  fullName: Innova.Prism.Infrastructure.Settings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Infrastructure
    name: Infrastructure
    href: Innova.Prism.Infrastructure.html
  - name: .
  - uid: Innova.Prism.Infrastructure.Settings
    name: Settings
    href: Innova.Prism.Infrastructure.Settings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Infrastructure
    name: Infrastructure
    href: Innova.Prism.Infrastructure.html
  - name: .
  - uid: Innova.Prism.Infrastructure.Settings
    name: Settings
    href: Innova.Prism.Infrastructure.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Prism.Infrastructure.Settings.MyList`1.PinnedList*
  commentId: Overload:Innova.Prism.Infrastructure.Settings.MyList`1.PinnedList
  href: Innova.Prism.Infrastructure.Settings.MyList-1.PinnedList.html#Innova_Prism_Infrastructure_Settings_MyList_1_PinnedList
  name: PinnedList
  nameWithType: MyList<KeyType>.PinnedList
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>.PinnedList
  nameWithType.vb: MyList(Of KeyType).PinnedList
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType).PinnedList
- uid: Innova.Prism.Infrastructure.Settings.MyQueue{{KeyType}}
  commentId: T:Innova.Prism.Infrastructure.Settings.MyQueue{`0}
  parent: Innova.Prism.Infrastructure.Settings
  definition: Innova.Prism.Infrastructure.Settings.MyQueue`1
  href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  name: MyQueue<KeyType>
  nameWithType: MyQueue<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyQueue<KeyType>
  nameWithType.vb: MyQueue(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyQueue(Of KeyType)
  name.vb: MyQueue(Of KeyType)
  spec.csharp:
  - uid: Innova.Prism.Infrastructure.Settings.MyQueue`1
    name: MyQueue
    href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Prism.Infrastructure.Settings.MyQueue`1
    name: MyQueue
    href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Prism.Infrastructure.Settings.MyQueue`1
  commentId: T:Innova.Prism.Infrastructure.Settings.MyQueue`1
  href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  name: MyQueue<KeyType>
  nameWithType: MyQueue<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyQueue<KeyType>
  nameWithType.vb: MyQueue(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyQueue(Of KeyType)
  name.vb: MyQueue(Of KeyType)
  spec.csharp:
  - uid: Innova.Prism.Infrastructure.Settings.MyQueue`1
    name: MyQueue
    href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Prism.Infrastructure.Settings.MyQueue`1
    name: MyQueue
    href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Prism.Infrastructure.Settings.MyList`1.LatestList*
  commentId: Overload:Innova.Prism.Infrastructure.Settings.MyList`1.LatestList
  href: Innova.Prism.Infrastructure.Settings.MyList-1.LatestList.html#Innova_Prism_Infrastructure_Settings_MyList_1_LatestList
  name: LatestList
  nameWithType: MyList<KeyType>.LatestList
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>.LatestList
  nameWithType.vb: MyList(Of KeyType).LatestList
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType).LatestList
- uid: Innova.Prism.Infrastructure.Settings.MyLatestList{{KeyType}}
  commentId: T:Innova.Prism.Infrastructure.Settings.MyLatestList{`0}
  parent: Innova.Prism.Infrastructure.Settings
  definition: Innova.Prism.Infrastructure.Settings.MyLatestList`1
  href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  name: MyLatestList<KeyType>
  nameWithType: MyLatestList<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyLatestList<KeyType>
  nameWithType.vb: MyLatestList(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyLatestList(Of KeyType)
  name.vb: MyLatestList(Of KeyType)
  spec.csharp:
  - uid: Innova.Prism.Infrastructure.Settings.MyLatestList`1
    name: MyLatestList
    href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Prism.Infrastructure.Settings.MyLatestList`1
    name: MyLatestList
    href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Prism.Infrastructure.Settings.MyLatestList`1
  commentId: T:Innova.Prism.Infrastructure.Settings.MyLatestList`1
  href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  name: MyLatestList<KeyType>
  nameWithType: MyLatestList<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyLatestList<KeyType>
  nameWithType.vb: MyLatestList(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyLatestList(Of KeyType)
  name.vb: MyLatestList(Of KeyType)
  spec.csharp:
  - uid: Innova.Prism.Infrastructure.Settings.MyLatestList`1
    name: MyLatestList
    href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Prism.Infrastructure.Settings.MyLatestList`1
    name: MyLatestList
    href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Prism.Infrastructure.Settings.MyList`1
  commentId: T:Innova.Prism.Infrastructure.Settings.MyList`1
  href: Innova.Prism.Infrastructure.Settings.MyList-1.html
  name: MyList<KeyType>
  nameWithType: MyList<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>
  nameWithType.vb: MyList(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType)
  name.vb: MyList(Of KeyType)
  spec.csharp:
  - uid: Innova.Prism.Infrastructure.Settings.MyList`1
    name: MyList
    href: Innova.Prism.Infrastructure.Settings.MyList-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Prism.Infrastructure.Settings.MyList`1
    name: MyList
    href: Innova.Prism.Infrastructure.Settings.MyList-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Prism.Infrastructure.Settings.MyList`1.#ctor*
  commentId: Overload:Innova.Prism.Infrastructure.Settings.MyList`1.#ctor
  href: Innova.Prism.Infrastructure.Settings.MyList-1.-ctor.html#Innova_Prism_Infrastructure_Settings_MyList_1__ctor
  name: MyList
  nameWithType: MyList<KeyType>.MyList
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>.MyList
  nameWithType.vb: MyList(Of KeyType).New
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType).New
  name.vb: New
memberLayout: SeparatePages
