### YamlMime:ManagedReference
items:
- uid: Innova.Data.Revision.RevisionItemTypeConfiguration
  commentId: T:Innova.Data.Revision.RevisionItemTypeConfiguration
  id: RevisionItemTypeConfiguration
  parent: Innova.Data.Revision
  children:
  - Innova.Data.Revision.RevisionItemTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
  langs:
  - csharp
  - vb
  name: RevisionItemTypeConfiguration
  nameWithType: RevisionItemTypeConfiguration
  fullName: Innova.Data.Revision.RevisionItemTypeConfiguration
  type: Class
  source:
    id: RevisionItemTypeConfiguration
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Revision\RevisionDbContextTypeConfigurations.cs
    startLine: 9
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Revision
  summary: Represents the configuration for the <xref href="Innova.Data.Revision.RevisionItem" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: 'public class RevisionItemTypeConfiguration : IEntityTypeConfiguration<RevisionItem>'
    content.vb: Public Class RevisionItemTypeConfiguration Implements IEntityTypeConfiguration(Of RevisionItem)
  inheritance:
  - System.Object
  implements:
  - Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}
- uid: Innova.Data.Revision.RevisionItemTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
  commentId: M:Innova.Data.Revision.RevisionItemTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
  id: Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
  parent: Innova.Data.Revision.RevisionItemTypeConfiguration
  langs:
  - csharp
  - vb
  name: Configure(EntityTypeBuilder<RevisionItem>)
  nameWithType: RevisionItemTypeConfiguration.Configure(EntityTypeBuilder<RevisionItem>)
  fullName: Innova.Data.Revision.RevisionItemTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.Revision.RevisionItem>)
  type: Method
  source:
    id: Configure
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Revision\RevisionDbContextTypeConfigurations.cs
    startLine: 15
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Revision
  summary: Configures the <xref href="Innova.Data.Revision.RevisionItem" data-throw-if-not-resolved="false"></xref> entity.
  example: []
  syntax:
    content: public void Configure(EntityTypeBuilder<RevisionItem> builder)
    parameters:
    - id: builder
      type: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem}
      description: The entity type builder used to configure the entity.
    content.vb: Public Sub Configure(builder As EntityTypeBuilder(Of RevisionItem))
  overload: Innova.Data.Revision.RevisionItemTypeConfiguration.Configure*
  implements:
  - Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
  nameWithType.vb: RevisionItemTypeConfiguration.Configure(EntityTypeBuilder(Of RevisionItem))
  fullName.vb: Innova.Data.Revision.RevisionItemTypeConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.Revision.RevisionItem))
  name.vb: Configure(EntityTypeBuilder(Of RevisionItem))
references:
- uid: Innova.Data.Revision.RevisionItem
  commentId: T:Innova.Data.Revision.RevisionItem
  href: Innova.Data.Revision.RevisionItem.html
  name: RevisionItem
  nameWithType: RevisionItem
  fullName: Innova.Data.Revision.RevisionItem
- uid: Innova.Data.Revision
  commentId: N:Innova.Data.Revision
  href: Innova.html
  name: Innova.Data.Revision
  nameWithType: Innova.Data.Revision
  fullName: Innova.Data.Revision
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Revision
    name: Revision
    href: Innova.Data.Revision.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Revision
    name: Revision
    href: Innova.Data.Revision.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}
  commentId: T:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}
  parent: Microsoft.EntityFrameworkCore
  definition: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  name: IEntityTypeConfiguration<RevisionItem>
  nameWithType: IEntityTypeConfiguration<RevisionItem>
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Innova.Data.Revision.RevisionItem>
  nameWithType.vb: IEntityTypeConfiguration(Of RevisionItem)
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of Innova.Data.Revision.RevisionItem)
  name.vb: IEntityTypeConfiguration(Of RevisionItem)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: <
  - uid: Innova.Data.Revision.RevisionItem
    name: RevisionItem
    href: Innova.Data.Revision.RevisionItem.html
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.Revision.RevisionItem
    name: RevisionItem
    href: Innova.Data.Revision.RevisionItem.html
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  commentId: T:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  name: IEntityTypeConfiguration<TEntity>
  nameWithType: IEntityTypeConfiguration<TEntity>
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<TEntity>
  nameWithType.vb: IEntityTypeConfiguration(Of TEntity)
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of TEntity)
  name.vb: IEntityTypeConfiguration(Of TEntity)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1
    name: IEntityTypeConfiguration
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
- uid: Microsoft.EntityFrameworkCore
  commentId: N:Microsoft.EntityFrameworkCore
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.EntityFrameworkCore
  nameWithType: Microsoft.EntityFrameworkCore
  fullName: Microsoft.EntityFrameworkCore
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
- uid: Innova.Data.Revision.RevisionItemTypeConfiguration.Configure*
  commentId: Overload:Innova.Data.Revision.RevisionItemTypeConfiguration.Configure
  href: Innova.Data.Revision.RevisionItemTypeConfiguration.Configure.html#Innova_Data_Revision_RevisionItemTypeConfiguration_Configure_Microsoft_EntityFrameworkCore_Metadata_Builders_EntityTypeBuilder_Innova_Data_Revision_RevisionItem__
  name: Configure
  nameWithType: RevisionItemTypeConfiguration.Configure
  fullName: Innova.Data.Revision.RevisionItemTypeConfiguration.Configure
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
  commentId: M:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
  parent: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}
  definition: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  name: Configure(EntityTypeBuilder<RevisionItem>)
  nameWithType: IEntityTypeConfiguration<RevisionItem>.Configure(EntityTypeBuilder<RevisionItem>)
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<Innova.Data.Revision.RevisionItem>.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.Revision.RevisionItem>)
  nameWithType.vb: IEntityTypeConfiguration(Of RevisionItem).Configure(EntityTypeBuilder(Of RevisionItem))
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of Innova.Data.Revision.RevisionItem).Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.Revision.RevisionItem))
  name.vb: Configure(EntityTypeBuilder(Of RevisionItem))
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - uid: Innova.Data.Revision.RevisionItem
    name: RevisionItem
    href: Innova.Data.Revision.RevisionItem.html
  - name: '>'
  - name: )
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration{Innova.Data.Revision.RevisionItem}.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.Revision.RevisionItem
    name: RevisionItem
    href: Innova.Data.Revision.RevisionItem.html
  - name: )
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem}
  commentId: T:Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Innova.Data.Revision.RevisionItem}
  parent: Microsoft.EntityFrameworkCore.Metadata.Builders
  definition: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  name: EntityTypeBuilder<RevisionItem>
  nameWithType: EntityTypeBuilder<RevisionItem>
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Innova.Data.Revision.RevisionItem>
  nameWithType.vb: EntityTypeBuilder(Of RevisionItem)
  fullName.vb: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of Innova.Data.Revision.RevisionItem)
  name.vb: EntityTypeBuilder(Of RevisionItem)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - uid: Innova.Data.Revision.RevisionItem
    name: RevisionItem
    href: Innova.Data.Revision.RevisionItem.html
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - uid: Innova.Data.Revision.RevisionItem
    name: RevisionItem
    href: Innova.Data.Revision.RevisionItem.html
  - name: )
- uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  commentId: M:Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  name: Configure(EntityTypeBuilder<TEntity>)
  nameWithType: IEntityTypeConfiguration<TEntity>.Configure(EntityTypeBuilder<TEntity>)
  fullName: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration<TEntity>.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>)
  nameWithType.vb: IEntityTypeConfiguration(Of TEntity).Configure(EntityTypeBuilder(Of TEntity))
  fullName.vb: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration(Of TEntity).Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity))
  name.vb: Configure(EntityTypeBuilder(Of TEntity))
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - name: TEntity
  - name: '>'
  - name: )
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.IEntityTypeConfiguration`1.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{`0})
    name: Configure
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1.configure
  - name: (
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  commentId: T:Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  name: EntityTypeBuilder<TEntity>
  nameWithType: EntityTypeBuilder<TEntity>
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<TEntity>
  nameWithType.vb: EntityTypeBuilder(Of TEntity)
  fullName.vb: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder(Of TEntity)
  name.vb: EntityTypeBuilder(Of TEntity)
  spec.csharp:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: <
  - name: TEntity
  - name: '>'
  spec.vb:
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1
    name: EntityTypeBuilder
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders.entitytypebuilder-1
  - name: (
  - name: Of
  - name: " "
  - name: TEntity
  - name: )
- uid: Microsoft.EntityFrameworkCore.Metadata.Builders
  commentId: N:Microsoft.EntityFrameworkCore.Metadata.Builders
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.EntityFrameworkCore.Metadata.Builders
  nameWithType: Microsoft.EntityFrameworkCore.Metadata.Builders
  fullName: Microsoft.EntityFrameworkCore.Metadata.Builders
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata
    name: Metadata
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders
    name: Builders
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata
    name: Metadata
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata
  - name: .
  - uid: Microsoft.EntityFrameworkCore.Metadata.Builders
    name: Builders
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.metadata.builders
memberLayout: SeparatePages
