### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Infrastructure.Settings
  commentId: N:Innova.Prism.Infrastructure.Settings
  id: Settings
  parent: Innova.Prism.Infrastructure
  children:
  - Innova.Prism.Infrastructure.Settings.MyLatestList`1
  - Innova.Prism.Infrastructure.Settings.MyList`1
  - Innova.Prism.Infrastructure.Settings.MyQueue`1
  langs:
  - csharp
  - vb
  name: Innova.Prism.Infrastructure.Settings
  nameWithType: Innova.Prism.Infrastructure.Settings
  fullName: Innova.Prism.Infrastructure.Settings
  type: Namespace
  assemblies:
  - Innova.Prism.Infrastructure
references:
- uid: Innova.Prism.Infrastructure.Settings.MyLatestList`1
  commentId: T:Innova.Prism.Infrastructure.Settings.MyLatestList`1
  href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  name: MyLatestList<KeyType>
  nameWithType: MyLatestList<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyLatestList<KeyType>
  nameWithType.vb: MyLatestList(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyLatestList(Of KeyType)
  name.vb: MyLatestList(Of KeyType)
  spec.csharp:
  - uid: Innova.Prism.Infrastructure.Settings.MyLatestList`1
    name: MyLatestList
    href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Prism.Infrastructure.Settings.MyLatestList`1
    name: MyLatestList
    href: Innova.Prism.Infrastructure.Settings.MyLatestList-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Prism.Infrastructure.Settings.MyList`1
  commentId: T:Innova.Prism.Infrastructure.Settings.MyList`1
  href: Innova.Prism.Infrastructure.Settings.MyList-1.html
  name: MyList<KeyType>
  nameWithType: MyList<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyList<KeyType>
  nameWithType.vb: MyList(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyList(Of KeyType)
  name.vb: MyList(Of KeyType)
  spec.csharp:
  - uid: Innova.Prism.Infrastructure.Settings.MyList`1
    name: MyList
    href: Innova.Prism.Infrastructure.Settings.MyList-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Prism.Infrastructure.Settings.MyList`1
    name: MyList
    href: Innova.Prism.Infrastructure.Settings.MyList-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
- uid: Innova.Prism.Infrastructure.Settings.MyQueue`1
  commentId: T:Innova.Prism.Infrastructure.Settings.MyQueue`1
  href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  name: MyQueue<KeyType>
  nameWithType: MyQueue<KeyType>
  fullName: Innova.Prism.Infrastructure.Settings.MyQueue<KeyType>
  nameWithType.vb: MyQueue(Of KeyType)
  fullName.vb: Innova.Prism.Infrastructure.Settings.MyQueue(Of KeyType)
  name.vb: MyQueue(Of KeyType)
  spec.csharp:
  - uid: Innova.Prism.Infrastructure.Settings.MyQueue`1
    name: MyQueue
    href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  - name: <
  - name: KeyType
  - name: '>'
  spec.vb:
  - uid: Innova.Prism.Infrastructure.Settings.MyQueue`1
    name: MyQueue
    href: Innova.Prism.Infrastructure.Settings.MyQueue-1.html
  - name: (
  - name: Of
  - name: " "
  - name: KeyType
  - name: )
memberLayout: SeparatePages
