### YamlMime:ManagedReference
items:
- uid: Innova.Prism.Library.Configuration.UI.UiGroup
  commentId: T:Innova.Prism.Library.Configuration.UI.UiGroup
  id: UiGroup
  parent: Innova.Prism.Library.Configuration.UI
  children: []
  langs:
  - csharp
  - vb
  name: UiGroup
  nameWithType: UiGroup
  fullName: Innova.Prism.Library.Configuration.UI.UiGroup
  type: Class
  source:
    id: UiGroup
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Prism.Library\Configuration\UI\UiGroup.cs
    startLine: 11
  assemblies:
  - Innova.Prism.Library
  namespace: Innova.Prism.Library.Configuration.UI
  summary: Represents a UI group.
  example: []
  syntax:
    content: 'public class UiGroup : UiBase'
    content.vb: Public Class UiGroup Inherits UiBase
  inheritance:
  - System.Object
  - Innova.Prism.Library.Configuration.UI.UiBase
  inheritedMembers:
  - Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  - Innova.Prism.Library.Configuration.UI.UiBase.Name
references:
- uid: Innova.Prism.Library.Configuration.UI
  commentId: N:Innova.Prism.Library.Configuration.UI
  href: Innova.html
  name: Innova.Prism.Library.Configuration.UI
  nameWithType: Innova.Prism.Library.Configuration.UI
  fullName: Innova.Prism.Library.Configuration.UI
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Prism
    name: Prism
    href: Innova.Prism.html
  - name: .
  - uid: Innova.Prism.Library
    name: Library
    href: Innova.Prism.Library.html
  - name: .
  - uid: Innova.Prism.Library.Configuration
    name: Configuration
    href: Innova.Prism.Library.Configuration.html
  - name: .
  - uid: Innova.Prism.Library.Configuration.UI
    name: UI
    href: Innova.Prism.Library.Configuration.UI.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Innova.Prism.Library.Configuration.UI.UiBase
  commentId: T:Innova.Prism.Library.Configuration.UI.UiBase
  parent: Innova.Prism.Library.Configuration.UI
  href: Innova.Prism.Library.Configuration.UI.UiBase.html
  name: UiBase
  nameWithType: UiBase
  fullName: Innova.Prism.Library.Configuration.UI.UiBase
- uid: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  commentId: P:Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
  parent: Innova.Prism.Library.Configuration.UI.UiBase
  href: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible.html#Innova_Prism_Library_Configuration_UI_UiBase_IsVisible
  name: IsVisible
  nameWithType: UiBase.IsVisible
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.IsVisible
- uid: Innova.Prism.Library.Configuration.UI.UiBase.Name
  commentId: P:Innova.Prism.Library.Configuration.UI.UiBase.Name
  parent: Innova.Prism.Library.Configuration.UI.UiBase
  href: Innova.Prism.Library.Configuration.UI.UiBase.Name.html#Innova_Prism_Library_Configuration_UI_UiBase_Name
  name: Name
  nameWithType: UiBase.Name
  fullName: Innova.Prism.Library.Configuration.UI.UiBase.Name
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
memberLayout: SeparatePages
