### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.Layout
  commentId: T:Innova.Data.AppSettings.Layout
  id: Layout
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.Layout.LayoutName
  - Innova.Data.AppSettings.Layout.LayoutString
  langs:
  - csharp
  - vb
  name: Layout
  nameWithType: Layout
  fullName: Innova.Data.AppSettings.Layout
  type: Class
  source:
    id: Layout
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Layout.cs
    startLine: 8
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents the layout settings.
  example: []
  syntax:
    content: >-
      [Serializable]

      public class Layout
    content.vb: >-
      <Serializable>

      Public Class Layout
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Innova.Data.AppSettings.Layout.LayoutString
  commentId: P:Innova.Data.AppSettings.Layout.LayoutString
  id: LayoutString
  parent: Innova.Data.AppSettings.Layout
  langs:
  - csharp
  - vb
  name: LayoutString
  nameWithType: Layout.LayoutString
  fullName: Innova.Data.AppSettings.Layout.LayoutString
  type: Property
  source:
    id: LayoutString
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Layout.cs
    startLine: 14
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the layout string.
  example: []
  syntax:
    content: public string LayoutString { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LayoutString As String
  overload: Innova.Data.AppSettings.Layout.LayoutString*
- uid: Innova.Data.AppSettings.Layout.LayoutName
  commentId: P:Innova.Data.AppSettings.Layout.LayoutName
  id: LayoutName
  parent: Innova.Data.AppSettings.Layout
  langs:
  - csharp
  - vb
  name: LayoutName
  nameWithType: Layout.LayoutName
  fullName: Innova.Data.AppSettings.Layout.LayoutName
  type: Property
  source:
    id: LayoutName
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Layout.cs
    startLine: 19
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets or sets the layout name.
  example: []
  syntax:
    content: public string LayoutName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LayoutName As String
  overload: Innova.Data.AppSettings.Layout.LayoutName*
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.Layout.LayoutString*
  commentId: Overload:Innova.Data.AppSettings.Layout.LayoutString
  href: Innova.Data.AppSettings.Layout.LayoutString.html#Innova_Data_AppSettings_Layout_LayoutString
  name: LayoutString
  nameWithType: Layout.LayoutString
  fullName: Innova.Data.AppSettings.Layout.LayoutString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Data.AppSettings.Layout.LayoutName*
  commentId: Overload:Innova.Data.AppSettings.Layout.LayoutName
  href: Innova.Data.AppSettings.Layout.LayoutName.html#Innova_Data_AppSettings_Layout_LayoutName
  name: LayoutName
  nameWithType: Layout.LayoutName
  fullName: Innova.Data.AppSettings.Layout.LayoutName
memberLayout: SeparatePages
