### YamlMime:ManagedReference
items:
- uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
  commentId: T:Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
  id: IEntityRevisionServiceConfiguration`1
  parent: Innova.Data.Revision
  children:
  - Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead
  langs:
  - csharp
  - vb
  name: IEntityRevisionServiceConfiguration<T>
  nameWithType: IEntityRevisionServiceConfiguration<T>
  fullName: Innova.Data.Revision.IEntityRevisionServiceConfiguration<T>
  type: Interface
  source:
    id: IEntityRevisionServiceConfiguration
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Revision\IEntityRevisionServiceConfiguration.cs
    startLine: 6
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Revision
  summary: Represents the configuration for the entity revision service.
  example: []
  syntax:
    content: 'public interface IEntityRevisionServiceConfiguration<T> where T : class'
    typeParameters:
    - id: T
      description: The type of the entity.
    content.vb: Public Interface IEntityRevisionServiceConfiguration(Of T As Class)
  nameWithType.vb: IEntityRevisionServiceConfiguration(Of T)
  fullName.vb: Innova.Data.Revision.IEntityRevisionServiceConfiguration(Of T)
  name.vb: IEntityRevisionServiceConfiguration(Of T)
- uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead
  commentId: P:Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead
  id: ImplementRead
  parent: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1
  langs:
  - csharp
  - vb
  name: ImplementRead
  nameWithType: IEntityRevisionServiceConfiguration<T>.ImplementRead
  fullName: Innova.Data.Revision.IEntityRevisionServiceConfiguration<T>.ImplementRead
  type: Property
  source:
    id: ImplementRead
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Revision\IEntityRevisionServiceConfiguration.cs
    startLine: 11
  assemblies:
  - Innova.Data
  namespace: Innova.Data.Revision
  summary: Gets or sets a value indicating whether to implement read functionality.
  example: []
  syntax:
    content: bool ImplementRead { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property ImplementRead As Boolean
  overload: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead*
  nameWithType.vb: IEntityRevisionServiceConfiguration(Of T).ImplementRead
  fullName.vb: Innova.Data.Revision.IEntityRevisionServiceConfiguration(Of T).ImplementRead
references:
- uid: Innova.Data.Revision
  commentId: N:Innova.Data.Revision
  href: Innova.html
  name: Innova.Data.Revision
  nameWithType: Innova.Data.Revision
  fullName: Innova.Data.Revision
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Revision
    name: Revision
    href: Innova.Data.Revision.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.Revision
    name: Revision
    href: Innova.Data.Revision.html
- uid: Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead*
  commentId: Overload:Innova.Data.Revision.IEntityRevisionServiceConfiguration`1.ImplementRead
  href: Innova.Data.Revision.IEntityRevisionServiceConfiguration-1.ImplementRead.html#Innova_Data_Revision_IEntityRevisionServiceConfiguration_1_ImplementRead
  name: ImplementRead
  nameWithType: IEntityRevisionServiceConfiguration<T>.ImplementRead
  fullName: Innova.Data.Revision.IEntityRevisionServiceConfiguration<T>.ImplementRead
  nameWithType.vb: IEntityRevisionServiceConfiguration(Of T).ImplementRead
  fullName.vb: Innova.Data.Revision.IEntityRevisionServiceConfiguration(Of T).ImplementRead
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
memberLayout: SeparatePages
