### YamlMime:ManagedReference
items:
- uid: Innova.Data.IInnovaApplicationBuilderBaseExtensions
  commentId: T:Innova.Data.IInnovaApplicationBuilderBaseExtensions
  id: IInnovaApplicationBuilderBaseExtensions
  parent: Innova.Data
  children:
  - Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  - Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  langs:
  - csharp
  - vb
  name: IInnovaApplicationBuilderBaseExtensions
  nameWithType: IInnovaApplicationBuilderBaseExtensions
  fullName: Innova.Data.IInnovaApplicationBuilderBaseExtensions
  type: Class
  source:
    id: IInnovaApplicationBuilderBaseExtensions
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Abstractions\Builder\IInnovaApplicationBuilderBaseExtensions.cs
    startLine: 8
  assemblies:
  - Innova.Data
  namespace: Innova.Data
  summary: Provides extension methods for the IInnovaApplicationBuilderBase interface.
  example: []
  syntax:
    content: public static class IInnovaApplicationBuilderBaseExtensions
    content.vb: Public Module IInnovaApplicationBuilderBaseExtensions
  inheritance:
  - System.Object
- uid: Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  commentId: M:Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  id: IsUsingSql(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  isExtensionMethod: true
  parent: Innova.Data.IInnovaApplicationBuilderBaseExtensions
  langs:
  - csharp
  - vb
  name: IsUsingSql(IInnovaApplicationBuilderBase)
  nameWithType: IInnovaApplicationBuilderBaseExtensions.IsUsingSql(IInnovaApplicationBuilderBase)
  fullName: Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase)
  type: Method
  source:
    id: IsUsingSql
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Abstractions\Builder\IInnovaApplicationBuilderBaseExtensions.cs
    startLine: 15
  assemblies:
  - Innova.Data
  namespace: Innova.Data
  summary: Determines whether the application is using SQL based on the connection settings.
  example: []
  syntax:
    content: public static bool IsUsingSql(this IInnovaApplicationBuilderBase app)
    parameters:
    - id: app
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The application builder.
    return:
      type: System.Boolean
      description: true if the application is using SQL; otherwise, false.
    content.vb: Public Shared Function IsUsingSql(app As IInnovaApplicationBuilderBase) As Boolean
  overload: Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql*
- uid: Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  commentId: M:Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  id: SetApplicationCulture(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase,System.String)
  isExtensionMethod: true
  parent: Innova.Data.IInnovaApplicationBuilderBaseExtensions
  langs:
  - csharp
  - vb
  name: SetApplicationCulture(IInnovaApplicationBuilderBase, string)
  nameWithType: IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture(IInnovaApplicationBuilderBase, string)
  fullName: Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase, string)
  type: Method
  source:
    id: SetApplicationCulture
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\Abstractions\Builder\IInnovaApplicationBuilderBaseExtensions.cs
    startLine: 26
  assemblies:
  - Innova.Data
  namespace: Innova.Data
  summary: Sets the application culture.
  example: []
  syntax:
    content: public static IInnovaApplicationBuilderBase SetApplicationCulture(this IInnovaApplicationBuilderBase app, string culture)
    parameters:
    - id: app
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The application builder.
    - id: culture
      type: System.String
      description: The culture to set.
    return:
      type: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
      description: The updated application builder.
    content.vb: Public Shared Function SetApplicationCulture(app As IInnovaApplicationBuilderBase, culture As String) As IInnovaApplicationBuilderBase
  overload: Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture*
  nameWithType.vb: IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture(IInnovaApplicationBuilderBase, String)
  fullName.vb: Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture(Innova.Abstractions.Builder.IInnovaApplicationBuilderBase, String)
  name.vb: SetApplicationCulture(IInnovaApplicationBuilderBase, String)
references:
- uid: Innova.Data
  commentId: N:Innova.Data
  href: Innova.html
  name: Innova.Data
  nameWithType: Innova.Data
  fullName: Innova.Data
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql*
  commentId: Overload:Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql
  href: Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql.html#Innova_Data_IInnovaApplicationBuilderBaseExtensions_IsUsingSql_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_
  name: IsUsingSql
  nameWithType: IInnovaApplicationBuilderBaseExtensions.IsUsingSql
  fullName: Innova.Data.IInnovaApplicationBuilderBaseExtensions.IsUsingSql
- uid: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  commentId: T:Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
  parent: Innova.Abstractions.Builder
  href: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase.html
  name: IInnovaApplicationBuilderBase
  nameWithType: IInnovaApplicationBuilderBase
  fullName: Innova.Abstractions.Builder.IInnovaApplicationBuilderBase
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Innova.Abstractions.Builder
  commentId: N:Innova.Abstractions.Builder
  href: Innova.html
  name: Innova.Abstractions.Builder
  nameWithType: Innova.Abstractions.Builder
  fullName: Innova.Abstractions.Builder
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Abstractions
    name: Abstractions
    href: Innova.Abstractions.html
  - name: .
  - uid: Innova.Abstractions.Builder
    name: Builder
    href: Innova.Abstractions.Builder.html
- uid: Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture*
  commentId: Overload:Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture
  href: Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture.html#Innova_Data_IInnovaApplicationBuilderBaseExtensions_SetApplicationCulture_Innova_Abstractions_Builder_IInnovaApplicationBuilderBase_System_String_
  name: SetApplicationCulture
  nameWithType: IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture
  fullName: Innova.Data.IInnovaApplicationBuilderBaseExtensions.SetApplicationCulture
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
memberLayout: SeparatePages
