### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1
  commentId: T:Innova.Data.AppSettings.Services.BaseUserSetting`1
  id: BaseUserSetting`1
  parent: Innova.Data.AppSettings.Services
  children:
  - Innova.Data.AppSettings.Services.BaseUserSetting`1.#ctor(Innova.Data.AppSettings.IUserSettingService,System.String)
  - Innova.Data.AppSettings.Services.BaseUserSetting`1.LoadData
  - Innova.Data.AppSettings.Services.BaseUserSetting`1.Save
  - Innova.Data.AppSettings.Services.BaseUserSetting`1.Setting
  - Innova.Data.AppSettings.Services.BaseUserSetting`1.SettingKey
  - Innova.Data.AppSettings.Services.BaseUserSetting`1.userSettingService
  langs:
  - csharp
  - vb
  name: BaseUserSetting<T>
  nameWithType: BaseUserSetting<T>
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>
  type: Class
  source:
    id: BaseUserSetting
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseUserSetting.cs
    startLine: 12
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Represents a base class for user settings.
  example: []
  syntax:
    content: 'public abstract class BaseUserSetting<T> : IUserSettingServiceSave where T : class, new()'
    typeParameters:
    - id: T
      description: The type of the setting.
    content.vb: Public MustInherit Class BaseUserSetting(Of T As {Class, New}) Implements IUserSettingServiceSave
  inheritance:
  - System.Object
  derivedClasses:
  - Innova.Prism.Library.Services.PinnedListService`2
  implements:
  - Innova.Data.AppSettings.IUserSettingServiceSave
  nameWithType.vb: BaseUserSetting(Of T)
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T)
  name.vb: BaseUserSetting(Of T)
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.userSettingService
  commentId: F:Innova.Data.AppSettings.Services.BaseUserSetting`1.userSettingService
  id: userSettingService
  parent: Innova.Data.AppSettings.Services.BaseUserSetting`1
  langs:
  - csharp
  - vb
  name: userSettingService
  nameWithType: BaseUserSetting<T>.userSettingService
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.userSettingService
  type: Field
  source:
    id: userSettingService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseUserSetting.cs
    startLine: 17
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: The user setting service.
  example: []
  syntax:
    content: protected readonly IUserSettingService userSettingService
    return:
      type: Innova.Data.AppSettings.IUserSettingService
    content.vb: Protected ReadOnly userSettingService As IUserSettingService
  nameWithType.vb: BaseUserSetting(Of T).userSettingService
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).userSettingService
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.Setting
  commentId: P:Innova.Data.AppSettings.Services.BaseUserSetting`1.Setting
  id: Setting
  parent: Innova.Data.AppSettings.Services.BaseUserSetting`1
  langs:
  - csharp
  - vb
  name: Setting
  nameWithType: BaseUserSetting<T>.Setting
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.Setting
  type: Property
  source:
    id: Setting
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseUserSetting.cs
    startLine: 22
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Gets or sets the setting value.
  example: []
  syntax:
    content: public T Setting { get; set; }
    parameters: []
    return:
      type: '{T}'
    content.vb: Public Property Setting As T
  overload: Innova.Data.AppSettings.Services.BaseUserSetting`1.Setting*
  nameWithType.vb: BaseUserSetting(Of T).Setting
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).Setting
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.SettingKey
  commentId: P:Innova.Data.AppSettings.Services.BaseUserSetting`1.SettingKey
  id: SettingKey
  parent: Innova.Data.AppSettings.Services.BaseUserSetting`1
  langs:
  - csharp
  - vb
  name: SettingKey
  nameWithType: BaseUserSetting<T>.SettingKey
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.SettingKey
  type: Property
  source:
    id: SettingKey
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseUserSetting.cs
    startLine: 27
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Gets or sets the setting key.
  example: []
  syntax:
    content: protected string SettingKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Protected Property SettingKey As String
  overload: Innova.Data.AppSettings.Services.BaseUserSetting`1.SettingKey*
  nameWithType.vb: BaseUserSetting(Of T).SettingKey
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).SettingKey
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.#ctor(Innova.Data.AppSettings.IUserSettingService,System.String)
  commentId: M:Innova.Data.AppSettings.Services.BaseUserSetting`1.#ctor(Innova.Data.AppSettings.IUserSettingService,System.String)
  id: '#ctor(Innova.Data.AppSettings.IUserSettingService,System.String)'
  parent: Innova.Data.AppSettings.Services.BaseUserSetting`1
  langs:
  - csharp
  - vb
  name: BaseUserSetting(IUserSettingService, string)
  nameWithType: BaseUserSetting<T>.BaseUserSetting(IUserSettingService, string)
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.BaseUserSetting(Innova.Data.AppSettings.IUserSettingService, string)
  type: Constructor
  source:
    id: .ctor
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseUserSetting.cs
    startLine: 34
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Initializes a new instance of the <xref href="Innova.Data.AppSettings.Services.BaseUserSetting%601" data-throw-if-not-resolved="false"></xref> class.
  example: []
  syntax:
    content: public BaseUserSetting(IUserSettingService userSettingService, string settingKey)
    parameters:
    - id: userSettingService
      type: Innova.Data.AppSettings.IUserSettingService
      description: The user setting service.
    - id: settingKey
      type: System.String
      description: The setting key.
    content.vb: Public Sub New(userSettingService As IUserSettingService, settingKey As String)
  overload: Innova.Data.AppSettings.Services.BaseUserSetting`1.#ctor*
  nameWithType.vb: BaseUserSetting(Of T).New(IUserSettingService, String)
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).New(Innova.Data.AppSettings.IUserSettingService, String)
  name.vb: New(IUserSettingService, String)
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.LoadData
  commentId: M:Innova.Data.AppSettings.Services.BaseUserSetting`1.LoadData
  id: LoadData
  parent: Innova.Data.AppSettings.Services.BaseUserSetting`1
  langs:
  - csharp
  - vb
  name: LoadData()
  nameWithType: BaseUserSetting<T>.LoadData()
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.LoadData()
  type: Method
  source:
    id: LoadData
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseUserSetting.cs
    startLine: 44
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Loads the data for the user setting.
  example: []
  syntax:
    content: public Task LoadData()
    return:
      type: System.Threading.Tasks.Task
      description: A task representing the asynchronous operation.
    content.vb: Public Function LoadData() As Task
  overload: Innova.Data.AppSettings.Services.BaseUserSetting`1.LoadData*
  nameWithType.vb: BaseUserSetting(Of T).LoadData()
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).LoadData()
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.Save
  commentId: M:Innova.Data.AppSettings.Services.BaseUserSetting`1.Save
  id: Save
  parent: Innova.Data.AppSettings.Services.BaseUserSetting`1
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: BaseUserSetting<T>.Save()
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.Save()
  type: Method
  source:
    id: Save
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\BaseUserSetting.cs
    startLine: 58
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings.Services
  summary: Saves the user setting.
  example: []
  syntax:
    content: public Task Save()
    return:
      type: System.Threading.Tasks.Task
      description: A task representing the asynchronous operation.
    content.vb: Public Function Save() As Task
  overload: Innova.Data.AppSettings.Services.BaseUserSetting`1.Save*
  implements:
  - Innova.Data.AppSettings.IUserSettingServiceSave.Save
  nameWithType.vb: BaseUserSetting(Of T).Save()
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).Save()
references:
- uid: Innova.Data.AppSettings.Services
  commentId: N:Innova.Data.AppSettings.Services
  href: Innova.html
  name: Innova.Data.AppSettings.Services
  nameWithType: Innova.Data.AppSettings.Services
  fullName: Innova.Data.AppSettings.Services
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  - name: .
  - uid: Innova.Data.AppSettings.Services
    name: Services
    href: Innova.Data.AppSettings.Services.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Innova.Data.AppSettings.IUserSettingServiceSave
  commentId: T:Innova.Data.AppSettings.IUserSettingServiceSave
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.IUserSettingServiceSave.html
  name: IUserSettingServiceSave
  nameWithType: IUserSettingServiceSave
  fullName: Innova.Data.AppSettings.IUserSettingServiceSave
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Data.AppSettings.IUserSettingService
  commentId: T:Innova.Data.AppSettings.IUserSettingService
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.IUserSettingService.html
  name: IUserSettingService
  nameWithType: IUserSettingService
  fullName: Innova.Data.AppSettings.IUserSettingService
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.Setting*
  commentId: Overload:Innova.Data.AppSettings.Services.BaseUserSetting`1.Setting
  href: Innova.Data.AppSettings.Services.BaseUserSetting-1.Setting.html#Innova_Data_AppSettings_Services_BaseUserSetting_1_Setting
  name: Setting
  nameWithType: BaseUserSetting<T>.Setting
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.Setting
  nameWithType.vb: BaseUserSetting(Of T).Setting
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).Setting
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.SettingKey*
  commentId: Overload:Innova.Data.AppSettings.Services.BaseUserSetting`1.SettingKey
  href: Innova.Data.AppSettings.Services.BaseUserSetting-1.SettingKey.html#Innova_Data_AppSettings_Services_BaseUserSetting_1_SettingKey
  name: SettingKey
  nameWithType: BaseUserSetting<T>.SettingKey
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.SettingKey
  nameWithType.vb: BaseUserSetting(Of T).SettingKey
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).SettingKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1
  commentId: T:Innova.Data.AppSettings.Services.BaseUserSetting`1
  href: Innova.Data.AppSettings.Services.BaseUserSetting-1.html
  name: BaseUserSetting<T>
  nameWithType: BaseUserSetting<T>
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>
  nameWithType.vb: BaseUserSetting(Of T)
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T)
  name.vb: BaseUserSetting(Of T)
  spec.csharp:
  - uid: Innova.Data.AppSettings.Services.BaseUserSetting`1
    name: BaseUserSetting
    href: Innova.Data.AppSettings.Services.BaseUserSetting-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Data.AppSettings.Services.BaseUserSetting`1
    name: BaseUserSetting
    href: Innova.Data.AppSettings.Services.BaseUserSetting-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.#ctor*
  commentId: Overload:Innova.Data.AppSettings.Services.BaseUserSetting`1.#ctor
  href: Innova.Data.AppSettings.Services.BaseUserSetting-1.-ctor.html#Innova_Data_AppSettings_Services_BaseUserSetting_1__ctor_Innova_Data_AppSettings_IUserSettingService_System_String_
  name: BaseUserSetting
  nameWithType: BaseUserSetting<T>.BaseUserSetting
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.BaseUserSetting
  nameWithType.vb: BaseUserSetting(Of T).New
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).New
  name.vb: New
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.LoadData*
  commentId: Overload:Innova.Data.AppSettings.Services.BaseUserSetting`1.LoadData
  href: Innova.Data.AppSettings.Services.BaseUserSetting-1.LoadData.html#Innova_Data_AppSettings_Services_BaseUserSetting_1_LoadData
  name: LoadData
  nameWithType: BaseUserSetting<T>.LoadData
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.LoadData
  nameWithType.vb: BaseUserSetting(Of T).LoadData
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).LoadData
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Innova.Data.AppSettings.Services.BaseUserSetting`1.Save*
  commentId: Overload:Innova.Data.AppSettings.Services.BaseUserSetting`1.Save
  href: Innova.Data.AppSettings.Services.BaseUserSetting-1.Save.html#Innova_Data_AppSettings_Services_BaseUserSetting_1_Save
  name: Save
  nameWithType: BaseUserSetting<T>.Save
  fullName: Innova.Data.AppSettings.Services.BaseUserSetting<T>.Save
  nameWithType.vb: BaseUserSetting(Of T).Save
  fullName.vb: Innova.Data.AppSettings.Services.BaseUserSetting(Of T).Save
- uid: Innova.Data.AppSettings.IUserSettingServiceSave.Save
  commentId: M:Innova.Data.AppSettings.IUserSettingServiceSave.Save
  parent: Innova.Data.AppSettings.IUserSettingServiceSave
  href: Innova.Data.AppSettings.IUserSettingServiceSave.Save.html#Innova_Data_AppSettings_IUserSettingServiceSave_Save
  name: Save()
  nameWithType: IUserSettingServiceSave.Save()
  fullName: Innova.Data.AppSettings.IUserSettingServiceSave.Save()
  spec.csharp:
  - uid: Innova.Data.AppSettings.IUserSettingServiceSave.Save
    name: Save
    href: Innova.Data.AppSettings.IUserSettingServiceSave.Save.html#Innova_Data_AppSettings_IUserSettingServiceSave_Save
  - name: (
  - name: )
  spec.vb:
  - uid: Innova.Data.AppSettings.IUserSettingServiceSave.Save
    name: Save
    href: Innova.Data.AppSettings.IUserSettingServiceSave.Save.html#Innova_Data_AppSettings_IUserSettingServiceSave_Save
  - name: (
  - name: )
memberLayout: SeparatePages
