### YamlMime:ManagedReference
items:
- uid: Innova.Data.AppSettings.ISavedQueryService
  commentId: T:Innova.Data.AppSettings.ISavedQueryService
  id: ISavedQueryService
  parent: Innova.Data.AppSettings
  children:
  - Innova.Data.AppSettings.ISavedQueryService.Get(System.String,System.String)
  - Innova.Data.AppSettings.ISavedQueryService.GetDefault(System.String,System.String)
  - Innova.Data.AppSettings.ISavedQueryService.Save
  - Innova.Data.AppSettings.ISavedQueryService.SaveDefaults
  langs:
  - csharp
  - vb
  name: ISavedQueryService
  nameWithType: ISavedQueryService
  fullName: Innova.Data.AppSettings.ISavedQueryService
  type: Interface
  source:
    id: ISavedQueryService
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ISavedQueryService.cs
    startLine: 5
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Represents a service for managing saved queries.
  example: []
  syntax:
    content: public interface ISavedQueryService
    content.vb: Public Interface ISavedQueryService
- uid: Innova.Data.AppSettings.ISavedQueryService.Get(System.String,System.String)
  commentId: M:Innova.Data.AppSettings.ISavedQueryService.Get(System.String,System.String)
  id: Get(System.String,System.String)
  parent: Innova.Data.AppSettings.ISavedQueryService
  langs:
  - csharp
  - vb
  name: Get(string, string)
  nameWithType: ISavedQueryService.Get(string, string)
  fullName: Innova.Data.AppSettings.ISavedQueryService.Get(string, string)
  type: Method
  source:
    id: Get
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ISavedQueryService.cs
    startLine: 13
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the saved query of the specified type and key.
  example: []
  syntax:
    content: EntitySavedQueryType Get(string typeName, string key = null)
    parameters:
    - id: typeName
      type: System.String
      description: The type name of the saved query.
    - id: key
      type: System.String
      description: The key of the saved query (optional).
    return:
      type: Innova.Data.AppSettings.EntitySavedQueryType
      description: The saved query of the specified type and key.
    content.vb: Function [Get](typeName As String, key As String = Nothing) As EntitySavedQueryType
  overload: Innova.Data.AppSettings.ISavedQueryService.Get*
  nameWithType.vb: ISavedQueryService.Get(String, String)
  fullName.vb: Innova.Data.AppSettings.ISavedQueryService.Get(String, String)
  name.vb: Get(String, String)
- uid: Innova.Data.AppSettings.ISavedQueryService.GetDefault(System.String,System.String)
  commentId: M:Innova.Data.AppSettings.ISavedQueryService.GetDefault(System.String,System.String)
  id: GetDefault(System.String,System.String)
  parent: Innova.Data.AppSettings.ISavedQueryService
  langs:
  - csharp
  - vb
  name: GetDefault(string, string)
  nameWithType: ISavedQueryService.GetDefault(string, string)
  fullName: Innova.Data.AppSettings.ISavedQueryService.GetDefault(string, string)
  type: Method
  source:
    id: GetDefault
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ISavedQueryService.cs
    startLine: 21
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Gets the default saved query of the specified type and key.
  example: []
  syntax:
    content: EntitySavedQueryType GetDefault(string typeName, string key = null)
    parameters:
    - id: typeName
      type: System.String
      description: The type name of the saved query.
    - id: key
      type: System.String
      description: The key of the saved query (optional).
    return:
      type: Innova.Data.AppSettings.EntitySavedQueryType
      description: The default saved query of the specified type and key.
    content.vb: Function GetDefault(typeName As String, key As String = Nothing) As EntitySavedQueryType
  overload: Innova.Data.AppSettings.ISavedQueryService.GetDefault*
  nameWithType.vb: ISavedQueryService.GetDefault(String, String)
  fullName.vb: Innova.Data.AppSettings.ISavedQueryService.GetDefault(String, String)
  name.vb: GetDefault(String, String)
- uid: Innova.Data.AppSettings.ISavedQueryService.Save
  commentId: M:Innova.Data.AppSettings.ISavedQueryService.Save
  id: Save
  parent: Innova.Data.AppSettings.ISavedQueryService
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: ISavedQueryService.Save()
  fullName: Innova.Data.AppSettings.ISavedQueryService.Save()
  type: Method
  source:
    id: Save
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ISavedQueryService.cs
    startLine: 26
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Saves the changes made to the saved queries.
  example: []
  syntax:
    content: void Save()
    content.vb: Sub Save()
  overload: Innova.Data.AppSettings.ISavedQueryService.Save*
- uid: Innova.Data.AppSettings.ISavedQueryService.SaveDefaults
  commentId: M:Innova.Data.AppSettings.ISavedQueryService.SaveDefaults
  id: SaveDefaults
  parent: Innova.Data.AppSettings.ISavedQueryService
  langs:
  - csharp
  - vb
  name: SaveDefaults()
  nameWithType: ISavedQueryService.SaveDefaults()
  fullName: Innova.Data.AppSettings.ISavedQueryService.SaveDefaults()
  type: Method
  source:
    id: SaveDefaults
    path: C:\Source\Workspaces\Workspace\Innova Frameworks\IDP\src\Innova.Data\AppSettings\Services\ISavedQueryService.cs
    startLine: 31
  assemblies:
  - Innova.Data
  namespace: Innova.Data.AppSettings
  summary: Saves the default saved queries.
  example: []
  syntax:
    content: void SaveDefaults()
    content.vb: Sub SaveDefaults()
  overload: Innova.Data.AppSettings.ISavedQueryService.SaveDefaults*
references:
- uid: Innova.Data.AppSettings
  commentId: N:Innova.Data.AppSettings
  href: Innova.html
  name: Innova.Data.AppSettings
  nameWithType: Innova.Data.AppSettings
  fullName: Innova.Data.AppSettings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Data
    name: Data
    href: Innova.Data.html
  - name: .
  - uid: Innova.Data.AppSettings
    name: AppSettings
    href: Innova.Data.AppSettings.html
- uid: Innova.Data.AppSettings.ISavedQueryService.Get*
  commentId: Overload:Innova.Data.AppSettings.ISavedQueryService.Get
  href: Innova.Data.AppSettings.ISavedQueryService.Get.html#Innova_Data_AppSettings_ISavedQueryService_Get_System_String_System_String_
  name: Get
  nameWithType: ISavedQueryService.Get
  fullName: Innova.Data.AppSettings.ISavedQueryService.Get
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Innova.Data.AppSettings.EntitySavedQueryType
  commentId: T:Innova.Data.AppSettings.EntitySavedQueryType
  parent: Innova.Data.AppSettings
  href: Innova.Data.AppSettings.EntitySavedQueryType.html
  name: EntitySavedQueryType
  nameWithType: EntitySavedQueryType
  fullName: Innova.Data.AppSettings.EntitySavedQueryType
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Innova.Data.AppSettings.ISavedQueryService.GetDefault*
  commentId: Overload:Innova.Data.AppSettings.ISavedQueryService.GetDefault
  href: Innova.Data.AppSettings.ISavedQueryService.GetDefault.html#Innova_Data_AppSettings_ISavedQueryService_GetDefault_System_String_System_String_
  name: GetDefault
  nameWithType: ISavedQueryService.GetDefault
  fullName: Innova.Data.AppSettings.ISavedQueryService.GetDefault
- uid: Innova.Data.AppSettings.ISavedQueryService.Save*
  commentId: Overload:Innova.Data.AppSettings.ISavedQueryService.Save
  href: Innova.Data.AppSettings.ISavedQueryService.Save.html#Innova_Data_AppSettings_ISavedQueryService_Save
  name: Save
  nameWithType: ISavedQueryService.Save
  fullName: Innova.Data.AppSettings.ISavedQueryService.Save
- uid: Innova.Data.AppSettings.ISavedQueryService.SaveDefaults*
  commentId: Overload:Innova.Data.AppSettings.ISavedQueryService.SaveDefaults
  href: Innova.Data.AppSettings.ISavedQueryService.SaveDefaults.html#Innova_Data_AppSettings_ISavedQueryService_SaveDefaults
  name: SaveDefaults
  nameWithType: ISavedQueryService.SaveDefaults
  fullName: Innova.Data.AppSettings.ISavedQueryService.SaveDefaults
memberLayout: SeparatePages
