### YamlMime:ManagedReference
items:
- uid: Innova.Rest.Server.Settings
  commentId: N:Innova.Rest.Server.Settings
  id: Settings
  parent: Innova.Rest.Server
  children:
  - Innova.Rest.Server.Settings.CachedSettingsEntityService
  - Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  - Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
  - Innova.Rest.Server.Settings.ServerSettingsEntityServiceFactory
  - Innova.Rest.Server.Settings.ServerUserSettingService`1
  langs:
  - csharp
  - vb
  name: Innova.Rest.Server.Settings
  nameWithType: Innova.Rest.Server.Settings
  fullName: Innova.Rest.Server.Settings
  type: Namespace
  assemblies:
  - Innova.Rest.Server
references:
- uid: Innova.Rest.Server.Settings.CachedSettingsEntityService
  commentId: T:Innova.Rest.Server.Settings.CachedSettingsEntityService
  href: Innova.Rest.Server.Settings.CachedSettingsEntityService.html
  name: CachedSettingsEntityService
  nameWithType: CachedSettingsEntityService
  fullName: Innova.Rest.Server.Settings.CachedSettingsEntityService
- uid: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  commentId: T:Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
  parent: Innova.Rest.Server.Settings
  href: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory.html
  name: IServerSettingsEntityServiceFactory
  nameWithType: IServerSettingsEntityServiceFactory
  fullName: Innova.Rest.Server.Settings.IServerSettingsEntityServiceFactory
- uid: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
  commentId: T:Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
  href: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer.html
  name: IServiceCollectionExtensionsRestServer
  nameWithType: IServiceCollectionExtensionsRestServer
  fullName: Innova.Rest.Server.Settings.IServiceCollectionExtensionsRestServer
- uid: Innova.Rest.Server.Settings.ServerSettingsEntityServiceFactory
  commentId: T:Innova.Rest.Server.Settings.ServerSettingsEntityServiceFactory
  href: Innova.Rest.Server.Settings.ServerSettingsEntityServiceFactory.html
  name: ServerSettingsEntityServiceFactory
  nameWithType: ServerSettingsEntityServiceFactory
  fullName: Innova.Rest.Server.Settings.ServerSettingsEntityServiceFactory
- uid: Innova.Rest.Server.Settings.ServerUserSettingService`1
  commentId: T:Innova.Rest.Server.Settings.ServerUserSettingService`1
  href: Innova.Rest.Server.Settings.ServerUserSettingService-1.html
  name: ServerUserSettingService<T>
  nameWithType: ServerUserSettingService<T>
  fullName: Innova.Rest.Server.Settings.ServerUserSettingService<T>
  nameWithType.vb: ServerUserSettingService(Of T)
  fullName.vb: Innova.Rest.Server.Settings.ServerUserSettingService(Of T)
  name.vb: ServerUserSettingService(Of T)
  spec.csharp:
  - uid: Innova.Rest.Server.Settings.ServerUserSettingService`1
    name: ServerUserSettingService
    href: Innova.Rest.Server.Settings.ServerUserSettingService-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Innova.Rest.Server.Settings.ServerUserSettingService`1
    name: ServerUserSettingService
    href: Innova.Rest.Server.Settings.ServerUserSettingService-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Innova.Rest.Server.Settings
  commentId: N:Innova.Rest.Server.Settings
  href: Innova.html
  name: Innova.Rest.Server.Settings
  nameWithType: Innova.Rest.Server.Settings
  fullName: Innova.Rest.Server.Settings
  spec.csharp:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Settings
    name: Settings
    href: Innova.Rest.Server.Settings.html
  spec.vb:
  - uid: Innova
    name: Innova
    href: Innova.html
  - name: .
  - uid: Innova.Rest
    name: Rest
    href: Innova.Rest.html
  - name: .
  - uid: Innova.Rest.Server
    name: Server
    href: Innova.Rest.Server.html
  - name: .
  - uid: Innova.Rest.Server.Settings
    name: Settings
    href: Innova.Rest.Server.Settings.html
memberLayout: SeparatePages
